#!/usr/bin/env node
/**
 * T3 — write `deploy/crds/*.yaml` from the schema modules in `src/crds/*.ts`.
 *
 * ```
 * pnpm --filter @ever-works/hosting-crds generate:crds         # write the manifests
 * pnpm --filter @ever-works/hosting-crds generate:crds:check   # fail if they have drifted
 * ```
 *
 * Both forms build first (`tsup`) and then run this file, because Node cannot execute the
 * TypeScript sources directly: their relative imports are `.js`-specified ESM (the house style in
 * `packages/plugins/k8s/**`), and only the bundler maps those back to `.ts`. The **drift gate is
 * the test**, not this script — `src/crds/__tests__/crds.spec.ts` imports the schemas from source
 * and compares the committed bytes, so `pnpm test` catches drift without building anything. This
 * script is the writer, and `--check` is the same comparison for a CI job that would rather have a
 * one-line diff report than a failing test.
 *
 * Paths are resolved from this file's own URL, never from the working directory, so the command
 * behaves identically from the package, from the repo root and from CI.
 */
import { createHash } from 'node:crypto';
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CRD_DIRECTORY, crdManifestFiles } from '../dist/index.js';

const outputDirectory = fileURLToPath(new URL(`../${CRD_DIRECTORY}/`, import.meta.url));
const checkOnly = process.argv.includes('--check');

/** The SHA-256 of a file's bytes, or `null` when it does not exist. */
function sha256OfFile(path: string): string | null {
	try {
		return createHash('sha256').update(readFileSync(path)).digest('hex');
	} catch {
		return null;
	}
}

mkdirSync(outputDirectory, { recursive: true });
const files = crdManifestFiles();
const expectedNames = new Set(files.map((file) => file.fileName));
const drifted: string[] = [];
let strays: string[] = [];

for (const file of files) {
	const path = join(outputDirectory, file.fileName);
	const before = sha256OfFile(path);

	if (checkOnly) {
		const committed = before === null ? null : readFileSync(path, 'utf8');
		if (committed !== file.yaml) {
			drifted.push(file.fileName);
			console.log(`drift  ${CRD_DIRECTORY}/${file.fileName}`);
		} else {
			console.log(`ok     ${CRD_DIRECTORY}/${file.fileName} sha256=${before}`);
		}
		continue;
	}

	writeFileSync(path, file.yaml, 'utf8');
	const after = sha256OfFile(path);
	console.log(
		`${before === after ? 'same  ' : 'wrote '} ${CRD_DIRECTORY}/${file.fileName} bytes=${Buffer.byteLength(file.yaml)} sha256=${after}`
	);
}

// A YAML file in the CRD directory that this generator does not produce is drift too: the zone's
// GitOps applies the whole directory, so a stray manifest would be installed by nobody's schema.
if (checkOnly) {
	strays = readdirSync(outputDirectory)
		.filter((name) => name.endsWith('.yaml') && !expectedNames.has(name))
		.sort();
	for (const stray of strays) console.log(`stray  ${CRD_DIRECTORY}/${stray} (not generated by this script)`);
}

if (checkOnly && (drifted.length > 0 || strays.length > 0)) {
	console.error(
		`\n${drifted.length} drifted and ${strays.length} stray CRD manifest(s). Run \`pnpm --filter @ever-works/hosting-crds generate:crds\` and commit the result.`
	);
	process.exit(1);
}
