export const README = [
	'## What is the Activepieces Automation plugin?',
	'',
	'This plugin delegates directory generation steps to an [Activepieces](https://www.activepieces.com) flow.',
	'Activepieces is the AI-first, open-source automation platform for every team.',
	'Instead of running the built-in generation pipeline, you build your own automated flow in Activepieces and this plugin triggers it during the appropriate generation stage.',
	'',
	'## Why use it?',
	'',
	'- **Full control** — design your own generation logic visually in Activepieces',
	'- **Custom data sources** — connect to any of Activepieces 280+ pieces (APIs, databases, scrapers)',
	'- **Flexible AI models** — call any AI provider via Activepieces actions',
	'- **Sync execution** — webhook trigger waits synchronously for flow output',
	'- **Deduplication** — existing directory items are summarized and passed to the flow to avoid duplicates',
	'',
	'## How it works',
	'',
	'1. **Validate** — checks your API key against the Activepieces API and verifies the target flow is enabled',
	'2. **Prepare Payload** — builds the input with directory metadata, existing items summary, and custom parameters',
	'3. **Execute Flow** — calls the Activepieces flow webhook (synchronously by default) with the payload',
	'4. **Collect Results** — parses the flow output into structured directory items with categories, tags, and brands',
	'5. **Capture Screenshots** — optionally captures screenshots for generated items using the configured screenshot provider',
	'6. **Cleanup** — releases resources',
	'',
	'## API integration',
	'',
	'The plugin talks to the Activepieces REST API directly (no SDK):',
	'',
	'- **Auth**: `Authorization: Bearer <API_KEY>` (generated from the Platform Dashboard)',
	'- **Base URL**: `https://cloud.activepieces.com/api/v1` (configurable for self-hosted)',
	'- **Flows**: `GET /flows/{id}` to validate the flow',
	'- **Webhook trigger**: `POST /webhooks/{flowId}/sync` (sync mode) or `POST /webhooks/{flowId}` (async)',
	'- **Flow runs**: `GET /flow-runs` to inspect recent executions',
	'',
	'## Data passing strategies',
	'',
	'- **Inline summary** (default) — directory metadata and a sample of existing items are sent in the webhook payload',
	'- **GitHub repository** — pass a repo URL and access token so the flow can read the full dataset directly',
	'',
	'## Flow input & output',
	'',
	'Your Activepieces flow must start with a **Webhook trigger** so it can be invoked by this plugin.',
	'The webhook trigger receives the JSON payload as the trigger output, accessible in subsequent steps.',
	'',
	'<details>',
	'<summary><strong>Input your flow receives</strong></summary>',
	'',
	'```json',
	'{',
	'  "metadata": {',
	'    "directoryId": "dir-123",',
	'    "directoryName": "Best AI Tools",',
	'    "directorySlug": "best-ai-tools",',
	'    "directoryDescription": "A curated list of the best AI tools",',
	'    "prompt": "Find the best AI writing tools",',
	'    "generationMethod": "create-update",',
	'    "targetItems": 50',
	'  },',
	'  "existingSummary": {',
	'    "totalItems": 10,',
	'    "categories": ["Writing", "Image Generation"],',
	'    "tags": ["free", "open-source"],',
	'    "sampleItems": [',
	'      { "name": "ChatGPT", "url": "https://chat.openai.com" }',
	'    ]',
	'  },',
	'  "flowParams": {}',
	'}',
	'```',
	'',
	'- `existingSummary` is optional — absent if the directory is empty or the user disabled it',
	'- `flowParams` contains any custom key-value pairs passed from the Advanced form section',
	'- `metadata.targetItems` is the number of new items the user wants',
	'',
	'</details>',
	'',
	'<details>',
	'<summary><strong>Output your flow must return</strong></summary>',
	'',
	'End your flow with a **Return Response** action that returns a JSON object with an `items` array:',
	'',
	'```json',
	'{',
	'  "items": [',
	'    {',
	'      "name": "Tool Name",',
	'      "description": "A concise description (1-3 sentences)",',
	'      "url": "https://example.com",',
	'      "category": "Category Name",',
	'      "tags": ["tag1", "tag2"],',
	'      "content": "Optional longer markdown content",',
	'      "brand": "Optional brand name",',
	'      "images": ["https://example.com/screenshot.png"]',
	'    }',
	'  ]',
	'}',
	'```',
	'',
	'**Required fields:** `name`, `description`, `url`, `category`, `tags`',
	'',
	'**Optional fields:** `content` (stored as markdown), `brand`, `images`',
	'',
	'</details>',
	'',
	'## Getting started',
	'',
	'1. Build a flow in [Activepieces](https://www.activepieces.com) starting with a **Webhook trigger**',
	'2. Add steps to fetch and shape data, then end with a **Return Response** action',
	'3. Generate an API key from the Activepieces Platform Dashboard',
	'4. Enable this plugin and enter your API key, base URL, and project ID in plugin settings',
	'5. When generating a directory, select Activepieces as the pipeline and provide the flow ID'
].join('\n');
