packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@sentry-internal/node-cpu-profiler'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - bcrypt
  - better-sqlite3
  - core-js
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
  - sqlite3
