import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	platformSidebar: [
		'index',
		'overview',
		'getting-started',
		'installation',
		'development-workflow',
		'environment-variables',
		'monorepo-structure',
		{
			type: 'category',
			label: 'Architecture',
			link: { type: 'doc', id: 'architecture' },
			items: [
				'architecture/agent-package',
				'architecture/pipeline-system',
				'architecture/event-system',
				'architecture/generator-system',
				'architecture/facade-pattern',
				'architecture/contracts-package',
				'architecture/web-app',
				'architecture/caching',
				'architecture/events-deep-dive',
				'architecture/dependency-injection',
				// Agents/Skills/Tasks PR #1017 — reference for the 6 new
				// Nest injection tokens (dispatchers, post-processors,
				// git facade, plugin-tools facade) operators bind to
				// custom adapters.
				'architecture/agent-injection-tokens',
				'architecture/module-system',
				'architecture/middleware-pipeline',
				'architecture/configuration-management',
				'architecture/dto-validation',
				'architecture/error-handling-patterns',
				'architecture/guards-interceptors',
				'architecture/nestjs-modules',
				'architecture/typeorm-patterns'
			]
		},
		{
			type: 'category',
			label: 'Features',
			collapsed: false,
			link: { type: 'doc', id: 'features/index' },
			items: [
				'features/creating-a-work',
				'features/missions',
				'features/ideas',
				'features/mission-templates',
				'features/budgets-and-usage',
				'features/community-pr-processing',
				'features/work-changelog',
				'features/collections',
				'features/item-source-validation',
				'features/scheduled-updates',
				'features/generation-cancellation',
				'features/works-config',
				'features/work-import',
				'features/work-members',
				'features/comparisons',
				'features/advanced-prompts',
				'features/git-operations',
				'features/taxonomy-system',
				'features/api-keys',
				'features/custom-domains',
				'features/k8s-deployment',
				'features/mcp-server',
				'features/data-management'
			]
		},
		{
			type: 'category',
			label: 'API Reference',
			items: [
				'api/index',
				'api/authentication',
				'api/works',
				// Agents/Skills/Tasks PR #1017 — Phase 20.2 reference
				// pages for the 3 new feature families.
				'api/agents',
				'api/skills',
				'api/tasks',
				'api/ai-conversation',
				'api/deployment',
				'api/other-modules',
				'api/subscriptions',
				'api/notifications',
				'api/mail',
				'api/plugins-api',
				'api/plugin-capabilities',
				'api/twenty-crm',
				'api/email-templates',
				'api/integrations-module',
				'api/screenshot-capability',
				'api/deploy-capability',
				'api/git-provider-capability',
				'api/oauth-capability',
				'api/search-capability',
				'api/device-auth-capability',
				'api/activity-log',
				'api/template-catalog',
				'api/account',
				'api/error-handling',
				'api/guards-interceptors',
				'api/websocket-events'
			]
		},
		{
			type: 'category',
			label: 'CLI Reference',
			items: [
				'cli/index',
				'cli/commands',
				'cli/auth-commands',
				'cli/work-commands',
				'cli/internal-cli',
				'cli/plugin-commands',
				'cli/generation-commands'
			]
		},
		{
			type: 'category',
			label: 'AI & Generation',
			items: [
				'ai-agents/index',
				'ai-agents/model-router',
				'ai-agents/data-generation',
				'ai-agents/markdown-generation',
				'ai-agents/website-generation'
			]
		},
		{
			type: 'category',
			label: 'Database',
			link: { type: 'doc', id: 'database' },
			items: ['database/entities', 'database/repositories', 'database/migrations']
		},
		{
			type: 'category',
			label: 'Plugin System',
			items: [
				'plugin-system/index',
				'plugin-system/architecture',
				'plugin-system/settings',
				'plugin-system/creating-a-plugin',
				{
					type: 'category',
					label: 'Category Guides',
					collapsed: false,
					items: [
						'plugin-system/creating-ai-provider-plugin',
						'plugin-system/creating-search-plugin',
						'plugin-system/creating-screenshot-plugin',
						'plugin-system/creating-content-extractor-plugin',
						'plugin-system/creating-pipeline-plugin',
						'plugin-system/creating-deployment-plugin',
						'plugin-system/creating-data-source-plugin'
					]
				},
				'plugin-system/built-in-plugins',
				'plugin-system/api-reference',
				'plugin-system/plugin-categories',
				'plugin-system/ai-provider-plugins',
				'plugin-system/search-plugins',
				'plugin-system/content-extraction-plugins',
				'plugin-system/deployment-plugins',
				'plugin-system/data-source-plugins',
				'plugin-system/pipeline-plugins',
				'plugin-system/testing-plugins',
				'plugin-system/brave-search-plugin',
				'plugin-system/exa-search-plugin',
				'plugin-system/jina-plugin',
				'plugin-system/firecrawl-plugin',
				'plugin-system/github-plugin',
				'plugin-system/vercel-plugin',
				'plugin-system/openai-plugin',
				'plugin-system/anthropic-plugin',
				'plugin-system/ollama-plugin',
				'plugin-system/groq-plugin',
				'plugin-system/tavily-plugin',
				'plugin-system/apify-plugin',
				'plugin-system/notion-plugin',
				'plugin-system/mistral-plugin',
				'plugin-system/perplexity-plugin',
				'plugin-system/openrouter-plugin',
				'plugin-system/scrapfly-plugin',
				'plugin-system/brightdata-plugin',
				'plugin-system/google-ai-plugin',
				'plugin-system/deepseek-plugin',
				'plugin-system/xai-plugin',
				'plugin-system/together-plugin',
				'plugin-system/fireworks-plugin',
				'plugin-system/cohere-plugin',
				'plugin-system/serpapi-plugin',
				'plugin-system/urlbox-plugin',
				'plugin-system/screenshotone-plugin',
				'plugin-system/valyu-plugin',
				'plugin-system/pdf-extractor-plugin',
				'plugin-system/local-extractor-plugin',
				'plugin-system/local-content-extractor-plugin',
				'plugin-system/agent-pipeline-plugin',
				'plugin-system/standard-pipeline-plugin',
				'plugin-system/comparison-generator-plugin',
				'plugin-system/claude-code-plugin',
				'plugin-system/claude-managed-agent-plugin',
				'plugin-system/codex-plugin',
				'plugin-system/gemini-plugin',
				'plugin-system/opencode-plugin',
				'plugin-system/make-plugin',
				'plugin-system/sim-ai-plugin',
				'plugin-system/zapier-plugin',
				'plugin-system/linkup-plugin',
				'plugin-system/langfuse-plugin',
				'plugin-system/vercel-ai-gateway-plugin',
				'plugin-system/github-plugin-deep-dive',
				'plugin-system/vercel-plugin-deep-dive',
				'plugin-system/openai-plugin-deep-dive',
				'plugin-system/anthropic-plugin-deep-dive',
				'plugin-system/firecrawl-plugin-deep-dive',
				'plugin-system/brave-plugin-deep-dive',
				'plugin-system/notion-plugin-deep-dive',
				'plugin-system/apify-plugin-deep-dive',
				'plugin-system/ollama-plugin-deep-dive',
				'plugin-system/exa-plugin-deep-dive',
				'plugin-system/standard-pipeline-deep-dive',
				'plugin-system/agent-pipeline-deep-dive',
				'plugin-system/claude-code-deep-dive',
				'plugin-system/pdf-extractor-deep-dive',
				'plugin-system/groq-plugin-deep-dive',
				'plugin-system/google-plugin-deep-dive',
				'plugin-system/mistral-plugin-deep-dive',
				'plugin-system/openrouter-plugin-deep-dive',
				'plugin-system/screenshotone-deep-dive',
				'plugin-system/urlbox-deep-dive'
			]
		},
		{
			type: 'category',
			label: 'Agent Services',
			items: [
				'agent-services/work-lifecycle',
				'agent-services/work-generation',
				'agent-services/work-scheduling',
				'agent-services/repository-management',
				'agent-services/items-generator',
				'agent-services/generator-form-schema',
				'agent-services/work-query',
				'agent-services/work-members',
				'agent-services/dto-reference',
				'agent-services/config-module',
				'agent-services/work-detail-service',
				'agent-services/work-import-service',
				'agent-services/work-ownership-service',
				'agent-services/work-taxonomy-service',
				'agent-services/work-schedule-dispatcher',
				'agent-services/distributed-task-lock',
				'agent-services/work-advanced-prompts',
				'agent-services/community-pr-service',
				'agent-services/import-system',
				'agent-services/comparison-generator-service',
				'agent-services/agent-dto-reference',
				'agent-services/agent-work-module',
				'agent-services/agent-generation-module',
				'agent-services/agent-pipeline-module',
				'agent-services/agent-taxonomy-module',
				'agent-services/agent-items-module',
				'agent-services/agent-deployment-module',
				'agent-services/agent-ai-module',
				'agent-services/agent-storage-module',
				'agent-services/agent-scheduling-module',
				'agent-services/agent-integration-module',
				'agent-services/cache-module',
				'agent-services/constants-module',
				'agent-services/database-module',
				'agent-services/entities-module',
				'agent-services/events-module',
				'agent-services/facades-module',
				'agent-services/notifications-module',
				'agent-services/pipeline-module',
				'agent-services/plugins-module',
				'agent-services/subscriptions-module',
				'agent-services/work-operations-module'
			]
		},
		{
			type: 'category',
			label: 'Packages',
			items: [
				'packages/tasks-package',
				'packages/monitoring-package',
				'packages/cli-shared-package',
				'packages/plugin-api-layer',
				'packages/plugin-ai-module',
				'packages/plugin-git-module',
				'packages/plugin-helpers',
				'packages/plugin-keywords',
				'packages/plugin-testing-framework',
				'packages/contracts-types',
				'packages/agent-package-overview',
				'packages/plugins-package-overview'
			]
		},
		{
			type: 'category',
			label: 'DevOps & Deployment',
			items: [
				'devops/docker',
				'devops/ci-cd',
				'devops/digital-ocean',
				'devops/monitoring',
				'devops/trigger-dev',
				'devops/scaling',
				'devops/security',
				'devops/github-workflows-deep-dive',
				'devops/docker-compose',
				'devops/environment-management',
				'devops/logging-aggregation',
				'devops/disaster-recovery',
				'devops/performance-monitoring',
				'devops/kubernetes',
				'devops/k8s-e2e-runbook'
			]
		},
		{
			type: 'category',
			label: 'Web Dashboard',
			items: [
				'web-dashboard/overview',
				'web-dashboard/components',
				'web-dashboard/configuration',
				'web-dashboard/server-actions',
				'web-dashboard/hooks-reference',
				'web-dashboard/ai-components',
				'web-dashboard/settings-pages',
				'web-dashboard/api-client',
				'web-dashboard/work-pages',
				'web-dashboard/plugin-pages',
				'web-dashboard/auth-pages',
				'web-dashboard/generation-ui',
				'web-dashboard/navigation-routing',
				'web-dashboard/form-system',
				'web-dashboard/data-tables',
				'web-dashboard/deployment-ui',
				'web-dashboard/members-ui',
				'web-dashboard/history-ui',
				'web-dashboard/items-ui',
				'web-dashboard/schedule-ui',
				'web-dashboard/dashboard-layout',
				'web-dashboard/ai-components-deep-dive',
				'web-dashboard/auth-components',
				'web-dashboard/settings-components',
				'web-dashboard/ui-component-library',
				'web-dashboard/work-detail-components',
				'web-dashboard/import-flow-components',
				'web-dashboard/web-hooks-reference',
				'web-dashboard/server-actions-deep-dive',
				'web-dashboard/web-api-routes'
			]
		},
		{
			type: 'category',
			label: 'Testing',
			items: ['testing/overview', 'testing/writing-tests', 'testing/test-infrastructure']
		},
		{
			type: 'category',
			label: 'Advanced Topics',
			items: [
				'advanced/import-system',
				'advanced/comparison-generator',
				'advanced/community-pr-deep-dive',
				'advanced/subscription-billing',
				'advanced/webhook-system',
				'advanced/caching-strategy',
				'advanced/error-recovery',
				'advanced/multi-tenancy',
				'advanced/rate-limiting',
				'advanced/database-optimization',
				'advanced/monitoring-deep-dive',
				'advanced/security-hardening',
				'advanced/performance-tuning',
				'advanced/ai-model-routing',
				'advanced/api-versioning',
				'advanced/event-listeners',
				'advanced/pipeline-customization',
				'advanced/plugin-development-guide'
			]
		},
		{
			type: 'category',
			label: 'Resources',
			items: ['comparison', 'glossary', 'faq', 'support', 'contributing', 'changelog', 'roadmap']
		}
	]
};

export default sidebars;
