import { APP_BUILD_WORKFLOW_BRANCH, APP_BUILD_WORKFLOW_PATH, sha256Hex } from '@ever-works/contracts';
import type { RepositoryCommitInput, RepositoryWriteErrorCode, RepositoryWriter } from '@ever-works/plugin';

import { isBranchProtected, type BranchProtectionPort, type BranchProtectionVerdict } from './branch-protection.js';

/**
 * APW-05 T9 — delivering the generated workflow (plan §4.6, `APW05-G16`, R-4).
 *
 * ## The one rule that shapes everything here
 *
 * **The plugin never clones.** Every write goes through the `RepositoryWriter` the
 * facade binds (APW-03's `commitFiles?` via `GitFacadeService`), whose four members
 * are all this file calls: `getFileContent`, `commitFiles`, `createBranch`,
 * `createPullRequest`. Writing one file must not clone a 1 GB repository
 * (plan §1.2), and the T9 spec asserts that no clone-shaped call exists — the fake
 * writer has no clone member to call.
 *
 * ## The paths, and which one a branch gets
 *
 * | Branch state                                                  | Path                                     |
 * | ------------------------------------------------------------- | ---------------------------------------- |
 * | File on the tracked branch already equals the generated bytes  | `unchanged`, **zero write calls**        |
 * | File exists, its sha256 is neither the stored one nor the new one | **hand edit** → pull request, never an overwrite on the tracked branch (FR-9) |
 * | `createdByAppWork === false` (a Link relation)                 | pull request, always (R-4)               |
 * | Protected (reviews, status checks, ruleset, or a 403)          | pull request                             |
 * | Otherwise                                                      | direct commit onto the tracked branch    |
 * | **No workflow content** (T42: no build and no check remains)   | pull request — the removal of §4.6 step 8, never a direct commit (FR-70) |
 *
 * The pull request path reuses **one** pull request: `ever-works/build-workflow` is
 * created from the tracked head when absent, the commit lands on it, and the pull
 * request is then ALWAYS asked for. Reuse is proven by GitHub, never assumed from
 * a stored number: when an open pull request already exists for that head, the
 * create is refused with `pullRequestExists` (the contract's code, or GitHub's own
 * 422 "A pull request already exists" when nothing translated it), and that
 * refusal is what `pullRequestUpdated` means (ACC-05-02). The stored
 * `pullRequestNumber`/`pullRequestUrl` are only echoed back so the reused pull
 * request keeps its link; a stored pull request the owner CLOSED is therefore
 * replaced by a new one rather than "updated" forever. A second and a third
 * preparation leave exactly one open pull request, and a preparation whose bytes
 * are already on that branch commits nothing at all.
 *
 * ## The refusals
 *
 *   - `nonFastForward` — a race: retry the direct write, at most
 *     {@link WORKFLOW_WRITE_MAX_ATTEMPTS} attempts in total (plan §4.6 step 2's
 *     "up to 3 times"), then `blocked workflowWriteFailed`.
 *   - `refRejectedByRule` — a protection or ruleset the pre-check could not see:
 *     switch to the pull request path **once** and never retry the direct write.
 *     If the pull request path is refused the same way, stop with
 *     `blocked workflowWriteFailed`, detail `{ cause: 'branchRules' }` — never a
 *     loop. Its copy is "The build workflow could not be written." plus "A rule on
 *     this repository refuses the change." (plan §4.6 steps 2–3).
 *   - a read-back that does not match: retried **once**; still mismatched →
 *     `blocked workflowWriteFailed`, and `storedWorkflowSha256` stays untouched —
 *     only a matching read-back may store a hash (FR-8).
 *
 * ## Where the branch head comes from
 *
 * `commitFiles` needs the commit the caller believes the branch is at, and the
 * `RepositoryWriter` contract has no `getBranch` member. Two ways in, both within
 * the four:
 *
 *   1. `input.resolveTrackedHead` — the facade, which already holds
 *      `GitFacadeService`, passes the real head (T16's binding);
 *   2. otherwise {@link readBranchHead} calls `createBranch(branch, branch)`, which
 *      the contract documents as returning an existing branch rather than
 *      recreating it — a read that happens to be spelled as a create.
 *
 * The head is re-read on **every** attempt, which is what makes the
 * `nonFastForward` retry real rather than a repeat of the same stale commit.
 */

/** The commit message of a file that did not exist (plan §4.6 step 2). */
export const WORKFLOW_COMMIT_MESSAGE_ADD = 'Add Ever Works build workflow';

/** The commit message of a file the platform is changing (plan §4.6 step 2). */
export const WORKFLOW_COMMIT_MESSAGE_UPDATE = 'Update Ever Works build workflow';

/** The commit message of the removal T42 proposes (plan §4.6 step 8, FR-70). */
export const WORKFLOW_COMMIT_MESSAGE_REMOVE = 'Remove Ever Works build workflow';

/** The pull request title (plan §4.6 step 3). */
export const WORKFLOW_PULL_REQUEST_TITLE = 'Add Ever Works build workflow';

/**
 * The removal pull request's title (T42, plan §4.6 step 8, FR-70).
 *
 * Not {@link WORKFLOW_PULL_REQUEST_TITLE}: a reviewer opening "Add Ever Works
 * build workflow" and finding every job deleted would be reading the wrong
 * sentence, and `ever-works/build-workflow` may already carry the open pull
 * request this one updates.
 */
export const WORKFLOW_REMOVAL_PULL_REQUEST_TITLE = 'Remove the Ever Works build workflow';

/** The pull request body — what a reviewer is looking at, and what not to do with it. */
export const WORKFLOW_PULL_REQUEST_BODY =
	'Ever Works generated this workflow from the App spec. It builds the image for this App Work on GitHub-hosted runners and publishes it to GHCR. Hand edits to this file are never overwritten: Ever Works proposes its changes as pull requests.';

/**
 * The removal pull request's body (T42, FR-70).
 *
 * It says what merging does, in the file's own terms, because the platform cannot
 * delete a file itself: the `RepositoryWriter` T9 is bound to has no deletion
 * member (plan §4.1:749–751 fixes its four), so the removal travels as the empty
 * bytes §4.6 step 8 calls "removing the jobs" — and the owner who would rather
 * delete the file outright is told so.
 */
export const WORKFLOW_REMOVAL_PULL_REQUEST_BODY =
	'Ever Works generated this workflow from the App spec. The App spec no longer declares a build or a check, so this pull request removes every job from it. Merge it to remove the workflow, or delete the file outright — Ever Works never writes to the tracked branch to remove a file.';

/**
 * How many direct-write attempts are made in total (plan §4.6 step 2: "A
 * `nonFastForward` error retries from step 1 up to 3 times").
 *
 * Read as at most three attempts, which is the stricter of the two readings of
 * "up to 3 times" and therefore cannot exceed the bound the plan states.
 */
export const WORKFLOW_WRITE_MAX_ATTEMPTS = 3;

/** How many read-backs one successful write gets: the first, plus the plan's single retry (FR-8). */
export const WORKFLOW_READ_BACK_ATTEMPTS = 2;

/** The tracked branch and the App Work's relation to it. */
export interface WorkflowRepositoryCoordinates {
	readonly owner: string;
	readonly repo: string;
	readonly trackedBranch: string;
	/** `false` for a Link relation — that repository is not ours to write into (R-4). */
	readonly createdByAppWork: boolean;
}

/** What the caller asks to deliver, and what it remembers from the last delivery. */
export interface WorkflowWriteInput {
	readonly repository: WorkflowRepositoryCoordinates;
	/** The generated bytes. */
	readonly content: string;
	/** The workflow sha256 the platform last wrote, or `null` — the other half of hand-edit detection (FR-9). */
	readonly lastWrittenWorkflowSha256: string | null;
	/**
	 * The pull request the platform recorded for this App Work (§3.1b), when there is one.
	 * Echoed back when GitHub reports an open pull request for the head; never used to
	 * decide that one is open.
	 */
	readonly pullRequestNumber?: number | null;
	/** That pull request's URL, echoed back on the reuse path (the writer never re-reads it). */
	readonly pullRequestUrl?: string | null;
	/** Overrides {@link APP_BUILD_WORKFLOW_PATH}; exists so a spec can name its own path. */
	readonly workflowPath?: string;
	/** The facade's branch-head read (T16). Without it, {@link readBranchHead} is used. */
	readonly resolveTrackedHead?: () => Promise<string>;
}

/** What the delivery decided — the transport state §3.1b maps onto `workflowState`. */
export interface WorkflowWriteResult {
	/**
	 * The delivery outcome.
	 *
	 * `'blocked'` is this writer's own terminal state and is **not** a member of
	 * `PrepareRepositoryResult.workflow.state` (which has five): the caller maps it
	 * onto `PrepareRepositoryResult.blocked` with reason `workflowWriteFailed`, and
	 * must not pass it through as a stored workflow state.
	 */
	readonly state: 'unchanged' | 'committed' | 'pullRequestOpened' | 'pullRequestUpdated' | 'editedByHand' | 'blocked';
	readonly commitSha?: string;
	readonly pullRequestNumber?: number;
	readonly pullRequestUrl?: string;
	/**
	 * The sha256 the platform may store as `lastWrittenWorkflowSha256`, or `null`
	 * when nothing on the tracked branch has been proven to equal the generated
	 * bytes. Only a matching read-back sets it (FR-8, plan §4.6 step 4).
	 */
	readonly storedWorkflowSha256: string | null;
	readonly blocked?: { readonly reason: 'workflowWriteFailed'; readonly detail: { readonly cause: string } };
}

/** A file as the writer reads it back — `encoding` decides whether the content needs decoding. */
interface ReadFile {
	readonly content: string;
	readonly encoding: string;
}

/** Decode a `getFileContent` answer to text — GitHub's contents API answers base64. */
function decodeFileContent(file: ReadFile): string {
	return file.encoding === 'base64' ? Buffer.from(file.content, 'base64').toString('utf-8') : file.content;
}

/** `null` when the file does not exist; otherwise its sha256 as text (plan §4.6 steps 4–5). */
async function readFileSha256(writer: RepositoryWriter, path: string, ref?: string): Promise<string | null> {
	const file = await writer.getFileContent(path, ref);
	if (!file) return null;
	return sha256Hex(decodeFileContent(file as ReadFile));
}

/**
 * The tracked branch's head commit.
 *
 * `createBranch(branch, branch)` is the contract's documented "an existing branch
 * is returned rather than recreated" path; a caller with a real head read passes
 * `input.resolveTrackedHead` instead.
 */
async function readBranchHead(writer: RepositoryWriter, branch: string): Promise<string> {
	const existing = await writer.createBranch(branch, branch);
	return existing.commit;
}

/** The refusal code of a thrown write error, if it is one of the codes the contract names. */
export function repositoryWriteErrorCode(error: unknown): RepositoryWriteErrorCode | null {
	const candidate = error as { code?: unknown; reason?: unknown } | null | undefined;
	for (const value of [candidate?.code, candidate?.reason]) {
		if (value === 'nonFastForward' || value === 'refRejectedByRule' || value === 'pullRequestExists') return value;
	}
	return null;
}

/** GitHub's wording for a second pull request on a head that already has an open one. */
const PULL_REQUEST_ALREADY_EXISTS = /pull request already exists/i;

/**
 * True when a `createPullRequest` refusal says the head already has an OPEN pull request.
 *
 * Primarily the contract's code (`pullRequestExists`, what a facade-bound writer
 * throws). The fallback is GitHub's own answer as Octokit throws it — status 422
 * AND the "already exists" wording in the message or in any `errors[].message` —
 * because a writer bound straight over the github plugin passes the `RequestError`
 * through untranslated. Both halves are required: another 422 ("No commits
 * between …") must still throw, and so must the wording without the status.
 */
export function isPullRequestAlreadyExistsError(error: unknown): boolean {
	if (repositoryWriteErrorCode(error) === 'pullRequestExists') return true;
	const candidate = error as
		| {
				status?: unknown;
				message?: unknown;
				response?: { data?: { message?: unknown; errors?: unknown } };
		  }
		| null
		| undefined;
	if (candidate?.status !== 422) return false;
	const messages: unknown[] = [candidate.message, candidate.response?.data?.message];
	const errors = candidate.response?.data?.errors;
	if (Array.isArray(errors)) {
		for (const entry of errors) messages.push((entry as { message?: unknown } | null)?.message);
	}
	return messages.some((message) => typeof message === 'string' && PULL_REQUEST_ALREADY_EXISTS.test(message));
}

/** One file, ready for {@link RepositoryWriter.commitFiles}. */
function commitFile(path: string, content: string) {
	return { path, content, encoding: 'utf-8' as const };
}

/** The three strings one delivery commits and opens its pull request with. */
interface DeliveryCopy {
	readonly commitMessage: string;
	readonly title: string;
	readonly body: string;
}

/** Writing or updating the file §4.6 steps 2–3 deliver. */
const DELIVERY_COPY: DeliveryCopy = {
	commitMessage: WORKFLOW_COMMIT_MESSAGE_UPDATE,
	title: WORKFLOW_PULL_REQUEST_TITLE,
	body: WORKFLOW_PULL_REQUEST_BODY
};

/** Proposing the removal of §4.6 step 8, whose diff takes the file's jobs away (FR-70). */
const REMOVAL_COPY: DeliveryCopy = {
	commitMessage: WORKFLOW_COMMIT_MESSAGE_REMOVE,
	title: WORKFLOW_REMOVAL_PULL_REQUEST_TITLE,
	body: WORKFLOW_REMOVAL_PULL_REQUEST_BODY
};

/**
 * Deliver the generated workflow (plan §4.6).
 *
 * `protection` is the branch-rules port; leave it out when the caller has no
 * protection read (a fork the platform owns, a spec), in which case only
 * `createdByAppWork` and hand-edit detection decide the path.
 *
 * **Empty content is T42's removal request** (plan §4.6 step 8, FR-70): the
 * generator answers `''` when neither a build nor a check remains, and
 *
 *   - with no file on the tracked branch there is nothing to remove — no write, no
 *     pull request, `unchanged` (and no stored hash: nothing was proven);
 *   - with one, the removal is **proposed by pull request** and never committed to
 *     the tracked branch: §4.6 step 8's "never deleted directly". The branch
 *     protections of steps 1–2 are not consulted, because there is no direct path
 *     to protect; `createdByAppWork` and the hand-edit verdict still decide the
 *     state the caller stores (§3.1b).
 */
export async function writeWorkflow(
	input: WorkflowWriteInput,
	writer: RepositoryWriter,
	protection?: BranchProtectionPort
): Promise<WorkflowWriteResult> {
	const path = input.workflowPath ?? APP_BUILD_WORKFLOW_PATH;
	const { owner, repo, trackedBranch, createdByAppWork } = input.repository;
	const contentSha256 = sha256Hex(input.content);

	// Step 5 — hand-edit detection, before any write. `lastWritten` null with a file
	// present means the platform never wrote it: a hand edit by definition.
	const currentSha256 = await readFileSha256(writer, path);
	const existsOnTrackedBranch = currentSha256 !== null;
	if (existsOnTrackedBranch && currentSha256 === contentSha256) {
		return { state: 'unchanged', storedWorkflowSha256: contentSha256 };
	}
	const handEdited =
		existsOnTrackedBranch && currentSha256 !== input.lastWrittenWorkflowSha256 && currentSha256 !== contentSha256;

	// Step 8 — the removal of a file whose jobs are all gone (T42, FR-70).
	const removal = input.content === '';
	if (removal) {
		if (!existsOnTrackedBranch) return { state: 'unchanged', storedWorkflowSha256: null };
		return pullRequestDelivery(input, writer, path, contentSha256, handEdited, REMOVAL_COPY);
	}

	// Step 7 then step 1 — a Link relation always takes the pull request path, and a
	// protected branch does too; `handEdited` forces it as well (FR-9).
	const verdict: BranchProtectionVerdict =
		createdByAppWork && !handEdited && protection
			? await isBranchProtected(protection, { owner, repo, branch: trackedBranch })
			: { protected: false, decision: 'none' };
	const pullRequestPath = !createdByAppWork || handEdited || verdict.protected;

	if (pullRequestPath) {
		return pullRequestDelivery(input, writer, path, contentSha256, handEdited);
	}
	return directDelivery(input, writer, path, contentSha256, existsOnTrackedBranch);
}

/** Steps 2 + 4 — the direct commit, with the `nonFastForward` retry and the `refRejectedByRule` switch. */
async function directDelivery(
	input: WorkflowWriteInput,
	writer: RepositoryWriter,
	path: string,
	contentSha256: string,
	existsOnTrackedBranch: boolean
): Promise<WorkflowWriteResult> {
	const { trackedBranch } = input.repository;
	const message = existsOnTrackedBranch ? WORKFLOW_COMMIT_MESSAGE_UPDATE : WORKFLOW_COMMIT_MESSAGE_ADD;
	let attempts = 0;

	while (attempts < WORKFLOW_WRITE_MAX_ATTEMPTS) {
		attempts += 1;
		// Step 1 again on every attempt: a fresh head is the whole point of retrying.
		const baseSha = input.resolveTrackedHead
			? await input.resolveTrackedHead()
			: await readBranchHead(writer, trackedBranch);
		const commit: RepositoryCommitInput = {
			branch: trackedBranch,
			baseSha,
			message,
			files: [commitFile(path, input.content)]
		};
		try {
			const { commitSha } = await writer.commitFiles(commit);
			const readBack = await readBackMatches(writer, path, commitSha, contentSha256);
			if (!readBack) return workflowWriteFailed('readBackMismatch');
			return { state: 'committed', commitSha, storedWorkflowSha256: contentSha256 };
		} catch (error) {
			const code = repositoryWriteErrorCode(error);
			// A rule we could not see: switch once to the pull request path, never loop.
			if (code === 'refRejectedByRule') {
				return pullRequestDelivery(input, writer, path, contentSha256, false);
			}
			if (code === 'nonFastForward' && attempts < WORKFLOW_WRITE_MAX_ATTEMPTS) continue;
			if (code === 'nonFastForward') return workflowWriteFailed('nonFastForward');
			throw error;
		}
	}

	return workflowWriteFailed('nonFastForward');
}

/** Steps 3 + 4 — one reused pull request on `ever-works/build-workflow`. */
async function pullRequestDelivery(
	input: WorkflowWriteInput,
	writer: RepositoryWriter,
	path: string,
	contentSha256: string,
	handEdited: boolean,
	copy: DeliveryCopy = DELIVERY_COPY
): Promise<WorkflowWriteResult> {
	const { trackedBranch } = input.repository;

	try {
		const branch = await writer.createBranch(APP_BUILD_WORKFLOW_BRANCH, trackedBranch);
		// Only commit when the branch does not already carry these bytes: a second or
		// third preparation with unchanged content leaves one open pull request and
		// adds no commit (ACC-05-02).
		const branchSha256 = await readFileSha256(writer, path, branch.name);
		if (branchSha256 !== contentSha256) {
			const { commitSha } = await writer.commitFiles({
				branch: branch.name,
				baseSha: branch.commit,
				message: copy.commitMessage,
				files: [commitFile(path, input.content)]
			});
			const readBack = await readBackMatches(writer, path, commitSha, contentSha256);
			if (!readBack) return workflowWriteFailed('readBackMismatch');
		}

		// Always ask: only GitHub knows whether a pull request for this head is still
		// open. A stored number the owner closed would otherwise be "updated" forever.
		try {
			const pullRequest = await writer.createPullRequest({
				title: copy.title,
				head: APP_BUILD_WORKFLOW_BRANCH,
				base: trackedBranch,
				body: copy.body
			});
			return {
				state: handEdited ? 'editedByHand' : 'pullRequestOpened',
				pullRequestNumber: pullRequest.number,
				pullRequestUrl: pullRequest.url,
				storedWorkflowSha256: null
			};
		} catch (error) {
			// Anything else — including another 422 — goes to the outer mapping below.
			if (!isPullRequestAlreadyExistsError(error)) throw error;
			// The open pull request now carries the commit above: reuse it (ACC-05-02),
			// echoing the recorded number and link when there are any.
			return {
				state: handEdited ? 'editedByHand' : 'pullRequestUpdated',
				...(input.pullRequestNumber != null ? { pullRequestNumber: input.pullRequestNumber } : {}),
				...(input.pullRequestUrl ? { pullRequestUrl: input.pullRequestUrl } : {}),
				storedWorkflowSha256: null
			};
		}
	} catch (error) {
		// A refusal on the pull request path is terminal: `workflowWriteFailed` with
		// the branch-rules cause, and never a second branch or a second pull request.
		if (repositoryWriteErrorCode(error) === 'refRejectedByRule') return workflowWriteFailed('branchRules');
		throw error;
	}
}

/** Step 4 — read the file back at the new commit and compare; one retry, then a refusal (FR-8). */
async function readBackMatches(
	writer: RepositoryWriter,
	path: string,
	commitSha: string,
	contentSha256: string
): Promise<boolean> {
	for (let attempt = 0; attempt < WORKFLOW_READ_BACK_ATTEMPTS; attempt += 1) {
		if ((await readFileSha256(writer, path, commitSha)) === contentSha256) return true;
	}
	return false;
}

/** The terminal refusal of a delivery that could not be proven — never a stored hash. */
function workflowWriteFailed(cause: string): WorkflowWriteResult {
	return {
		state: 'blocked',
		storedWorkflowSha256: null,
		blocked: { reason: 'workflowWriteFailed', detail: { cause } }
	};
}
