import { APP_BUILD_WORKFLOW_BRANCH, APP_BUILD_WORKFLOW_PATH, sha256Hex } from '@ever-works/contracts';
import type { RepositoryCommitInput, RepositoryWriteErrorCode, RepositoryWriter } from '@ever-works/plugin';

import { isBranchProtected, type BranchProtectionPort, type BranchProtectionVerdict } from './branch-protection.js';

/**
 * APW-05 T9 — delivering the generated workflow (plan §4.6, `APW05-G16`, R-4).
 *
 * ## The one rule that shapes everything here
 *
 * **The plugin never clones.** Every write goes through the `RepositoryWriter` the
 * facade binds (APW-03's `commitFiles?` via `GitFacadeService`), whose four members
 * are all this file calls: `getFileContent`, `commitFiles`, `createBranch`,
 * `createPullRequest`. Writing one file must not clone a 1 GB repository
 * (plan §1.2), and the T9 spec asserts that no clone-shaped call exists — the fake
 * writer has no clone member to call.
 *
 * ## The paths, and which one a branch gets
 *
 * | Branch state                                                  | Path                                     |
 * | ------------------------------------------------------------- | ---------------------------------------- |
 * | File on the tracked branch already equals the generated bytes  | `unchanged`, **zero write calls**        |
 * | File exists, its sha256 is neither the stored one nor the new one | **hand edit** → pull request, never an overwrite on the tracked branch (FR-9) |
 * | `createdByAppWork === false` (a Link relation)                 | pull request, always (R-4)               |
 * | Protected (reviews, status checks, ruleset, or a 403)          | pull request                             |
 * | Otherwise                                                      | direct commit onto the tracked branch    |
 *
 * The pull request path reuses **one** pull request: `ever-works/build-workflow` is
 * created from the tracked head when absent, the commit lands on it, and a stored
 * `pullRequestNumber` means the open pull request is updated rather than a second
 * one opened (ACC-05-02). A second and a third preparation therefore leave exactly
 * one open pull request, and a preparation whose bytes are already on that branch
 * commits nothing at all.
 *
 * ## The refusals
 *
 *   - `nonFastForward` — a race: retry the direct write, at most
 *     {@link WORKFLOW_WRITE_MAX_ATTEMPTS} attempts in total (plan §4.6 step 2's
 *     "up to 3 times"), then `blocked workflowWriteFailed`.
 *   - `refRejectedByRule` — a protection or ruleset the pre-check could not see:
 *     switch to the pull request path **once** and never retry the direct write.
 *     If the pull request path is refused the same way, stop with
 *     `blocked workflowWriteFailed`, detail `{ cause: 'branchRules' }` — never a
 *     loop. Its copy is "The build workflow could not be written." plus "A rule on
 *     this repository refuses the change." (plan §4.6 steps 2–3).
 *   - a read-back that does not match: retried **once**; still mismatched →
 *     `blocked workflowWriteFailed`, and `storedWorkflowSha256` stays untouched —
 *     only a matching read-back may store a hash (FR-8).
 *
 * ## Where the branch head comes from
 *
 * `commitFiles` needs the commit the caller believes the branch is at, and the
 * `RepositoryWriter` contract has no `getBranch` member. Two ways in, both within
 * the four:
 *
 *   1. `input.resolveTrackedHead` — the facade, which already holds
 *      `GitFacadeService`, passes the real head (T16's binding);
 *   2. otherwise {@link readBranchHead} calls `createBranch(branch, branch)`, which
 *      the contract documents as returning an existing branch rather than
 *      recreating it — a read that happens to be spelled as a create.
 *
 * The head is re-read on **every** attempt, which is what makes the
 * `nonFastForward` retry real rather than a repeat of the same stale commit.
 */

/** The commit message of a file that did not exist (plan §4.6 step 2). */
export const WORKFLOW_COMMIT_MESSAGE_ADD = 'Add Ever Works build workflow';

/** The commit message of a file the platform is changing (plan §4.6 step 2). */
export const WORKFLOW_COMMIT_MESSAGE_UPDATE = 'Update Ever Works build workflow';

/** The pull request title (plan §4.6 step 3). */
export const WORKFLOW_PULL_REQUEST_TITLE = 'Add Ever Works build workflow';

/** The pull request body — what a reviewer is looking at, and what not to do with it. */
export const WORKFLOW_PULL_REQUEST_BODY =
	'Ever Works generated this workflow from the App spec. It builds the image for this App Work on GitHub-hosted runners and publishes it to GHCR. Hand edits to this file are never overwritten: Ever Works proposes its changes as pull requests.';

/**
 * How many direct-write attempts are made in total (plan §4.6 step 2: "A
 * `nonFastForward` error retries from step 1 up to 3 times").
 *
 * Read as at most three attempts, which is the stricter of the two readings of
 * "up to 3 times" and therefore cannot exceed the bound the plan states.
 */
export const WORKFLOW_WRITE_MAX_ATTEMPTS = 3;

/** How many read-backs one successful write gets: the first, plus the plan's single retry (FR-8). */
export const WORKFLOW_READ_BACK_ATTEMPTS = 2;

/** The tracked branch and the App Work's relation to it. */
export interface WorkflowRepositoryCoordinates {
	readonly owner: string;
	readonly repo: string;
	readonly trackedBranch: string;
	/** `false` for a Link relation — that repository is not ours to write into (R-4). */
	readonly createdByAppWork: boolean;
}

/** What the caller asks to deliver, and what it remembers from the last delivery. */
export interface WorkflowWriteInput {
	readonly repository: WorkflowRepositoryCoordinates;
	/** The generated bytes. */
	readonly content: string;
	/** The workflow sha256 the platform last wrote, or `null` — the other half of hand-edit detection (FR-9). */
	readonly lastWrittenWorkflowSha256: string | null;
	/** The pull request the platform already has open for this App Work, when there is one. */
	readonly pullRequestNumber?: number | null;
	/** That pull request's URL, echoed back on the reuse path (the writer never re-reads it). */
	readonly pullRequestUrl?: string | null;
	/** Overrides {@link APP_BUILD_WORKFLOW_PATH}; exists so a spec can name its own path. */
	readonly workflowPath?: string;
	/** The facade's branch-head read (T16). Without it, {@link readBranchHead} is used. */
	readonly resolveTrackedHead?: () => Promise<string>;
}

/** What the delivery decided — the transport state §3.1b maps onto `workflowState`. */
export interface WorkflowWriteResult {
	/**
	 * The delivery outcome.
	 *
	 * `'blocked'` is this writer's own terminal state and is **not** a member of
	 * `PrepareRepositoryResult.workflow.state` (which has five): the caller maps it
	 * onto `PrepareRepositoryResult.blocked` with reason `workflowWriteFailed`, and
	 * must not pass it through as a stored workflow state.
	 */
	readonly state: 'unchanged' | 'committed' | 'pullRequestOpened' | 'pullRequestUpdated' | 'editedByHand' | 'blocked';
	readonly commitSha?: string;
	readonly pullRequestNumber?: number;
	readonly pullRequestUrl?: string;
	/**
	 * The sha256 the platform may store as `lastWrittenWorkflowSha256`, or `null`
	 * when nothing on the tracked branch has been proven to equal the generated
	 * bytes. Only a matching read-back sets it (FR-8, plan §4.6 step 4).
	 */
	readonly storedWorkflowSha256: string | null;
	readonly blocked?: { readonly reason: 'workflowWriteFailed'; readonly detail: { readonly cause: string } };
}

/** A file as the writer reads it back — `encoding` decides whether the content needs decoding. */
interface ReadFile {
	readonly content: string;
	readonly encoding: string;
}

/** Decode a `getFileContent` answer to text — GitHub's contents API answers base64. */
function decodeFileContent(file: ReadFile): string {
	return file.encoding === 'base64' ? Buffer.from(file.content, 'base64').toString('utf-8') : file.content;
}

/** `null` when the file does not exist; otherwise its sha256 as text (plan §4.6 steps 4–5). */
async function readFileSha256(writer: RepositoryWriter, path: string, ref?: string): Promise<string | null> {
	const file = await writer.getFileContent(path, ref);
	if (!file) return null;
	return sha256Hex(decodeFileContent(file as ReadFile));
}

/**
 * The tracked branch's head commit.
 *
 * `createBranch(branch, branch)` is the contract's documented "an existing branch
 * is returned rather than recreated" path; a caller with a real head read passes
 * `input.resolveTrackedHead` instead.
 */
async function readBranchHead(writer: RepositoryWriter, branch: string): Promise<string> {
	const existing = await writer.createBranch(branch, branch);
	return existing.commit;
}

/** The refusal code of a thrown write error, if it is one of the two the contract names. */
export function repositoryWriteErrorCode(error: unknown): RepositoryWriteErrorCode | null {
	const candidate = error as { code?: unknown; reason?: unknown } | null | undefined;
	for (const value of [candidate?.code, candidate?.reason]) {
		if (value === 'nonFastForward' || value === 'refRejectedByRule') return value;
	}
	return null;
}

/** One file, ready for {@link RepositoryWriter.commitFiles}. */
function commitFile(path: string, content: string) {
	return { path, content, encoding: 'utf-8' as const };
}

/**
 * Deliver the generated workflow (plan §4.6).
 *
 * `protection` is the branch-rules port; leave it out when the caller has no
 * protection read (a fork the platform owns, a spec), in which case only
 * `createdByAppWork` and hand-edit detection decide the path.
 */
export async function writeWorkflow(
	input: WorkflowWriteInput,
	writer: RepositoryWriter,
	protection?: BranchProtectionPort
): Promise<WorkflowWriteResult> {
	const path = input.workflowPath ?? APP_BUILD_WORKFLOW_PATH;
	const { owner, repo, trackedBranch, createdByAppWork } = input.repository;
	const contentSha256 = sha256Hex(input.content);

	// Step 5 — hand-edit detection, before any write. `lastWritten` null with a file
	// present means the platform never wrote it: a hand edit by definition.
	const currentSha256 = await readFileSha256(writer, path);
	const existsOnTrackedBranch = currentSha256 !== null;
	if (existsOnTrackedBranch && currentSha256 === contentSha256) {
		return { state: 'unchanged', storedWorkflowSha256: contentSha256 };
	}
	const handEdited =
		existsOnTrackedBranch && currentSha256 !== input.lastWrittenWorkflowSha256 && currentSha256 !== contentSha256;

	// Step 7 then step 1 — a Link relation always takes the pull request path, and a
	// protected branch does too; `handEdited` forces it as well (FR-9).
	const verdict: BranchProtectionVerdict =
		createdByAppWork && !handEdited && protection
			? await isBranchProtected(protection, { owner, repo, branch: trackedBranch })
			: { protected: false, decision: 'none' };
	const pullRequestPath = !createdByAppWork || handEdited || verdict.protected;

	if (pullRequestPath) {
		return pullRequestDelivery(input, writer, path, contentSha256, handEdited);
	}
	return directDelivery(input, writer, path, contentSha256, existsOnTrackedBranch);
}

/** Steps 2 + 4 — the direct commit, with the `nonFastForward` retry and the `refRejectedByRule` switch. */
async function directDelivery(
	input: WorkflowWriteInput,
	writer: RepositoryWriter,
	path: string,
	contentSha256: string,
	existsOnTrackedBranch: boolean
): Promise<WorkflowWriteResult> {
	const { trackedBranch } = input.repository;
	const message = existsOnTrackedBranch ? WORKFLOW_COMMIT_MESSAGE_UPDATE : WORKFLOW_COMMIT_MESSAGE_ADD;
	let attempts = 0;

	while (attempts < WORKFLOW_WRITE_MAX_ATTEMPTS) {
		attempts += 1;
		// Step 1 again on every attempt: a fresh head is the whole point of retrying.
		const baseSha = input.resolveTrackedHead
			? await input.resolveTrackedHead()
			: await readBranchHead(writer, trackedBranch);
		const commit: RepositoryCommitInput = {
			branch: trackedBranch,
			baseSha,
			message,
			files: [commitFile(path, input.content)]
		};
		try {
			const { commitSha } = await writer.commitFiles(commit);
			const readBack = await readBackMatches(writer, path, commitSha, contentSha256);
			if (!readBack) return workflowWriteFailed('readBackMismatch');
			return { state: 'committed', commitSha, storedWorkflowSha256: contentSha256 };
		} catch (error) {
			const code = repositoryWriteErrorCode(error);
			// A rule we could not see: switch once to the pull request path, never loop.
			if (code === 'refRejectedByRule') {
				return pullRequestDelivery(input, writer, path, contentSha256, false);
			}
			if (code === 'nonFastForward' && attempts < WORKFLOW_WRITE_MAX_ATTEMPTS) continue;
			if (code === 'nonFastForward') return workflowWriteFailed('nonFastForward');
			throw error;
		}
	}

	return workflowWriteFailed('nonFastForward');
}

/** Steps 3 + 4 — one reused pull request on `ever-works/build-workflow`. */
async function pullRequestDelivery(
	input: WorkflowWriteInput,
	writer: RepositoryWriter,
	path: string,
	contentSha256: string,
	handEdited: boolean
): Promise<WorkflowWriteResult> {
	const { trackedBranch } = input.repository;
	const reusedNumber = input.pullRequestNumber ?? null;

	try {
		const branch = await writer.createBranch(APP_BUILD_WORKFLOW_BRANCH, trackedBranch);
		// Only commit when the branch does not already carry these bytes: a second or
		// third preparation with unchanged content leaves one open pull request and
		// adds no commit (ACC-05-02).
		const branchSha256 = await readFileSha256(writer, path, branch.name);
		if (branchSha256 !== contentSha256) {
			const { commitSha } = await writer.commitFiles({
				branch: branch.name,
				baseSha: branch.commit,
				message: WORKFLOW_COMMIT_MESSAGE_UPDATE,
				files: [commitFile(path, input.content)]
			});
			const readBack = await readBackMatches(writer, path, commitSha, contentSha256);
			if (!readBack) return workflowWriteFailed('readBackMismatch');
		}

		if (reusedNumber !== null) {
			return {
				state: handEdited ? 'editedByHand' : 'pullRequestUpdated',
				pullRequestNumber: reusedNumber,
				...(input.pullRequestUrl ? { pullRequestUrl: input.pullRequestUrl } : {}),
				storedWorkflowSha256: null
			};
		}

		const pullRequest = await writer.createPullRequest({
			title: WORKFLOW_PULL_REQUEST_TITLE,
			head: APP_BUILD_WORKFLOW_BRANCH,
			base: trackedBranch,
			body: WORKFLOW_PULL_REQUEST_BODY
		});
		return {
			state: handEdited ? 'editedByHand' : 'pullRequestOpened',
			pullRequestNumber: pullRequest.number,
			pullRequestUrl: pullRequest.url,
			storedWorkflowSha256: null
		};
	} catch (error) {
		// A refusal on the pull request path is terminal: `workflowWriteFailed` with
		// the branch-rules cause, and never a second branch or a second pull request.
		if (repositoryWriteErrorCode(error) === 'refRejectedByRule') return workflowWriteFailed('branchRules');
		throw error;
	}
}

/** Step 4 — read the file back at the new commit and compare; one retry, then a refusal (FR-8). */
async function readBackMatches(
	writer: RepositoryWriter,
	path: string,
	commitSha: string,
	contentSha256: string
): Promise<boolean> {
	for (let attempt = 0; attempt < WORKFLOW_READ_BACK_ATTEMPTS; attempt += 1) {
		if ((await readFileSha256(writer, path, commitSha)) === contentSha256) return true;
	}
	return false;
}

/** The terminal refusal of a delivery that could not be proven — never a stored hash. */
function workflowWriteFailed(cause: string): WorkflowWriteResult {
	return {
		state: 'blocked',
		storedWorkflowSha256: null,
		blocked: { reason: 'workflowWriteFailed', detail: { cause } }
	};
}
