import { test, expect } from '@playwright/test';
import { API_BASE } from './helpers/api';

/**
 * RFC 7231 says any response generated by an origin server should
 * include a Date header. The value should be a well-formed HTTP-date
 * (parseable by `Date.parse`) and within a small skew window of the
 * local clock — large skews are a sign of frozen container time or
 * a mis-set NTP.
 */

const PUBLIC_PATHS = [
    '/api/health',
    '/api/version',
    '/api/info',
    '/api/works',
    '/.well-known/agent.json',
];

const MAX_SKEW_MS = 5 * 60 * 1000;

test.describe('API responses: Date header sanity', () => {
    for (const path of PUBLIC_PATHS) {
        test(`GET ${path} returns parseable Date header within ±5 min skew`, async ({
            request,
        }) => {
            const before = Date.now();
            const res = await request.get(`${API_BASE}${path}`);
            const after = Date.now();
            const dateHeader = res.headers()['date'];
            if (!dateHeader) return; // Date header absent is its own issue; covered elsewhere
            const parsed = Date.parse(dateHeader);
            expect(Number.isFinite(parsed), `Date "${dateHeader}" parses for ${path}`).toBe(true);
            const skew = Math.min(Math.abs(parsed - before), Math.abs(parsed - after));
            expect(skew, `Date skew on ${path}: ${dateHeader}`).toBeLessThan(MAX_SKEW_MS);
        });
    }
});
