import { test, expect } from '@playwright/test';
import { loadSeededTestUser } from './helpers/seeded-test-user';
import { createWorkViaAPI, loginViaAPI } from './helpers/api';
import { seedKbBinaryDoc } from './helpers/kb-fixtures';

/**
 * EW-641 Phase 1B/d row 21c — A14 acceptance e2e (viewer size caps).
 *
 * Drives the per-MIME viewer dispatcher (row 21b) end-to-end:
 *
 *  A14.1 — PDF under the 30 MiB inline cap: seed a tiny valid PDF byte
 *    stub via the public upload endpoint, navigate to the per-doc
 *    editor route, assert that `KbPdfViewer` mounts in `data-mode="inline"`
 *    (the lazy-loaded iframe canvas — we only check the dispatcher's
 *    outer-container state, not the PDF.js render, so this stays fast
 *    and stable on CI).
 *
 *  A14.2 — XLSX over the 5 MiB inline cap: seed a 6 MiB zero-filled
 *    buffer (passes the upload endpoint's 200 MiB cap, fails the
 *    KbXlsxViewer's 5 MiB viewer-side threshold), navigate, assert
 *    that `KbXlsxViewer` mounts in `data-mode="download"` AND the
 *    `kb-xlsx-download-fallback` card is visible.
 *
 * The viewer dispatcher lives in
 * `apps/web/src/app/[locale]/(dashboard)/works/[id]/kb/[...path]/page.tsx`
 * — it fetches the source upload row when `doc.sourceUploadId` is set,
 * runs `pickKbViewer(upload.mimeType)`, and dispatches to the matching
 * `Kb{Pdf,Xlsx,Docx,Image,Video,Audio}Viewer`. URL points at the
 * row-21a download proxy (`/api/works/:id/kb/uploads/:uploadId/download`).
 *
 * Lives in `apps/web/e2e/` so the existing `e2e.yml` workflow picks it
 * up on push to develop / stage / main. Authenticated by the shared
 * `storageState` from `global-setup.ts` (the chromium project's
 * `testIgnore` regex does not enumerate `kb-*`).
 */

const PDF_MIME = 'application/pdf';
const XLSX_MIME = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

/**
 * Build a minimal-but-valid PDF with one page that draws several lines of
 * "Hello, World!" via a Type1 Helvetica font. The agent's pdf-parse
 * extractor (an old pdfjs fork) needs BOTH (a) a parseable `/Catalog` +
 * `/Pages` tree AND (b) at least one page that yields > 0 chars of text
 * — otherwise the extractor reports `"KB PDF extraction produced no
 * text — likely an image-only PDF; OCR is Phase 3"` and marks the
 * upload row failed.
 *
 * Earlier string-based attempts failed non-deterministically inside
 * pdf-parse ("Command token too long: 128" / "bad XRef entry") because:
 *  1. No `%binary-marker` line after `%PDF-1.4` → text-aware tools
 *     could normalize CR/LF and shift byte offsets relative to the
 *     xref table.
 *  2. String concatenation + utf8 encoding meant byte offsets were
 *     computed from UTF-16 string `.length` rather than emitted bytes.
 *  3. Single-line content stream put pdfjs's token scanner past its
 *     128-char overflow guard with no delimiter.
 *
 * This rebuild assembles everything as `Buffer`s, computes xref offsets
 * from real byte lengths, embeds the canonical `% â ã Ï Ó` binary
 * marker, and emits the content stream with one operator per line.
 */
function makeMinimalValidPdf(): Buffer {
    // Multi-line content stream, one PDF operator per line. Drawing
    // three distinct text lines so pdf-parse extracts > 0 chars even
    // if its font-metric handling collapses repeated literals.
    const streamData = Buffer.from(
        [
            'BT',
            '/F1 24 Tf',
            '50 720 Td',
            '(Hello, World!) Tj',
            '0 -30 Td',
            '(KB viewer dispatcher test fixture.) Tj',
            '0 -30 Td',
            '(Generated by kb-viewer-size-cap.spec.ts) Tj',
            'ET',
            '',
        ].join('\n'),
        'ascii',
    );

    const objBodies: Buffer[] = [
        Buffer.from('<</Type/Catalog/Pages 2 0 R>>', 'ascii'),
        Buffer.from('<</Type/Pages/Kids[3 0 R]/Count 1>>', 'ascii'),
        Buffer.from(
            '<</Type/Page/Parent 2 0 R/Resources<</Font<</F1 5 0 R>>>>/MediaBox[0 0 612 792]/Contents 4 0 R>>',
            'ascii',
        ),
        Buffer.concat([
            Buffer.from(`<</Length ${streamData.length}>>\nstream\n`, 'ascii'),
            streamData,
            Buffer.from('endstream', 'ascii'),
        ]),
        Buffer.from('<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>', 'ascii'),
    ];

    // PDF spec §7.5.2: a header comment of 4 bytes ≥ 0x80 tells
    // recognizers (and any CR/LF-normalizing transport) to treat the
    // file as binary. The 0xE2 0xE3 0xCF 0xD3 byte sequence is the
    // de-facto convention used by the official Adobe spec sample.
    const header = Buffer.concat([
        Buffer.from('%PDF-1.4\n', 'ascii'),
        Buffer.from([0x25, 0xe2, 0xe3, 0xcf, 0xd3, 0x0a]),
    ]);

    const chunks: Buffer[] = [header];
    let cursor = header.length;
    const offsets: number[] = [];
    for (let i = 0; i < objBodies.length; i++) {
        offsets.push(cursor);
        const prefix = Buffer.from(`${i + 1} 0 obj\n`, 'ascii');
        const suffix = Buffer.from('\nendobj\n', 'ascii');
        const seg = Buffer.concat([prefix, objBodies[i], suffix]);
        chunks.push(seg);
        cursor += seg.length;
    }
    const xrefPos = cursor;

    const pad = (n: number): string => n.toString().padStart(10, '0');
    // Each xref entry is exactly 20 bytes: 10-digit offset + space +
    // 5-digit generation + space + 'n'/'f' + space + LF. pdfjs treats
    // the slot width as load-bearing and bails on the slightest drift.
    const xrefLines: string[] = [
        `xref\n0 ${objBodies.length + 1}\n`,
        '0000000000 65535 f \n',
        ...offsets.map((o) => `${pad(o)} 00000 n \n`),
    ];
    chunks.push(Buffer.from(xrefLines.join(''), 'ascii'));

    chunks.push(
        Buffer.from(
            `trailer<</Size ${objBodies.length + 1}/Root 1 0 R>>\nstartxref\n${xrefPos}\n%%EOF\n`,
            'ascii',
        ),
    );

    return Buffer.concat(chunks);
}

/**
 * Build a real `.xlsx` byte buffer (ZIP-of-XML, exceljs-emitted) padded
 * with incompressible random base64 cells until the file is at least
 * `targetBytes`. The agent's buffer extractor parses every uploaded
 * `application/vnd...sheet` body via `exceljs.xlsx.load()`, so handing
 * it `Buffer.alloc(6 * 1024 * 1024, 0)` produced a "not a zip file"
 * extraction failure that left the upload row with `document: null`.
 *
 * For the A14.2 dispatcher test we just need a workbook that:
 *  - extracts cleanly (so the API returns `{upload, document}`),
 *  - is > KbXlsxViewer's 5 MiB inline cap (so the viewer mounts in
 *    `data-mode="download"`).
 */
async function makeOversizeXlsx(targetBytes: number): Promise<Buffer> {
    // exceljs ships as CJS; under Node ESM `await import('exceljs')`
    // returns `{ default: ExcelJSObject }` and the `.Workbook` constructor
    // lives on the default export — `new ExcelJS.Workbook()` directly on
    // the namespace throws "is not a constructor". The production
    // `load-exceljs-workbook.ts` only works because webpack flattens the
    // interop in the browser bundle; in Playwright (raw Node) we have to
    // unwrap the default ourselves. Fall through to the namespace for
    // ESM-native builds that do not wrap.
    interface ExcelJsCtorHost {
        Workbook: new () => {
            addWorksheet(name: string): {
                getCell(addr: string): { value: string };
            };
            xlsx: { writeBuffer(): Promise<ArrayBuffer> };
        };
    }
    const mod = (await import('exceljs')) as unknown as {
        default?: ExcelJsCtorHost;
    } & ExcelJsCtorHost;
    const ExcelJS: ExcelJsCtorHost = mod.default ?? mod;
    const { randomBytes } = await import('node:crypto');
    const wb = new ExcelJS.Workbook();
    const sheet = wb.addWorksheet('Sheet1');
    // 64 KiB random → ~88 KiB base64 per cell, ZIP-incompressible.
    const CHUNK = 64 * 1024;
    const rowsNeeded = Math.ceil(targetBytes / CHUNK) + 8;
    for (let i = 0; i < rowsNeeded; i++) {
        sheet.getCell(`A${i + 1}`).value = randomBytes(CHUNK).toString('base64');
    }
    return Buffer.from(await wb.xlsx.writeBuffer());
}

test.describe('Knowledge Base — A14 viewer size caps', () => {
    test('PDF under 30 MiB renders inline via KbPdfViewer', async ({ page, request }) => {
        test.setTimeout(180_000);

        const testUser = loadSeededTestUser();
        const { access_token } = await loginViaAPI(request, {
            email: testUser.email,
            password: testUser.password,
        });

        const runId = `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
        const { id: workId } = await createWorkViaAPI(request, access_token, {
            name: `KB PDF inline ${runId}`,
        });
        expect(workId, 'createWorkViaAPI must return a non-empty work id').toBeTruthy();

        const { path: docPath } = await seedKbBinaryDoc(request, access_token, workId, {
            filename: `kb-a14-pdf-${runId}.pdf`,
            mimeType: PDF_MIME,
            body: makeMinimalValidPdf(),
        });
        // The server stores every extracted upload at `${class}/${slug}.md`
        // (knowledge-base.service.ts ≈ line 1496); the original `.pdf`
        // extension is dropped during extraction. The viewer dispatcher
        // then picks `KbPdfViewer` from `upload.mimeType`, NOT from the
        // document path, so any matching slug+class is fine here.
        expect(docPath).toMatch(/^freeform\/kb-a14-pdf-.*\.md$/);

        await page.goto(`/en/works/${workId}/kb/${docPath}`, { waitUntil: 'domcontentloaded' });

        const pdfViewer = page.locator('[data-testid="kb-pdf-viewer"]');
        await expect(pdfViewer).toBeVisible({ timeout: 60_000 });
        await expect(pdfViewer).toHaveAttribute('data-mode', 'inline');
        // Confirm the download fallback did NOT render — the viewer's
        // inline branch chose KbPdfViewerCanvas (next/dynamic), not the
        // download-fallback card.
        await expect(page.locator('[data-testid="kb-pdf-download-fallback"]')).toHaveCount(0);
    });

    test('XLSX over 5 MiB shows download fallback via KbXlsxViewer', async ({ page, request }) => {
        test.setTimeout(180_000);

        const testUser = loadSeededTestUser();
        const { access_token } = await loginViaAPI(request, {
            email: testUser.email,
            password: testUser.password,
        });

        const runId = `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
        const { id: workId } = await createWorkViaAPI(request, access_token, {
            name: `KB XLSX over-cap ${runId}`,
        });
        expect(workId).toBeTruthy();

        // Real exceljs-emitted workbook padded with random base64 cells
        // to ~6 MiB. Has to be a valid XLSX so the agent's buffer
        // extractor (`exceljs.xlsx.load()`) doesn't reject the upload —
        // a zero-filled buffer used to fail extraction with "not a zip
        // file" and leave the upload row with `document: null`. The
        // viewer dispatcher then decides on `fileSize` AFTER the row
        // exists, so a slightly oversized real workbook is the cleanest
        // way to drive the > 5 MiB download-fallback branch.
        const xlsxBuffer = await makeOversizeXlsx(6 * 1024 * 1024);
        const { path: docPath } = await seedKbBinaryDoc(request, access_token, workId, {
            filename: `kb-a14-xlsx-${runId}.xlsx`,
            mimeType: XLSX_MIME,
            body: xlsxBuffer,
        });
        // Same `.md` rewrite as the PDF case — viewer dispatch reads
        // `upload.mimeType`, not the doc path extension.
        expect(docPath).toMatch(/^freeform\/kb-a14-xlsx-.*\.md$/);

        await page.goto(`/en/works/${workId}/kb/${docPath}`, { waitUntil: 'domcontentloaded' });

        const xlsxViewer = page.locator('[data-testid="kb-xlsx-viewer"]');
        await expect(xlsxViewer).toBeVisible({ timeout: 60_000 });
        await expect(xlsxViewer).toHaveAttribute('data-mode', 'download');
        await expect(page.locator('[data-testid="kb-xlsx-download-fallback"]')).toBeVisible({
            timeout: 10_000,
        });
        // The download anchor's href must point at the row-21a download
        // proxy so the operator's click streams the bytes back through
        // the same CSP+nosniff-pinned route.
        const downloadLink = page.locator('[data-testid="kb-xlsx-download-link"]');
        await expect(downloadLink).toBeVisible();
        await expect(downloadLink).toHaveAttribute(
            'href',
            new RegExp(`/api/works/${workId}/kb/uploads/[^/]+/download$`),
        );
    });
});
