import { test, expect } from '@playwright/test';
import { loadSeededTestUser } from './helpers/seeded-test-user';
import { createWorkViaAPI, loginViaAPI } from './helpers/api';
import { seedKbBinaryDoc } from './helpers/kb-fixtures';

/**
 * EW-641 Phase 1B/d row 21c — A14 acceptance e2e (viewer size caps).
 *
 * Drives the per-MIME viewer dispatcher (row 21b) end-to-end:
 *
 *  A14.1 — PDF under the 30 MiB inline cap: seed a tiny valid PDF byte
 *    stub via the public upload endpoint, navigate to the per-doc
 *    editor route, assert that `KbPdfViewer` mounts in `data-mode="inline"`
 *    (the lazy-loaded iframe canvas — we only check the dispatcher's
 *    outer-container state, not the PDF.js render, so this stays fast
 *    and stable on CI).
 *
 *  A14.2 — XLSX over the 5 MiB inline cap: seed a 6 MiB zero-filled
 *    buffer (passes the upload endpoint's 200 MiB cap, fails the
 *    KbXlsxViewer's 5 MiB viewer-side threshold), navigate, assert
 *    that `KbXlsxViewer` mounts in `data-mode="download"` AND the
 *    `kb-xlsx-download-fallback` card is visible.
 *
 * The viewer dispatcher lives in
 * `apps/web/src/app/[locale]/(dashboard)/works/[id]/kb/[...path]/page.tsx`
 * — it fetches the source upload row when `doc.sourceUploadId` is set,
 * runs `pickKbViewer(upload.mimeType)`, and dispatches to the matching
 * `Kb{Pdf,Xlsx,Docx,Image,Video,Audio}Viewer`. URL points at the
 * row-21a download proxy (`/api/works/:id/kb/uploads/:uploadId/download`).
 *
 * Lives in `apps/web/e2e/` so the existing `e2e.yml` workflow picks it
 * up on push to develop / stage / main. Authenticated by the shared
 * `storageState` from `global-setup.ts` (the chromium project's
 * `testIgnore` regex does not enumerate `kb-*`).
 */

const PDF_MIME = 'application/pdf';
const XLSX_MIME = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

/**
 * Build a minimal-but-valid PDF with one page that draws a few lines of
 * text via the standard Helvetica font, using `pdf-lib`. The agent's
 * pdf-parse extractor (an old pdfjs fork) needs BOTH (a) a parseable
 * `/Catalog` + `/Pages` tree AND (b) at least one page that yields > 0
 * chars of text — otherwise the extractor reports `"KB PDF extraction
 * produced no text — likely an image-only PDF; OCR is Phase 3"` and
 * marks the upload row failed.
 *
 * Earlier hand-rolled attempts (commits 32df2af6, 21680fa5, 5f555b85)
 * failed inside pdf-parse with various permutations of "Command token
 * too long: 128" and "bad XRef entry" even with the binary marker and
 * byte-perfect xref offsets. pdfjs's tolerance for terse-but-valid
 * PDFs is essentially zero. Using `pdf-lib` shifts the byte-layout
 * correctness burden to a battle-tested PDF library; it's already a
 * tiny pure-JS dependency with no native bindings.
 *
 * We're only asserting on the viewer dispatcher's `data-mode`
 * attribute, not on the actual rendered content, so a one-page PDF
 * with three Helvetica text lines is plenty.
 */
async function makeMinimalValidPdf(): Promise<Buffer> {
    const { PDFDocument, StandardFonts } = await import('pdf-lib');
    const pdfDoc = await PDFDocument.create();
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const page = pdfDoc.addPage([612, 792]);
    page.drawText('Hello, World!', { x: 50, y: 720, size: 24, font });
    page.drawText('KB viewer dispatcher test fixture.', {
        x: 50,
        y: 690,
        size: 16,
        font,
    });
    page.drawText('Generated by kb-viewer-size-cap.spec.ts', {
        x: 50,
        y: 660,
        size: 16,
        font,
    });
    return Buffer.from(await pdfDoc.save());
}

/**
 * Build a real `.xlsx` byte buffer (ZIP-of-XML, exceljs-emitted) padded
 * with incompressible random base64 cells until the file is at least
 * `targetBytes`. The agent's buffer extractor parses every uploaded
 * `application/vnd...sheet` body via `exceljs.xlsx.load()`, so handing
 * it `Buffer.alloc(6 * 1024 * 1024, 0)` produced a "not a zip file"
 * extraction failure that left the upload row with `document: null`.
 *
 * For the A14.2 dispatcher test we just need a workbook that:
 *  - extracts cleanly (so the API returns `{upload, document}`),
 *  - is > KbXlsxViewer's 5 MiB inline cap (so the viewer mounts in
 *    `data-mode="download"`).
 */
async function makeOversizeXlsx(targetBytes: number): Promise<Buffer> {
    // exceljs ships as CJS; under Node ESM `await import('exceljs')`
    // returns `{ default: ExcelJSObject }` and the `.Workbook` constructor
    // lives on the default export — `new ExcelJS.Workbook()` directly on
    // the namespace throws "is not a constructor". The production
    // `load-exceljs-workbook.ts` only works because webpack flattens the
    // interop in the browser bundle; in Playwright (raw Node) we have to
    // unwrap the default ourselves. Fall through to the namespace for
    // ESM-native builds that do not wrap.
    interface ExcelJsCtorHost {
        Workbook: new () => {
            addWorksheet(name: string): {
                getCell(addr: string): { value: string };
            };
            xlsx: { writeBuffer(): Promise<ArrayBuffer> };
        };
    }
    const mod = (await import('exceljs')) as unknown as {
        default?: ExcelJsCtorHost;
    } & ExcelJsCtorHost;
    const ExcelJS: ExcelJsCtorHost = mod.default ?? mod;
    const { randomBytes } = await import('node:crypto');
    const wb = new ExcelJS.Workbook();
    const sheet = wb.addWorksheet('Sheet1');
    // 64 KiB random → ~88 KiB base64 per cell, ZIP-incompressible.
    const CHUNK = 64 * 1024;
    const rowsNeeded = Math.ceil(targetBytes / CHUNK) + 8;
    for (let i = 0; i < rowsNeeded; i++) {
        sheet.getCell(`A${i + 1}`).value = randomBytes(CHUNK).toString('base64');
    }
    return Buffer.from(await wb.xlsx.writeBuffer());
}

test.describe('Knowledge Base — A14 viewer size caps', () => {
    test('PDF under 30 MiB renders inline via KbPdfViewer', async ({ page, request }) => {
        test.setTimeout(180_000);

        const testUser = loadSeededTestUser();
        const { access_token } = await loginViaAPI(request, {
            email: testUser.email,
            password: testUser.password,
        });

        const runId = `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
        const { id: workId } = await createWorkViaAPI(request, access_token, {
            name: `KB PDF inline ${runId}`,
        });
        expect(workId, 'createWorkViaAPI must return a non-empty work id').toBeTruthy();

        const { path: docPath } = await seedKbBinaryDoc(request, access_token, workId, {
            filename: `kb-a14-pdf-${runId}.pdf`,
            mimeType: PDF_MIME,
            body: await makeMinimalValidPdf(),
        });
        // The server stores every extracted upload at `${class}/${slug}.md`
        // (knowledge-base.service.ts ≈ line 1496); the original `.pdf`
        // extension is dropped during extraction. The viewer dispatcher
        // then picks `KbPdfViewer` from `upload.mimeType`, NOT from the
        // document path, so any matching slug+class is fine here.
        expect(docPath).toMatch(/^freeform\/kb-a14-pdf-.*\.md$/);

        await page.goto(`/en/works/${workId}/kb/${docPath}`, { waitUntil: 'domcontentloaded' });

        const pdfViewer = page.locator('[data-testid="kb-pdf-viewer"]');
        await expect(pdfViewer).toBeVisible({ timeout: 60_000 });
        await expect(pdfViewer).toHaveAttribute('data-mode', 'inline');
        // Confirm the download fallback did NOT render — the viewer's
        // inline branch chose KbPdfViewerCanvas (next/dynamic), not the
        // download-fallback card.
        await expect(page.locator('[data-testid="kb-pdf-download-fallback"]')).toHaveCount(0);
    });

    test('XLSX over 5 MiB shows download fallback via KbXlsxViewer', async ({ page, request }) => {
        test.setTimeout(180_000);

        const testUser = loadSeededTestUser();
        const { access_token } = await loginViaAPI(request, {
            email: testUser.email,
            password: testUser.password,
        });

        const runId = `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
        const { id: workId } = await createWorkViaAPI(request, access_token, {
            name: `KB XLSX over-cap ${runId}`,
        });
        expect(workId).toBeTruthy();

        // Real exceljs-emitted workbook padded with random base64 cells
        // to ~6 MiB. Has to be a valid XLSX so the agent's buffer
        // extractor (`exceljs.xlsx.load()`) doesn't reject the upload —
        // a zero-filled buffer used to fail extraction with "not a zip
        // file" and leave the upload row with `document: null`. The
        // viewer dispatcher then decides on `fileSize` AFTER the row
        // exists, so a slightly oversized real workbook is the cleanest
        // way to drive the > 5 MiB download-fallback branch.
        const xlsxBuffer = await makeOversizeXlsx(6 * 1024 * 1024);
        const { path: docPath } = await seedKbBinaryDoc(request, access_token, workId, {
            filename: `kb-a14-xlsx-${runId}.xlsx`,
            mimeType: XLSX_MIME,
            body: xlsxBuffer,
        });
        // Same `.md` rewrite as the PDF case — viewer dispatch reads
        // `upload.mimeType`, not the doc path extension.
        expect(docPath).toMatch(/^freeform\/kb-a14-xlsx-.*\.md$/);

        await page.goto(`/en/works/${workId}/kb/${docPath}`, { waitUntil: 'domcontentloaded' });

        const xlsxViewer = page.locator('[data-testid="kb-xlsx-viewer"]');
        await expect(xlsxViewer).toBeVisible({ timeout: 60_000 });
        await expect(xlsxViewer).toHaveAttribute('data-mode', 'download');
        await expect(page.locator('[data-testid="kb-xlsx-download-fallback"]')).toBeVisible({
            timeout: 10_000,
        });
        // The download anchor's href must point at the row-21a download
        // proxy so the operator's click streams the bytes back through
        // the same CSP+nosniff-pinned route.
        const downloadLink = page.locator('[data-testid="kb-xlsx-download-link"]');
        await expect(downloadLink).toBeVisible();
        await expect(downloadLink).toHaveAttribute(
            'href',
            new RegExp(`/api/works/${workId}/kb/uploads/[^/]+/download$`),
        );
    });
});
