/**
 * Tenant Postgres DDL — the payload the managed tier's zone controller runs to
 * create one App Work's database, and the platform-data-server refusal check.
 *
 * Owning epic: **APW-07 (App env & dependencies)**, for APW-10's zone
 * controller (CONTRACTS §3:370–371, APW-10 plan §5.3, APW-07 `tasks.md` T35).
 * Implements `docs/specs/features/app-works/APW-07-app-env-and-dependencies/plan.md`
 * §4.11:697–717 and `spec.md` FR-52/FR-54.
 *
 * **Pure and dependency-free**: it imports one sibling constants module and
 * nothing else — no `node:*`, no npm package — because APW-10's controller
 * imports it directly into the zone. It is the idempotent shape of
 * `EverWorksDbProvisionService.runDdl`, hardened: the same call run twice
 * converges (step 1 emits `ALTER ROLE`, step 3 is skipped when the database
 * exists) instead of failing.
 *
 * Requirement ids: FR-52 (own owner role, closed to every other role, 20
 * connections for the role, 60-second statement and idle-in-transaction
 * timeouts), FR-53 (its own credential), FR-54 (provisioning refuses any
 * platform data server), FR-56 (probed on the live servers, not asserted from
 * configuration).
 *
 * No real hostname, address or credential appears in this file — the builder
 * takes its names and its password from the caller, and the refusal helper
 * compares against endpoints the caller supplies.
 */

import { APP_DEPENDENCY_MANAGED, APP_DEPENDENCY_POSTGRES_DEFAULT_PORT } from './app-dependencies.js';

/** Prefix of a generated tenant database name — plan §4.11:699 (`awd_<hex>`). */
export const TENANT_POSTGRES_DATABASE_PREFIX = 'awd_' as const;

/** Prefix of a generated tenant role name — plan §4.11:699 (`awr_<hex>`). */
export const TENANT_POSTGRES_ROLE_PREFIX = 'awr_' as const;

/** The generated password's shape: 32 lower-case hex characters — plan §4.11:700. */
export const TENANT_POSTGRES_PASSWORD_PATTERN = '^[0-9a-f]{32}$' as const;

/** The role's connection limit (FR-52, `APP_DEPENDENCY_MANAGED.pgRoleConnectionLimit`). */
export const TENANT_POSTGRES_ROLE_CONNECTION_LIMIT = APP_DEPENDENCY_MANAGED.pgRoleConnectionLimit;

/** The database's connection limit (FR-52, `APP_DEPENDENCY_MANAGED.pgDatabaseConnectionLimit`). */
export const TENANT_POSTGRES_DATABASE_CONNECTION_LIMIT = APP_DEPENDENCY_MANAGED.pgDatabaseConnectionLimit;

/** The role's default statement timeout (FR-52, `APP_DEPENDENCY_MANAGED.pgStatementTimeoutMs`). */
export const TENANT_POSTGRES_STATEMENT_TIMEOUT_MS = APP_DEPENDENCY_MANAGED.pgStatementTimeoutMs;

/** The role's default idle-in-transaction timeout (FR-52). */
export const TENANT_POSTGRES_IDLE_IN_TRANSACTION_TIMEOUT_MS = APP_DEPENDENCY_MANAGED.pgIdleInTransactionTimeoutMs;

/**
 * The `NO*` role attributes every tenant role carries — plan §4.11:702–703.
 *
 * Spelled the same on `CREATE` and on `ALTER`, so a re-run converges on the
 * same role rather than inheriting whatever the previous run left.
 */
export const TENANT_POSTGRES_ROLE_ATTRIBUTES = [
	'LOGIN',
	'NOSUPERUSER',
	'NOCREATEDB',
	'NOCREATEROLE',
	'NOREPLICATION',
	'NOBYPASSRLS'
] as const;

/** The database's default port for the refusal comparison — RFC 5737-safe default, plan §4.11. */
export const TENANT_POSTGRES_DEFAULT_PORT = APP_DEPENDENCY_POSTGRES_DEFAULT_PORT;

/**
 * A step of the DDL payload.
 *
 * `server` statements run against the data server (steps 1–4 of plan
 * §4.11:702–708); `database` statements run **connected to the tenant
 * database** (step 5, plan §4.11:709–710). The split exists because
 * `CREATE DATABASE` cannot run inside a transaction block and because step 5
 * needs the new database as its connection target — see
 * {@link TenantPostgresDdlPlan.createsDatabase}.
 */
export interface TenantPostgresDdlPlan {
	/** Statements 1–4, in order, run on the data server. */
	readonly server: readonly string[];
	/** Statement 5, in order, run with the tenant database as the connection target. */
	readonly database: readonly string[];
	/** `server` then `database`, flattened — the full payload in its normative order. */
	readonly statements: readonly string[];
	/** True when step 3 will create the database, so the caller must not wrap it in a transaction. */
	readonly createsDatabase: boolean;
	/** True when step 1 will `ALTER` an existing role rather than `CREATE` it. */
	readonly altersRole: boolean;
}

/** Input to {@link buildTenantPostgresDdl} — plan §4.11:699–701. */
export interface TenantPostgresDdlInput {
	/** `awd_<hex>` — plan §4.11:699. */
	readonly dbName: string;
	/** `awr_<hex>` — plan §4.11:699. */
	readonly roleName: string;
	/** 32 lower-case hex characters, generated by the zone — plan §4.11:700. */
	readonly password: string;
	/**
	 * Whether the role already exists.
	 *
	 * `true` emits `ALTER ROLE` (plan §4.11:702 "Role exists → `ALTER ROLE`"), so
	 * a re-run converges instead of failing — T35's "re-running yields `ALTER`
	 * not `CREATE`".
	 */
	readonly roleExists: boolean;
	/** Whether the database already exists; `false` emits the `CREATE DATABASE` of step 3. */
	readonly databaseExists: boolean;
	/** Step 5's extensions, from the data server's allowlist — plan §4.11:710. */
	readonly extensions?: readonly string[];
	/** Overrides, defaulting to the FR-52 values. */
	readonly roleConnectionLimit?: number;
	readonly databaseConnectionLimit?: number;
	readonly statementTimeoutMs?: number;
	readonly idleInTransactionTimeoutMs?: number;
}

/** Why {@link buildTenantPostgresDdl} refused to build a payload. */
export const TENANT_POSTGRES_DDL_REFUSALS = [
	'identifierInvalid',
	'passwordInvalid',
	'connectionLimitInvalid',
	'timeoutInvalid'
] as const;

/** A DDL build refusal reason. */
export type TenantPostgresDdlRefusal = (typeof TENANT_POSTGRES_DDL_REFUSALS)[number];

/** The outcome of {@link buildTenantPostgresDdl}. */
export type TenantPostgresDdlResult =
	| { readonly ok: true; readonly plan: TenantPostgresDdlPlan }
	| { readonly ok: false; readonly refusal: TenantPostgresDdlRefusal };

/** An identifier this module will accept: the generated names, and nothing exotic. */
const TENANT_POSTGRES_IDENTIFIER_PATTERN = /^[a-z][a-z0-9_]{0,62}$/;

/**
 * Quote a Postgres identifier, doubling any embedded `"`.
 *
 * Every identifier in every statement below goes through this function, so the
 * generated names are always double-quoted (T35) and a name can never break out
 * of its quotes into the statement text.
 */
export function quoteTenantPostgresIdentifier(name: string): string {
	return `"${name.replace(/"/g, '""')}"`;
}

/** Quote a Postgres string literal, doubling any embedded `'`. */
function quoteTenantPostgresLiteral(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}

/**
 * The ordered DDL payload for one tenant database — plan §4.11:701–710.
 *
 * Statements, in the plan's order:
 *
 * 1. Role exists → `ALTER ROLE`; otherwise `CREATE ROLE "<role>" WITH LOGIN
 *    PASSWORD '<pw>' CONNECTION LIMIT 20` with `NOSUPERUSER NOCREATEDB
 *    NOCREATEROLE NOREPLICATION NOBYPASSRLS`.
 * 2. `ALTER ROLE "<role>" SET statement_timeout = '60s'` and
 *    `ALTER ROLE "<role>" SET idle_in_transaction_session_timeout = '60s'`.
 * 3. Database missing → `CREATE DATABASE "<db>" OWNER "<role>" CONNECTION LIMIT 25`
 *    (outside a transaction).
 * 4. `REVOKE CONNECT, TEMPORARY ON DATABASE "<db>" FROM PUBLIC` and
 *    `GRANT CONNECT, TEMPORARY ON DATABASE "<db>" TO "<role>"`.
 * 5. Connected to `<db>`: `REVOKE ALL ON SCHEMA public FROM PUBLIC`,
 *    `ALTER SCHEMA public OWNER TO "<role>"`, and the declared extensions.
 *
 * The plan does not spell the `ALTER ROLE` of step 1 out; it carries the same
 * property set as the `CREATE` so that a re-run converges on the same role.
 * Fail-closed: a name that is not a plain lower-case identifier, a password that
 * is not 32 hex characters, or a non-positive limit is refused rather than
 * interpolated.
 */
export function buildTenantPostgresDdl(input: TenantPostgresDdlInput): TenantPostgresDdlResult {
	if (!TENANT_POSTGRES_IDENTIFIER_PATTERN.test(input.dbName)) return { ok: false, refusal: 'identifierInvalid' };
	if (!TENANT_POSTGRES_IDENTIFIER_PATTERN.test(input.roleName)) return { ok: false, refusal: 'identifierInvalid' };
	if (!new RegExp(TENANT_POSTGRES_PASSWORD_PATTERN).test(input.password))
		return { ok: false, refusal: 'passwordInvalid' };

	const roleLimit = input.roleConnectionLimit ?? TENANT_POSTGRES_ROLE_CONNECTION_LIMIT;
	const databaseLimit = input.databaseConnectionLimit ?? TENANT_POSTGRES_DATABASE_CONNECTION_LIMIT;
	const statementTimeoutMs = input.statementTimeoutMs ?? TENANT_POSTGRES_STATEMENT_TIMEOUT_MS;
	const idleTimeoutMs = input.idleInTransactionTimeoutMs ?? TENANT_POSTGRES_IDLE_IN_TRANSACTION_TIMEOUT_MS;
	if (!Number.isSafeInteger(roleLimit) || roleLimit < 1) return { ok: false, refusal: 'connectionLimitInvalid' };
	if (!Number.isSafeInteger(databaseLimit) || databaseLimit < 1)
		return { ok: false, refusal: 'connectionLimitInvalid' };
	if (!Number.isSafeInteger(statementTimeoutMs) || statementTimeoutMs < 1)
		return { ok: false, refusal: 'timeoutInvalid' };
	if (!Number.isSafeInteger(idleTimeoutMs) || idleTimeoutMs < 1) return { ok: false, refusal: 'timeoutInvalid' };

	const db = quoteTenantPostgresIdentifier(input.dbName);
	const role = quoteTenantPostgresIdentifier(input.roleName);
	const password = quoteTenantPostgresLiteral(input.password);
	const attributes = TENANT_POSTGRES_ROLE_ATTRIBUTES.join(' ');

	const server: string[] = [
		input.roleExists
			? `ALTER ROLE ${role} WITH ${attributes} PASSWORD ${password} CONNECTION LIMIT ${roleLimit};`
			: `CREATE ROLE ${role} WITH ${attributes} PASSWORD ${password} CONNECTION LIMIT ${roleLimit};`,
		`ALTER ROLE ${role} SET statement_timeout = ${quoteTenantPostgresLiteral(toPostgresSeconds(statementTimeoutMs))};`,
		`ALTER ROLE ${role} SET idle_in_transaction_session_timeout = ${quoteTenantPostgresLiteral(
			toPostgresSeconds(idleTimeoutMs)
		)};`
	];

	if (!input.databaseExists) {
		server.push(`CREATE DATABASE ${db} OWNER ${role} CONNECTION LIMIT ${databaseLimit};`);
	}

	server.push(`REVOKE CONNECT, TEMPORARY ON DATABASE ${db} FROM PUBLIC;`);
	server.push(`GRANT CONNECT, TEMPORARY ON DATABASE ${db} TO ${role};`);

	const database: string[] = [`REVOKE ALL ON SCHEMA public FROM PUBLIC;`, `ALTER SCHEMA public OWNER TO ${role};`];
	for (const extension of input.extensions ?? []) {
		if (!TENANT_POSTGRES_IDENTIFIER_PATTERN.test(extension)) return { ok: false, refusal: 'identifierInvalid' };
		database.push(`CREATE EXTENSION IF NOT EXISTS ${quoteTenantPostgresIdentifier(extension)};`);
	}

	return {
		ok: true,
		plan: {
			server,
			database,
			statements: [...server, ...database],
			createsDatabase: !input.databaseExists,
			altersRole: input.roleExists
		}
	};
}

/** Render a millisecond timeout as the Postgres interval literal the plan writes (`'60s'`). */
function toPostgresSeconds(milliseconds: number): string {
	return `${milliseconds / 1000}s`;
}

/* ------------------------------------------------------------------------- *
 * Platform-data-server refusal (FR-54, plan §4.11:714–717)
 * ------------------------------------------------------------------------- */

/** One of the platform's own data servers, as the caller knows it. */
export interface PlatformDataServerEndpoint {
	/** Host name or IP literal, e.g. `db.example.com` or `2001:db8::1`. */
	readonly host: string;
	/** Port; omit for the default 5432. */
	readonly port?: number;
}

/** A normalised `host:port` pair. */
export interface NormalisedDataServerEndpoint {
	readonly host: string;
	readonly port: number;
}

/**
 * Normalise a `host:port` for comparison: lower-case host, IPv6 brackets
 * stripped, missing port defaulted to {@link TENANT_POSTGRES_DEFAULT_PORT}.
 *
 * Returns `null` for anything that is not a host — an unparseable candidate is
 * never treated as "not a platform server" by accident once the caller decides
 * what to do with `null`.
 */
export function normaliseDataServerEndpoint(host: string, port?: number): NormalisedDataServerEndpoint | null {
	let normalisedHost = host.trim().toLowerCase();
	if (normalisedHost.startsWith('[') && normalisedHost.endsWith(']')) {
		normalisedHost = normalisedHost.slice(1, -1);
	}
	if (normalisedHost.length === 0) return null;
	if (port !== undefined && (!Number.isSafeInteger(port) || port < 1 || port > 65_535)) return null;
	return { host: normalisedHost, port: port ?? TENANT_POSTGRES_DEFAULT_PORT };
}

/**
 * Extract the `host:port` of a connection URL.
 *
 * Accepts a `postgres://` / `postgresql://` URL, a `host:port` pair and a bare
 * host, with or without IPv6 brackets, and defaults the port to 5432 — so
 * `db.example.com`, `DB.EXAMPLE.COM:5432` and
 * `postgresql://user@db.example.com:5432/app` are the same server (T35).
 */
export function parseDataServerUrl(url: string): NormalisedDataServerEndpoint | null {
	const trimmed = url.trim();
	if (trimmed.length === 0) return null;
	const schemeAt = trimmed.indexOf('://');
	if (schemeAt >= 0) {
		const rest = trimmed.slice(schemeAt + 3);
		const authority = rest.split(/[/?#]/, 1)[0] ?? '';
		const withoutUserInfo = authority.includes('@') ? authority.slice(authority.lastIndexOf('@') + 1) : authority;
		// IPv6 authorities are `[addr]` or `[addr]:port`, so only split on a colon
		// that follows the closing bracket.
		if (withoutUserInfo.startsWith('[')) {
			const closing = withoutUserInfo.indexOf(']');
			if (closing < 0) return null;
			const host = withoutUserInfo.slice(1, closing);
			const tail = withoutUserInfo.slice(closing + 1);
			if (tail.length === 0) return normaliseDataServerEndpoint(host);
			if (!tail.startsWith(':')) return null;
			return normaliseDataServerEndpoint(host, Number(tail.slice(1)));
		}
		const separator = withoutUserInfo.lastIndexOf(':');
		if (separator < 0) return normaliseDataServerEndpoint(withoutUserInfo);
		const host = withoutUserInfo.slice(0, separator);
		const portText = withoutUserInfo.slice(separator + 1);
		return normaliseDataServerEndpoint(host, portText.length === 0 ? undefined : Number(portText));
	}
	if (trimmed.startsWith('[')) {
		const closing = trimmed.indexOf(']');
		if (closing < 0) return null;
		const host = trimmed.slice(1, closing);
		const tail = trimmed.slice(closing + 1);
		if (tail.length === 0) return normaliseDataServerEndpoint(host);
		if (!tail.startsWith(':')) return null;
		return normaliseDataServerEndpoint(host, Number(tail.slice(1)));
	}
	const separator = trimmed.lastIndexOf(':');
	if (separator < 0) return normaliseDataServerEndpoint(trimmed);
	return normaliseDataServerEndpoint(trimmed.slice(0, separator), Number(trimmed.slice(separator + 1)));
}

/**
 * Is this connection URL one of the platform's own data servers?
 *
 * FR-54: "Provisioning refuses any server that is one of the platform's own
 * data servers." The comparison is a normalised `host:port` match — host
 * case-insensitively, IPv6 brackets stripped, a missing port equal to 5432,
 * exactly as plan §4.11:714–717 specifies.
 *
 * The plan adds "plus `system_identifier` when readable"; that half needs a live
 * connection to the candidate server and stays with the caller (the zone
 * controller for its own configuration, the platform when it validates an
 * admin-scope server setting). This function is pure and connects to nothing,
 * which is why it can be imported into the zone.
 */
export function isPlatformDataServer(
	candidate: string,
	platformEndpoints: readonly PlatformDataServerEndpoint[]
): boolean {
	const parsed = parseDataServerUrl(candidate);
	if (parsed === null) return false;
	return platformEndpoints.some((endpoint) => {
		const normalised = normaliseDataServerEndpoint(endpoint.host, endpoint.port);
		return normalised !== null && normalised.host === parsed.host && normalised.port === parsed.port;
	});
}

/**
 * The platform data servers a refusal check is built from, collected so no
 * caller reconstructs the pair by hand: the platform database and the shared
 * Work database (plan §4.11:714–716).
 */
export interface PlatformDataServerSet {
	/** `config.database.*` — the platform's own database. */
	readonly platform: PlatformDataServerEndpoint;
	/** `config.everWorks.sharedDb.*` — the shared Work database. */
	readonly sharedWorks: PlatformDataServerEndpoint;
}

/** Flatten a {@link PlatformDataServerSet} into the list {@link isPlatformDataServer} takes. */
export function platformDataServerEndpoints(set: PlatformDataServerSet): PlatformDataServerEndpoint[] {
	return [set.platform, set.sharedWorks];
}
