/**
 * T3 — the five `hosting.ever.works` CRD manifests, in one deterministic list (plan §3:216–221,
 * §3.8:479, tasks T3).
 *
 * This module is the **single** place the manifests and their YAML exist: `scripts/generate-crds.ts`
 * writes it to `deploy/crds/*.yaml`, and `src/crds/__tests__/crds.spec.ts` asserts that what is
 * committed is byte-identical to it — so the drift gate and the generator cannot disagree about
 * what "the CRDs" are (the task's "CI fails if generated CRDs drift").
 *
 * Serialisation is fixed (`indent: 2`, no line folding, no aliases, declaration order) because the
 * committed files are compared byte-for-byte: a change in serializer output is a change to the
 * artefact, and it must show up as a diff in review rather than as a silent reformat.
 *
 * The indent matches the repository's Prettier rule for YAML (2 spaces, no tabs — the
 * `*.yml`/`*.yaml` overrides in the root `package.json`), so `pnpm exec prettier --check
 * deploy/crds/*.yaml` is a no-op on a freshly generated file instead of a reformat that would fail
 * the drift guard.
 */
import type { KubernetesObject } from '@kubernetes/client-node';
import * as yaml from 'js-yaml';

import { ABUSE_SIGNAL_CRD } from './abusesignal.js';
import { APP_BUILD_CRD } from './appbuild.js';
import type { CustomResourceDefinitionManifest } from './crd.js';
import { SELF_CHECK_CRD } from './selfcheck.js';
import { USAGE_REPORT_CRD } from './usagereport.js';
import { WORK_CRD } from './work.js';

/** Where the generated manifests live, relative to this package. */
export const CRD_DIRECTORY = 'deploy/crds';

/** One committed manifest: its kind, its file name and its bytes. */
export interface CrdManifestFile {
	readonly kind: string;
	readonly fileName: string;
	readonly manifest: CustomResourceDefinitionManifest;
	readonly yaml: string;
}

/**
 * The five manifests in the order the plan introduces them — `Work`, then the four of §3.2.
 *
 * All five are namespaced in the control namespace (plan §3:220), which each schema states by
 * construction (`crd.ts`).
 */
export const CRD_MANIFESTS: readonly CustomResourceDefinitionManifest[] = [
	WORK_CRD,
	SELF_CHECK_CRD,
	USAGE_REPORT_CRD,
	ABUSE_SIGNAL_CRD,
	APP_BUILD_CRD
];

/**
 * The comment every generated file opens with.
 *
 * It is part of the artefact, so it is part of the byte comparison: a hand edit to a committed CRD
 * fails the drift test, and the first line says where the edit belongs instead.
 */
export function manifestHeader(kind: string): string {
	return [
		`# Generated by \`pnpm --filter ever-works-apps-tier-controller generate:crds\` — do not edit by hand.`,
		`# Source: apps/apps-tier-controller/src/crds/${kind.toLowerCase()}.ts (APW-10 plan §3.1–3.2).`,
		`# \`pnpm test\` asserts this file is byte-identical to a fresh generation.`
	].join('\n');
}

/** Serialise one manifest: fixed options, a trailing newline, and the generated-file header. */
export function serializeCrdManifest(manifest: CustomResourceDefinitionManifest): string {
	const body = yaml.dump(manifest, {
		indent: 2,
		lineWidth: -1,
		noRefs: true,
		sortKeys: false,
		skipInvalid: false
	});
	return `${manifestHeader(manifest.spec.names.kind)}\n${body}`;
}

/** A manifest's file name inside {@link CRD_DIRECTORY}. */
export function crdFileName(manifest: CustomResourceDefinitionManifest): string {
	return `${manifest.spec.names.plural}.yaml`;
}

/** The generated files, ready to write or to compare. */
export function crdManifestFiles(): readonly CrdManifestFile[] {
	return CRD_MANIFESTS.map((manifest) => ({
		kind: manifest.spec.names.kind,
		fileName: crdFileName(manifest),
		manifest,
		yaml: serializeCrdManifest(manifest)
	}));
}

/**
 * Parse a committed manifest back into an object.
 *
 * Used by the drift test to prove the committed YAML is not merely equal to the generated text but
 * also *loads*: a serialiser that emitted a document the API server would reject (an unquoted
 * pattern, a folded scalar) would still compare equal to itself, and this is what catches that.
 */
export function parseCrdManifest(source: string): KubernetesObject {
	return yaml.load(source) as KubernetesObject;
}
