import { Injectable, Logger } from '@nestjs/common';
import { UserRepository } from '@ever-works/agent/database';
import { WorkLifecycleService } from '@ever-works/agent/services';
import type { OnboardingWorkCreator } from '@ever-works/agent/onboarding';

interface ManifestShape {
    metadata: {
        name: string;
        slug?: string;
        description?: string;
    };
    spec: {
        deployment?: { target?: string };
        output?: { repos?: { website?: string; awesomeList?: string } };
    };
}

/**
 * Api-side implementation of `OnboardingWorkCreator` (T9c).
 *
 * Translates the parsed `works.yml` manifest into a `CreateWorkDto` and
 * delegates to the existing `WorkLifecycleService.createWork`. The
 * lifecycle service handles the heavy lifting:
 *   - Creates the Work row + the data, website, and (optionally) awesome
 *     repositories under the agent's GitHub user/org.
 *   - Kicks off the existing data-generation flow.
 *
 * Returns `{ workId }` so the OnboardingRequest row can be patched and
 * the agent's status URL starts returning the real work id.
 */
@Injectable()
export class OnboardingWorkAdapter implements OnboardingWorkCreator {
    private readonly logger = new Logger(OnboardingWorkAdapter.name);

    constructor(
        private readonly workLifecycle: WorkLifecycleService,
        private readonly users: UserRepository,
    ) {}

    async createFromManifest(input: {
        accountId: string;
        githubAccessToken: string;
        manifestRepoUrl: string;
        manifest: Record<string, unknown>;
        subdomain: string;
        onboardingId: string;
    }): Promise<{ workId: string }> {
        const manifest = input.manifest as unknown as ManifestShape;
        const user = await this.users.findById(input.accountId);
        if (!user) {
            throw new Error(`accountId ${input.accountId} not found when creating Work`);
        }

        const owner = parseRepoOwner(input.manifestRepoUrl);
        const slug = (manifest.metadata.slug || slugify(manifest.metadata.name)).slice(0, 63);
        const description =
            manifest.metadata.description ||
            `Auto-generated by Ever Works zero-friction onboarding (${input.onboardingId.slice(0, 8)}).`;

        const dto = {
            slug,
            name: manifest.metadata.name,
            description,
            owner,
            organization: false,
            gitProvider: 'github',
            deployProvider: manifest.spec.deployment?.target ?? 'vercel',
            websiteTemplateId: 'classic',
        };

        try {
            const result = await this.workLifecycle.createWork(dto as any, user);
            const workId = (result?.work as { id?: string } | undefined)?.id;
            if (!workId) {
                throw new Error('createWork returned no work id');
            }
            this.logger.log(
                `onboarding.work_created onboardingId=${input.onboardingId} workId=${workId} slug=${slug}`,
            );
            return { workId };
        } catch (err) {
            this.logger.warn(
                `onboarding.work_creation_failed onboardingId=${input.onboardingId} reason=${describeError(err)}`,
            );
            throw err;
        }
    }
}

function parseRepoOwner(url: string): string {
    try {
        const u = new URL(url);
        const segments = u.pathname.replace(/\.git$/, '').split('/').filter(Boolean);
        return segments[0] ?? '';
    } catch {
        return '';
    }
}

function slugify(name: string): string {
    return (
        name
            .toLowerCase()
            .trim()
            .replace(/[^a-z0-9]+/g, '-')
            .replace(/^-+|-+$/g, '')
            .slice(0, 63) || 'work'
    );
}

function describeError(err: unknown): string {
    return err instanceof Error ? err.message : String(err);
}
