export const README = [
	'## What is the Composio Integrations plugin?',
	'',
	"This plugin lets Ever Works call any of [Composio](https://composio.dev)'s 500+ third-party app integrations (Gmail, Slack, GitHub, Notion, Linear, Salesforce, HubSpot, Stripe, Shopify, Airtable, …) during Work generation.",
	"Composio brokers OAuth on your behalf: each user connects an app once through Composio's hosted flow, and the platform reuses that connection to execute tools.",
	'',
	'## Why use it?',
	'',
	'- **500+ ready-made integrations** — no per-app connector code to write',
	'- **OAuth handled for you** — Composio manages tokens, refresh, scopes, and rate limits',
	'- **Per-user accounts** — every user can connect their own Gmail / Slack / GitHub without sharing credentials',
	'- **Three result shapes** — structured items, native records via field mapping, or side-effect only',
	'- **Side-effect actions** — send messages, create issues, or trigger downstream workflows without producing items',
	'',
	'## How it works in Ever Works',
	'',
	'When this plugin is selected as the active pipeline, the platform calls the Composio v3 REST API:',
	'',
	'1. **Validate** — checks that the Composio API key is accepted and that the user has an ACTIVE connected account for the requested toolkit',
	'2. **Prepare Payload** — builds the input with work metadata, existing items summary, and custom arguments',
	'3. **Execute Tool** — `POST /tools/execute/{tool_slug}` with `{ user_id, arguments }`',
	'4. **Collect Results** — converts the response into work items or completes a side-effect action',
	'5. **Capture Screenshots** — optionally captures screenshots for generated items',
	'6. **Cleanup** — releases resources',
	'',
	'The plugin treats the **tool slug** (e.g. `GMAIL_SEND_EMAIL`, `GITHUB_CREATE_ISSUE`) as the unique identifier of an action — toolkit slug is informational and used only for connection validation.',
	'',
	'## Result modes',
	'',
	'- **Structured items** — for custom tools that already return `{ items: [...] }` in the work-item shape',
	'- **Native records** — for catalog tools (Gmail messages, Notion pages, GitHub issues, …) that return records you map onto work items via a field mapping',
	'- **Side-effect only** — for tools that send a message, create a task, or update another system without adding work items',
	'',
	'## Data passing strategies',
	'',
	'- **Inline summary** (default) — work metadata and a sample of existing items are sent in the tool arguments',
	'- **GitHub repository** — pass a repo URL and access token so the tool can read the full dataset directly',
	'',
	'## Required configuration',
	'',
	'- **Composio API key** — a single platform key, generated at https://app.composio.dev/settings/api-keys',
	'- **Composio User ID** (optional override) — defaults to your Ever Works user id; set this if you connected the upstream account under a different identifier (typically an email)',
	'- **Toolkit slug** — the upstream app (e.g. `GMAIL`, `GITHUB`, `SLACK`)',
	'- **Tool slug** — the specific action inside the toolkit (e.g. `GMAIL_SEND_EMAIL`)',
	'',
	'## Tool input & output',
	'',
	"Composio executes the tool against the user's connected account using the arguments you provide.",
	'',
	'<details>',
	'<summary><strong>Input your tool receives</strong></summary>',
	'',
	'```json',
	'{',
	'  "metadata": {',
	'    "workId": "dir-123",',
	'    "workName": "Best AI Tools",',
	'    "workSlug": "best-ai-tools",',
	'    "workDescription": "A curated list of the best AI tools",',
	'    "prompt": "Find the best AI writing tools",',
	'    "generationMethod": "create-update",',
	'    "targetItems": 50',
	'  },',
	'  "existingSummary": {',
	'    "totalItems": 10,',
	'    "categories": ["Writing", "Image Generation"],',
	'    "tags": ["free", "open-source"],',
	'    "sampleItems": [{ "name": "ChatGPT", "url": "https://chat.openai.com" }]',
	'  },',
	'  "toolParams": { "to": "alice@example.com", "subject": "Hello" }',
	'}',
	'```',
	'',
	'- `existingSummary` is omitted when the work is empty or the user disables it via **Pass Existing Items Summary**',
	'- `toolParams` is also spread at the top level so catalog tools see their required inputs (e.g. `to`, `subject`, `body` for `GMAIL_SEND_EMAIL`)',
	'- `metadata.targetItems` is the number of new items the user asked for',
	'',
	'</details>',
	'',
	'<details>',
	'<summary><strong>Structured output your tool can return</strong></summary>',
	'',
	'For Structured items mode, return a JSON object with an `items` array:',
	'',
	'```json',
	'{',
	'  "items": [',
	'    {',
	'      "name": "Tool Name",',
	'      "description": "A concise description (1-3 sentences)",',
	'      "url": "https://example.com",',
	'      "category": "Category Name",',
	'      "tags": ["tag1", "tag2"],',
	'      "content": "Optional longer markdown content",',
	'      "brand": "Optional brand name",',
	'      "images": ["https://example.com/screenshot.png"]',
	'    }',
	'  ]',
	'}',
	'```',
	'',
	'**Required field:** `name`',
	'',
	'**Recommended fields:** `description`, `url`, `category`, `tags`',
	'',
	'**Optional fields:** `content` (stored as markdown), `brand`, `images`',
	'',
	'</details>',
	'',
	'## Connecting a toolkit (one-time, per user)',
	'',
	'1. Sign in to [Composio](https://app.composio.dev) and locate the toolkit you want (e.g. Gmail)',
	'2. Add an **auth config** for the toolkit (Composio-managed OAuth is fastest; bring-your-own OAuth credentials is also supported)',
	'3. From the Connected Accounts page, **Initiate** a connection for your `user_id` and complete the OAuth flow',
	'4. Confirm the account shows status `ACTIVE` in the Composio dashboard',
	'5. In Ever Works, open the Composio plugin settings, set the `Toolkit` and `Tool Slug` for your work, and trigger a run',
	'',
	'## Getting started',
	'',
	'1. Create a Composio account at [composio.dev](https://composio.dev) and grab your API key from **Settings → API Keys**',
	'2. Connect at least one toolkit (Gmail, GitHub, Slack, …) under your Composio `user_id`',
	'3. Open the Composio plugin settings in Ever Works and paste the API key (and, if needed, override the Composio `user_id`). Save.',
	'4. In the **Generate** flow, set `toolkit`, `tool_slug`, the result shape, and any custom tool arguments, then trigger a run.'
].join('\n');
