export const README = [
	'## What is the SIM AI Workflows plugin?',
	'',
	'This plugin delegates the entire directory generation process to a [SIM AI](https://www.sim.ai) workflow.',
	'SIM AI is an open-source visual workflow builder for designing and deploying AI agent workflows.',
	'Instead of using the built-in generation pipeline, you design your own workflow in SIM Studio and this plugin triggers it.',
	'',
	'## Why use it?',
	'',
	'- **Full control** — design your own generation logic visually in SIM Studio',
	'- **Custom data sources** — connect to any API, database, or scraper within your workflow',
	'- **Flexible AI models** — use any model supported by SIM (OpenAI, Anthropic, Google, open-source)',
	'- **Async execution** — workflows run asynchronously with automatic polling (up to 2 hours)',
	'- **Deduplication** — existing directory items are summarized and passed to the workflow to avoid duplicates',
	'',
	'## How it works',
	'',
	'1. **Validate** — checks your API key and verifies the SIM workflow is deployed and reachable',
	'2. **Prepare Payload** — builds the input with directory metadata, existing items summary, and custom parameters',
	'3. **Execute Workflow** — calls the SIM API asynchronously and polls until completion',
	'4. **Collect Results** — parses the workflow output into structured directory items with categories, tags, and brands',
	'5. **Capture Screenshots** — optionally captures screenshots for generated items using the configured screenshot provider',
	'6. **Cleanup** — releases resources',
	'',
	'## Data passing strategies',
	'',
	'- **Inline summary** (default) — directory metadata and a sample of existing items are sent in the workflow input payload',
	'- **GitHub repository** — pass a repo URL and access token so the workflow can read the full dataset directly',
	'',
	'## Workflow input & output',
	'',
	'Your SIM workflow receives a JSON payload via `<start.message>` and must return structured items.',
	'',
	'<details>',
	'<summary><strong>Input your workflow receives</strong></summary>',
	'',
	'The input is a JSON string with this structure:',
	'',
	'```json',
	'{',
	'  "metadata": {',
	'    "directoryId": "dir-123",',
	'    "directoryName": "Best AI Tools",',
	'    "directorySlug": "best-ai-tools",',
	'    "directoryDescription": "A curated list of the best AI tools",',
	'    "prompt": "Find the best AI writing tools",',
	'    "generationMethod": "create-update",',
	'    "targetItems": 50',
	'  },',
	'  "existingSummary": {',
	'    "totalItems": 10,',
	'    "categories": ["Writing", "Image Generation"],',
	'    "tags": ["free", "open-source"],',
	'    "sampleItems": [',
	'      { "name": "ChatGPT", "url": "https://chat.openai.com" }',
	'    ]',
	'  },',
	'  "workflowParams": {}',
	'}',
	'```',
	'',
	'- `existingSummary` is optional — absent if the directory is empty or the user disabled it',
	'- `workflowParams` contains any custom key-value pairs passed from the Advanced form section',
	'- `metadata.targetItems` is the number of new items the user wants',
	'',
	'</details>',
	'',
	'<details>',
	'<summary><strong>Output your workflow must return</strong></summary>',
	'',
	'Return a JSON object with an `items` array:',
	'',
	'```json',
	'{',
	'  "items": [',
	'    {',
	'      "name": "Tool Name",',
	'      "description": "A concise description (1-3 sentences)",',
	'      "url": "https://example.com",',
	'      "category": "Category Name",',
	'      "tags": ["tag1", "tag2"],',
	'      "content": "Optional longer markdown content",',
	'      "brand": "Optional brand name",',
	'      "images": ["https://example.com/screenshot.png"]',
	'    }',
	'  ]',
	'}',
	'```',
	'',
	'**Required fields:** `name`, `description`, `url`, `category`, `tags`',
	'',
	'**Optional fields:** `content` (stored as markdown), `brand`, `images`',
	'',
	'</details>',
	'',
	'<details>',
	'<summary><strong>Example prompt for SIM AI chat</strong></summary>',
	'',
	"Paste this into SIM Studio's AI chat to generate a starter workflow:",
	'',
	'```',
	'Build a workflow that generates directory listing items.',
	'',
	'Input: The workflow receives a JSON string via <start.message> with:',
	'- metadata.prompt — what kind of items to find (e.g. "Find the best AI writing tools")',
	'- metadata.directoryName — the directory name',
	'- metadata.directoryDescription — what the directory is about',
	'- metadata.targetItems — how many items to generate',
	'- existingSummary (optional) — summary of existing items to avoid duplicates',
	'',
	'Steps:',
	'1. Parse the JSON input from <start.message>',
	'2. Use the prompt and directory description to understand what items to find',
	'3. If existingSummary is present, avoid generating items with the same names or URLs',
	'4. Use web search to find real items with valid URLs',
	'5. Generate up to targetItems new items',
	'',
	'Output: Return a JSON object with an "items" array where each item has:',
	'- name (required) — item name',
	'- description (required) — 1-3 sentence description',
	'- url (required) — real website URL',
	'- category (required) — category name',
	'- tags (required) — array of tag strings',
	'- content (optional) — longer markdown description',
	'- brand (optional) — company or brand name',
	'- images (optional) — array of image URLs',
	'```',
	'',
	'</details>',
	'',
	'## Getting started',
	'',
	'1. Build and deploy a workflow in [SIM Studio](https://www.sim.ai)',
	'2. Copy your API key from the SIM dashboard',
	'3. Enable this plugin and enter your API key in the settings',
	'4. When generating a directory, select SIM AI as the pipeline and provide the workflow ID'
].join('\n');
