export const README = [
	'## What is the SIM AI Workflows plugin?',
	'',
	'This plugin delegates the entire directory generation process to a [SIM AI](https://www.sim.ai) workflow.',
	'SIM AI is an open-source visual workflow builder for designing and deploying AI agent workflows.',
	'Instead of using the built-in generation pipeline, you design your own workflow in SIM Studio and this plugin triggers it.',
	'',
	'## Why use it?',
	'',
	'- **Full control** — design your own generation logic visually in SIM Studio',
	'- **Custom data sources** — connect to any API, database, or scraper within your workflow',
	'- **Flexible AI models** — use any model supported by SIM (OpenAI, Anthropic, Google, open-source)',
	'- **Async support** — long-running workflows execute asynchronously with automatic polling',
	'- **Deduplication** — existing directory items are summarized and passed to the workflow to avoid duplicates',
	'',
	'## How it works',
	'',
	'1. **Validate** — checks your API key and verifies the SIM workflow is deployed and reachable',
	'2. **Prepare Payload** — builds the input with directory metadata, existing items summary, and custom parameters',
	'3. **Execute Workflow** — calls the SIM API (sync for fast workflows, async with polling for long-running ones)',
	'4. **Collect Results** — parses the workflow output into structured directory items with categories, tags, and brands',
	'5. **Capture Screenshots** — optionally captures screenshots for generated items using the configured screenshot provider',
	'6. **Cleanup** — releases resources',
	'',
	'## Data passing strategies',
	'',
	'- **Inline summary** (default) — directory metadata and a sample of existing items are sent in the workflow input payload',
	'- **GitHub repository** — pass a repo URL and access token so the workflow can read the full dataset directly',
	'',
	'## Expected workflow output',
	'',
	'Your SIM workflow must return a JSON object with an `items` array:',
	'',
	'```json',
	'{',
	'  "items": [',
	'    {',
	'      "name": "Item Name",',
	'      "description": "Short description",',
	'      "url": "https://example.com",',
	'      "category": "Category Name",',
	'      "tags": ["tag1", "tag2"],',
	'      "content": "Optional longer markdown content",',
	'      "brand": "Optional brand name",',
	'      "images": ["https://example.com/image.png"]',
	'    }',
	'  ]',
	'}',
	'```',
	'',
	'Required fields: `name`, `description`, `url`, `category`, `tags`.',
	'Optional fields: `content` (stored as markdown), `brand`, `images`.',
	'',
	'## Getting started',
	'',
	'1. Build and deploy a workflow in [SIM Studio](https://www.sim.ai)',
	'2. Copy your API key from the SIM dashboard',
	'3. Enable this plugin and enter your API key in the settings',
	'4. When generating a directory, select SIM AI as the pipeline and provide the workflow ID'
].join('\n');
