export const README = [
	'## What is the Make.com Workflows plugin?',
	'',
	'This plugin delegates the directory generation process to a [Make.com](https://www.make.com) scenario or webhook.',
	'Make.com (formerly Integromat) is a visual automation platform that lets you connect apps and services into powerful workflows (“scenarios”).',
	'Instead of using the built-in generation pipeline, you design your own scenario on Make.com and this plugin triggers it at the right stage of the pipeline.',
	'',
	'## Why use it?',
	'',
	'- **Full control** — design your generation logic visually in Make.com',
	'- **Hundreds of integrations** — Make.com ships with 2,000+ pre-built app connectors',
	'- **Scenarios and webhooks** — trigger via REST API (with polling) or directly via webhook URL',
	'- **Hook management** — optionally ping a Make.com hook before running the scenario',
	'- **Deduplication** — existing directory items are summarized and passed to the scenario to avoid duplicates',
	'',
	'## How it works',
	'',
	'1. **Validate** — checks your API key and verifies the scenario/hook is reachable',
	'2. **Prepare Payload** — builds the input with directory metadata, existing items summary, and custom parameters',
	'3. **Execute Scenario** — runs the scenario via the REST API (`POST /scenarios/{id}/run` and polls `GET /scenarios/{id}/executions/{executionId}`) or invokes the webhook URL directly',
	'4. **Collect Results** — parses the scenario output into structured directory items with categories, tags, and brands',
	'5. **Capture Screenshots** — optionally captures screenshots for generated items using the configured screenshot provider',
	'6. **Cleanup** — releases resources',
	'',
	'## Data passing strategies',
	'',
	'- **Inline summary** (default) — directory metadata and a sample of existing items are sent in the scenario input payload',
	'- **GitHub repository** — pass a repo URL and access token so the scenario can read the full dataset directly',
	'',
	'## Scenario input & output',
	'',
	'Your Make.com scenario receives structured input fields and must return structured items.',
	'',
	'<details>',
	'<summary><strong>Input your scenario receives</strong></summary>',
	'',
	'```json',
	'{',
	'  "metadata": {',
	'    "directoryId": "dir-123",',
	'    "directoryName": "Best AI Tools",',
	'    "directorySlug": "best-ai-tools",',
	'    "directoryDescription": "A curated list of the best AI tools",',
	'    "prompt": "Find the best AI writing tools",',
	'    "generationMethod": "create-update",',
	'    "targetItems": 50',
	'  },',
	'  "existingSummary": {',
	'    "totalItems": 10,',
	'    "categories": ["Writing", "Image Generation"],',
	'    "tags": ["free", "open-source"],',
	'    "sampleItems": [',
	'      { "name": "ChatGPT", "url": "https://chat.openai.com" }',
	'    ]',
	'  },',
	'  "scenarioParams": {}',
	'}',
	'```',
	'',
	'- `existingSummary` is optional — absent if the directory is empty or the user disabled it',
	'- `scenarioParams` contains any custom key-value pairs passed from the Advanced form section',
	'- `metadata.targetItems` is the number of new items the user wants',
	'',
	'</details>',
	'',
	'<details>',
	'<summary><strong>Output your scenario must return</strong></summary>',
	'',
	'Return a JSON object with an `items` array:',
	'',
	'```json',
	'{',
	'  "items": [',
	'    {',
	'      "name": "Tool Name",',
	'      "description": "A concise description (1-3 sentences)",',
	'      "url": "https://example.com",',
	'      "category": "Category Name",',
	'      "tags": ["tag1", "tag2"],',
	'      "content": "Optional longer markdown content",',
	'      "brand": "Optional brand name",',
	'      "images": ["https://example.com/screenshot.png"]',
	'    }',
	'  ]',
	'}',
	'```',
	'',
	'**Required fields:** `name`, `description`, `url`, `category`, `tags`',
	'',
	'**Optional fields:** `content` (stored as markdown), `brand`, `images`',
	'',
	'</details>',
	'',
	'## Getting started',
	'',
	'1. Build and activate a scenario in [Make.com](https://www.make.com) (us2 zone)',
	'2. Generate an API key with all scopes enabled from the Make.com dashboard',
	'3. Enable this plugin and enter your API key and (optionally) team/organization ID in the settings',
	'4. When generating a directory, select Make.com as the pipeline and provide the scenario ID or webhook URL'
].join('\n');
