import type { RuntimeSelection } from '../shared/ipc-contract';
import { getRuntime } from '../shared/runtimes';

/** IO abstraction so runtime setup is unit-testable without touching disk/Docker. */
export interface RuntimeSetupIo {
	run(
		command: string,
		args: string[],
		options?: { cwd?: string }
	): Promise<{ code: number | null; stdout: string; stderr: string }>;
	readFile(path: string): Promise<string | undefined>;
	writeFile(path: string, content: string): Promise<void>;
}

export interface BuildEnvOptions {
	/** Absolute path used for the embedded SQLite database file. */
	sqliteDbPath?: string;
}

export const ENV_FILE_HEADER = [
	'# Generated by Ever Works Desktop (install wizard).',
	'# Values here are passed to the locally supervised API/web processes.',
	'# You may edit this file; re-running the wizard overwrites the keys it owns.'
].join('\n');

/**
 * Desktop-owned marker recording which job runtime the user picked.
 *
 * This is what the API reads at boot to persist the wizard's choice into
 * `tenant_job_runtime_config` (A9): the install wizard runs BEFORE anybody has
 * signed in, so there is no session it could use to call the admin API. The
 * env file is the handoff — the wizard writes the choice here, and the API
 * materialises the overlay row for the tenant the moment one exists.
 */
export const DESKTOP_RUNTIME_ENV_KEY = 'EVER_WORKS_DESKTOP_JOB_RUNTIME';

/**
 * The platform-global runtime selector (ADR-015 / EW-683). Written alongside
 * the desktop marker so the supervised API actually BOOTS on the runtime the
 * user chose — without it the wizard's choice was cosmetic until somebody
 * edited the env file by hand.
 */
export const PLATFORM_RUNTIME_ENV_KEY = 'EVER_WORKS_JOB_RUNTIME';

/**
 * Map a `job-runtime-*` plugin id to the provider id used by the platform's
 * runtime selector and by `tenant_job_runtime_config.providerId`
 * (`trigger | temporal | bullmq | pgboss | inngest | node`).
 */
export function toJobRuntimeProviderId(runtimeId: string): string {
	return runtimeId.replace(/^job-runtime-/, '');
}

/**
 * Translate the wizard's runtime selection into concrete env file entries:
 * service ports/URLs, database configuration and the selected runtime's own
 * `x-envVar` fields (user values falling back to field defaults).
 */
export function buildEnvEntries(selection: RuntimeSelection, options: BuildEnvOptions = {}): Record<string, string> {
	const runtime = getRuntime(selection.runtimeId);
	if (!runtime) {
		throw new Error(`Unknown job runtime: ${selection.runtimeId}`);
	}

	const entries: Record<string, string> = {
		PORT: '3100',
		WEB_URL: 'http://localhost:3000',
		API_URL: 'http://localhost:3100'
	};

	if (selection.database === 'embedded-sqlite') {
		entries.DATABASE_TYPE = 'sqlite';
		entries.DATABASE_IN_MEMORY = 'false';
		if (options.sqliteDbPath) {
			entries.DATABASE_PATH = options.sqliteDbPath;
		}
	} else if (selection.database === 'docker-postgres') {
		// Matches the defaults baked into docker-compose.infra.yml.
		entries.DATABASE_TYPE = 'postgres';
		entries.DATABASE_HOST = 'localhost';
		entries.DATABASE_PORT = '5432';
		entries.DATABASE_USERNAME = 'postgres';
		entries.DATABASE_PASSWORD = 'ever_works_password';
		entries.DATABASE_NAME = 'ever_works';
	} else {
		entries.DATABASE_TYPE = 'postgres';
		if (selection.externalDatabaseUrl) {
			entries.DATABASE_URL = selection.externalDatabaseUrl;
		}
	}

	entries[DESKTOP_RUNTIME_ENV_KEY] = runtime.id;
	entries[PLATFORM_RUNTIME_ENV_KEY] = toJobRuntimeProviderId(runtime.id);

	for (const field of runtime.fields) {
		const value = selection.values[field.key] ?? field.defaultValue;
		if (value !== undefined && value !== '') {
			entries[field.key] = value;
		}
	}

	return entries;
}

/** Parse a dotenv-style file. Ignores blank lines and `#` comments; strips surrounding double quotes. */
export function parseEnvFile(content: string): Record<string, string> {
	const entries: Record<string, string> = {};
	for (const rawLine of content.split(/\r?\n/)) {
		const line = rawLine.trim();
		if (line === '' || line.startsWith('#')) {
			continue;
		}
		const eq = line.indexOf('=');
		if (eq <= 0) {
			continue;
		}
		const key = line.slice(0, eq).trim();
		let value = line.slice(eq + 1).trim();
		if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
			value = value.slice(1, -1);
		}
		entries[key] = value;
	}
	return entries;
}

/** Serialize entries as a dotenv file (quoting values that contain spaces or `#`). */
export function serializeEnvFile(entries: Record<string, string>): string {
	const lines = Object.entries(entries).map(([key, value]) => {
		const needsQuotes = /[\s#]/.test(value);
		return `${key}=${needsQuotes ? `"${value}"` : value}`;
	});
	return `${ENV_FILE_HEADER}\n\n${lines.join('\n')}\n`;
}

/** Merge generated entries over an existing env file's entries (generated keys win, unrelated keys survive). */
export function mergeEnvEntries(
	existing: Record<string, string>,
	next: Record<string, string>
): Record<string, string> {
	return { ...existing, ...next };
}

export async function detectDocker(io: RuntimeSetupIo): Promise<{ available: boolean; version?: string }> {
	try {
		const result = await io.run('docker', ['--version']);
		if (result.code !== 0) {
			return { available: false };
		}
		const match = result.stdout.match(/(\d+\.\d+(?:\.\d+)?)/);
		return { available: true, version: match ? match[1] : undefined };
	} catch {
		return { available: false };
	}
}

/** Bring up the platform's backing services (Postgres + Redis) via the repo's infra compose file. */
export async function startDockerInfra(io: RuntimeSetupIo, repoRoot: string): Promise<{ ok: boolean; output: string }> {
	const result = await io.run('docker', ['compose', '-f', 'docker-compose.infra.yml', 'up', '-d'], { cwd: repoRoot });
	return { ok: result.code === 0, output: `${result.stdout}\n${result.stderr}`.trim() };
}

export interface ApplyRuntimeSelectionOptions {
	selection: RuntimeSelection;
	envFilePath: string;
	repoRoot: string;
	sqliteDbPath?: string;
}

export interface ApplyRuntimeSelectionResult {
	envFilePath: string;
	entries: Record<string, string>;
	dockerStarted: boolean;
}

/**
 * Full wizard "apply" step: optionally provision docker infra (detecting
 * Docker first), then merge the generated entries into the env file.
 */
export async function applyRuntimeSelection(
	io: RuntimeSetupIo,
	options: ApplyRuntimeSelectionOptions
): Promise<ApplyRuntimeSelectionResult> {
	const { selection, envFilePath, repoRoot, sqliteDbPath } = options;

	let dockerStarted = false;
	if (selection.useDockerInfra) {
		const docker = await detectDocker(io);
		if (!docker.available) {
			throw new Error('Docker is not available — cannot provision docker-compose infrastructure');
		}
		const infra = await startDockerInfra(io, repoRoot);
		if (!infra.ok) {
			throw new Error(`docker compose up failed: ${infra.output}`);
		}
		dockerStarted = true;
	}

	const generated = buildEnvEntries(selection, { sqliteDbPath });
	const existingContent = await io.readFile(envFilePath);
	const existing = existingContent ? parseEnvFile(existingContent) : {};
	const entries = mergeEnvEntries(existing, generated);
	await io.writeFile(envFilePath, serializeEnvFile(entries));

	return { envFilePath, entries, dockerStarted };
}
