/**
 * GENERATED FILE — do not edit by hand.
 *
 * Built by `apps/web/scripts/build-help-catalog.mjs` from the documentation pages listed in
 * `apps/web/src/content/help/manual.json`. Regenerate with
 * `pnpm --filter ever-works-web help:build`; `help-catalog.unit.spec.ts` fails when this file
 * no longer matches the documentation it was built from.
 */
import type { HelpArticleMeta } from './help-types';

export const HELP_ARTICLES = [
    {
        id: 'overview',
        section: 'start-here',
        order: 10,
        title: 'Platform Overview',
        label: 'Overview',
        summary: 'What Ever Works is, the mental model behind Missions, Ideas, Works and Agents, and the surfaces you use it from.',
        keywords: ['overview', 'introduction', 'platform', 'mental model', 'surfaces'],
        documents: [],
        related: ['getting-started', 'dashboard', 'new-page'],
        reviewedAt: '2026-09-14',
        source: 'docs/overview.md',
        docsUrl: 'https://docs.ever.works/overview',
        headings: [
            { id: 'what-ever-works-is', text: 'What Ever Works is', level: 2 },
            { id: 'the-mental-model', text: 'The mental model', level: 3 },
            { id: 'how-it-works', text: 'How It Works', level: 2 },
            { id: 'surfaces', text: 'Surfaces', level: 2 },
            { id: 'technology-stack', text: 'Technology Stack', level: 2 },
            { id: 'key-repositories', text: 'Key Repositories', level: 2 },
            { id: 'ai-providers', text: 'AI Providers', level: 2 },
            { id: 'plugin-system', text: 'Plugin System', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'getting-started',
        section: 'start-here',
        order: 20,
        title: 'Getting Started',
        label: 'Getting Started',
        summary: 'The hosted path and the self-hosted path, the plugin keys you need, and how to create your first Work.',
        keywords: [
            'getting started',
            'first work',
            'setup',
            'install',
            'self-host',
            'keys',
        ],
        documents: ['DASHBOARD'],
        related: ['overview', 'creating-a-work', 'plugins'],
        reviewedAt: '2026-09-14',
        source: 'docs/getting-started.md',
        docsUrl: 'https://docs.ever.works/getting-started',
        headings: [
            { id: 'hosted-or-local', text: 'Hosted or local?', level: 2 },
            { id: 'the-hosted-path', text: 'The hosted path', level: 3 },
            { id: 'quick-start', text: 'Quick Start', level: 2 },
            { id: '1-prerequisites', text: '1. Prerequisites', level: 3 },
            { id: '2-clone-and-install', text: '2. Clone and Install', level: 3 },
            {
                id: '3-build-workspace-packages',
                text: '3. Build Workspace Packages',
                level: 3,
            },
            { id: '4-configure-environment', text: '4. Configure Environment', level: 3 },
            { id: '5-start-the-dev-servers', text: '5. Start the Dev Servers', level: 3 },
            { id: 'configuring-plugins', text: 'Configuring Plugins', level: 2 },
            {
                id: 'github-plugin-git-provider--required',
                text: 'GitHub Plugin (Git Provider) — Required',
                level: 3,
            },
            {
                id: 'ai-provider--required-for-generation',
                text: 'AI Provider — Required for Generation',
                level: 3,
            },
            {
                id: 'search-provider--recommended',
                text: 'Search Provider — Recommended',
                level: 3,
            },
            {
                id: 'screenshot-provider--optional',
                text: 'Screenshot Provider — Optional',
                level: 3,
            },
            {
                id: 'minimum-viable-configuration',
                text: 'Minimum Viable Configuration',
                level: 3,
            },
            { id: 'your-first-work', text: 'Your First Work', level: 2 },
            { id: 'development-commands', text: 'Development Commands', level: 2 },
            {
                id: 'api-documentation-interactive',
                text: 'API Documentation (Interactive)',
                level: 2,
            },
            { id: 'next-steps', text: 'Next Steps', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'new-page',
        section: 'start-here',
        order: 30,
        title: 'The + New page',
        label: 'The + New page',
        summary: 'One page to start anything: a Mission, an Idea, an Agent, a Task, a Work, a repository or a company.',
        keywords: ['new', 'create', 'start', 'chips', 'prompt'],
        documents: ['DASHBOARD_NEW'],
        related: ['missions', 'creating-a-work', 'tasks'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/new-page.md',
        docsUrl: 'https://docs.ever.works/features/new-page',
        headings: [
            { id: 'what-is-on-the-page', text: 'What is on the page', level: 2 },
            { id: 'the-chips', text: 'The chips', level: 2 },
            {
                id: 'which-chip-is-selected-when-you-arrive',
                text: 'Which chip is selected when you arrive',
                level: 3,
            },
            {
                id: 'what-happens-when-you-press-create',
                text: 'What happens when you press Create',
                level: 2,
            },
            { id: 'mission', text: 'Mission', level: 3 },
            { id: 'idea', text: 'Idea', level: 3 },
            { id: 'agent', text: 'Agent', level: 3 },
            { id: 'task', text: 'Task', level: 3 },
            {
                id: 'website-landing-page-blog-directory-awesome-repo',
                text: 'Website, Landing Page, Blog, Directory, Awesome Repo',
                level: 3,
            },
            { id: 'repository', text: 'Repository', level: 3 },
            { id: 'company', text: 'Company', level: 3 },
            { id: 'deep-links', text: 'Deep links', level: 2 },
            {
                id: 'switching-kinds-off-per-environment',
                text: 'Switching kinds off per environment',
                level: 2,
            },
            { id: 'how-to-use', text: 'How to use', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'dashboard',
        section: 'start-here',
        order: 40,
        title: 'The Dashboard',
        label: 'Dashboard',
        summary: 'The home page, the sidebar, the header, the Help drawer and the keyboard shortcuts.',
        keywords: [
            'home',
            'dashboard',
            'sidebar',
            'needs attention',
            'shortcuts',
            'help drawer',
        ],
        documents: ['DASHBOARD'],
        related: ['overview', 'inbox', 'settings-map'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/dashboard.md',
        docsUrl: 'https://docs.ever.works/features/dashboard',
        headings: [
            { id: 'the-home-page-at-', text: 'The home page at /', level: 2 },
            { id: 'the-nine-stat-tiles', text: 'The nine stat tiles', level: 3 },
            { id: 'needs-attention', text: 'Needs attention', level: 3 },
            { id: 'coming-up', text: 'Coming up', level: 3 },
            { id: 'action-approvals', text: 'Action approvals', level: 3 },
            { id: 'missions', text: 'Missions', level: 3 },
            { id: 'ideas', text: 'Ideas', level: 3 },
            { id: 'works', text: 'Works', level: 3 },
            { id: 'tasks', text: 'Tasks', level: 3 },
            { id: 'agents', text: 'Agents', level: 3 },
            { id: 'the-sidebar', text: 'The sidebar', level: 2 },
            { id: 'organization-switcher', text: 'Organization switcher', level: 3 },
            { id: '-new', text: '+ New', level: 3 },
            { id: 'navigation', text: 'Navigation', level: 3 },
            { id: 'collapse-toggle', text: 'Collapse toggle', level: 3 },
            { id: 'runner-status', text: 'Runner status', level: 3 },
            { id: 'profile-menu', text: 'Profile menu', level: 3 },
            { id: 'the-chat-panel', text: 'The chat panel', level: 3 },
            { id: 'the-header', text: 'The header', level: 2 },
            { id: 'the-help-drawer', text: 'The Help drawer', level: 2 },
            { id: 'keyboard-shortcuts', text: 'Keyboard shortcuts', level: 2 },
            { id: 'how-to', text: 'How to', level: 2 },
            {
                id: 'triage-your-account-in-two-minutes',
                text: 'Triage your account in two minutes',
                level: 3,
            },
            {
                id: 'get-a-fresh-batch-of-ideas',
                text: 'Get a fresh batch of Ideas',
                level: 3,
            },
            {
                id: 'approve-a-proposal-from-the-api',
                text: 'Approve a proposal from the API',
                level: 3,
            },
            {
                id: 'switch-to-another-organization',
                text: 'Switch to another Organization',
                level: 3,
            },
            {
                id: 'pick-up-onboarding-where-you-left-off',
                text: 'Pick up onboarding where you left off',
                level: 3,
            },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'missions',
        section: 'running-the-loop',
        order: 10,
        title: 'Missions',
        label: 'Missions',
        summary: 'A long-running goal that keeps finding Ideas and building Works until you mark it complete.',
        keywords: ['mission', 'goal', 'schedule', 'auto-build', 'delegate', 'brief'],
        documents: ['DASHBOARD_MISSIONS', 'DASHBOARD_MISSIONS_NEW', 'DASHBOARD_MISSION'],
        related: ['ideas', 'creating-a-work', 'budgets-and-usage'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/missions.md',
        docsUrl: 'https://docs.ever.works/features/missions',
        headings: [
            {
                id: 'when-to-use-a-mission-vs-a-work',
                text: 'When to use a Mission vs a Work',
                level: 2,
            },
            { id: 'creating-a-mission', text: 'Creating a Mission', level: 2 },
            { id: 'mission-lifecycle', text: 'Mission lifecycle', level: 2 },
            { id: 'run-now', text: 'Run-now', level: 3 },
            { id: 'auto-build-works', text: 'Auto-build Works', level: 2 },
            { id: 'outstanding-ideas-cap', text: 'Outstanding-Ideas cap', level: 2 },
            {
                id: 'attached-works-and-relations',
                text: 'Attached Works and relations',
                level: 2,
            },
            { id: 'the-six-relation-kinds', text: 'The six relation kinds', level: 3 },
            {
                id: 'the-rules-that-make-it-safe',
                text: 'The rules that make it safe',
                level: 3,
            },
            { id: 'how-to-attach-a-work', text: 'How to attach a Work', level: 3 },
            { id: 'how-to-detach', text: 'How to detach', level: 3 },
            {
                id: 'seeing-it-from-the-work-side',
                text: 'Seeing it from the Work side',
                level: 3,
            },
            { id: 'the-rest-surface', text: 'The REST surface', level: 3 },
            { id: 'attachments', text: 'Attachments', level: 2 },
            { id: 'cloning-a-mission', text: 'Cloning a Mission', level: 2 },
            { id: 'deleting-a-mission', text: 'Deleting a Mission', level: 2 },
            { id: 'where-to-go-next', text: 'Where to go next', level: 2 },
        ],
    },
    {
        id: 'ideas',
        section: 'running-the-loop',
        order: 20,
        title: 'Ideas',
        label: 'Ideas',
        summary: 'Candidate Works proposed by you or a Mission: accept, build, refresh or retry them.',
        keywords: ['idea', 'build', 'accept', 'refresh', 'failed idea'],
        documents: ['DASHBOARD_IDEAS', 'DASHBOARD_IDEAS_NEW', 'DASHBOARD_IDEA'],
        related: ['missions', 'creating-a-work', 'budgets-and-usage'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/ideas.md',
        docsUrl: 'https://docs.ever.works/features/ideas',
        headings: [
            { id: 'idea-lifecycle', text: 'Idea lifecycle', level: 2 },
            { id: 'build-vs-accept', text: 'Build vs Accept', level: 2 },
            { id: 'refreshing-ideas', text: 'Refreshing Ideas', level: 2 },
            { id: 'failed-ideas', text: 'Failed Ideas', level: 2 },
            { id: 'mission-spawned-ideas', text: 'Mission-spawned Ideas', level: 2 },
            { id: 'cost--budget', text: 'Cost & budget', level: 2 },
            { id: 'api', text: 'API', level: 2 },
        ],
    },
    {
        id: 'creating-a-work',
        section: 'running-the-loop',
        order: 30,
        title: 'Creating a Work',
        label: 'Creating a Work',
        summary: 'Create a Work with AI, by hand, by import or from an Idea, and how its git and deploy providers are chosen.',
        keywords: ['work', 'website', 'create', 'import', 'deploy', 'generation'],
        documents: ['DASHBOARD_WORKS', 'DASHBOARD_WORKS_NEW', 'DASHBOARD_WORK'],
        related: ['new-page', 'ideas', 'knowledge-base'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/creating-a-work.md',
        docsUrl: 'https://docs.ever.works/features/creating-a-work',
        headings: [
            { id: 'start-from-new', text: 'Start from /new', level: 2 },
            { id: 'how-you-get-to-the-form', text: 'How you get to the form', level: 3 },
            { id: 'the-entry-view', text: 'The entry view', level: 3 },
            { id: 'pick-a-kind', text: 'Pick a kind', level: 3 },
            { id: 'pick-a-blueprint', text: 'Pick a blueprint', level: 3 },
            { id: 'creation-methods', text: 'Creation Methods', level: 2 },
            { id: 'ai-creation', text: 'AI Creation', level: 2 },
            { id: 'what-you-provide', text: 'What You Provide', level: 3 },
            { id: 'provider-selection', text: 'Provider Selection', level: 3 },
            { id: 'dynamic-plugin-fields', text: 'Dynamic Plugin Fields', level: 3 },
            {
                id: 'what-happens-after-submission',
                text: 'What Happens After Submission',
                level: 3,
            },
            { id: 'manual-creation', text: 'Manual Creation', level: 2 },
            { id: 'what-you-provide-1', text: 'What You Provide', level: 3 },
            {
                id: 'what-happens-after-submission-1',
                text: 'What Happens After Submission',
                level: 3,
            },
            { id: 'import', text: 'Import', level: 2 },
            { id: 'source-selection', text: 'Source Selection', level: 3 },
            {
                id: 'provider-selection-for-import',
                text: 'Provider Selection for Import',
                level: 3,
            },
            { id: 'from-an-idea', text: 'From an Idea', level: 2 },
            { id: 'start-a-campaign', text: 'Start a campaign', level: 2 },
            { id: 'repository-works', text: 'Repository Works', level: 2 },
            { id: 'app-works', text: 'App Works', level: 2 },
            { id: 'common-concepts', text: 'Common Concepts', level: 2 },
            { id: 'git-provider', text: 'Git Provider', level: 3 },
            { id: 'deploy-provider', text: 'Deploy Provider', level: 3 },
            {
                id: 'deploy-provider-selector--what-is-in-the-list',
                text: 'Deploy Provider Selector — What Is in the List',
                level: 3,
            },
            {
                id: 'git-provider-picker--connection-states',
                text: 'Git Provider Picker — Connection States',
                level: 3,
            },
            { id: 'repository-owner', text: 'Repository Owner', level: 3 },
            {
                id: 'how-provider-defaults-work',
                text: 'How Provider Defaults Work',
                level: 3,
            },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'tasks',
        section: 'running-the-loop',
        order: 40,
        title: 'Tasks',
        label: 'Tasks',
        summary: 'Units of work an Agent picks up: create, prioritise, run, gate and schedule them, and read the board.',
        keywords: [
            'task',
            'kanban',
            'board',
            'sub-task',
            'priority',
            'blocked',
            'recurring',
        ],
        documents: [
            'DASHBOARD_TASKS',
            'DASHBOARD_TASK_NEW',
            'DASHBOARD_TASK',
            'DASHBOARD_TASK_TRIGGERS',
        ],
        related: ['agents', 'sessions-and-steering', 'approvals-and-escalations'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/tasks.md',
        docsUrl: 'https://docs.ever.works/features/tasks',
        headings: [
            {
                id: 'when-to-use-a-task-vs-a-work-mission-or-idea',
                text: 'When to use a Task vs a Work, Mission or Idea',
                level: 2,
            },
            { id: 'creating-a-task', text: 'Creating a Task', level: 2 },
            {
                id: 'labels-are-derived-from-the-title-until-you-touch-them',
                text: 'Labels are derived from the title until you touch them',
                level: 3,
            },
            { id: 'starting-from-a-template', text: 'Starting from a template', level: 3 },
            {
                id: 'building-a-task-tree-from-a-workflow-template',
                text: 'Building a task tree from a workflow template',
                level: 3,
            },
            {
                id: 'a-template-step-can-live-in-another-repository',
                text: 'A template step can live in another repository',
                level: 3,
            },
            { id: 'priorities', text: 'Priorities', level: 2 },
            {
                id: 'scoping-a-task-to-a-work-mission-or-idea',
                text: 'Scoping a Task to a Work, Mission or Idea',
                level: 2,
            },
            { id: 'sub-tasks', text: 'Sub-tasks', level: 2 },
            {
                id: 'the-list-its-views-and-its-filters',
                text: 'The list, its views and its filters',
                level: 2,
            },
            { id: 'working-on-the-board', text: 'Working on the board', level: 3 },
            { id: 'the-triggers-tab', text: 'The Triggers tab', level: 2 },
            { id: 'statuses-and-transitions', text: 'Statuses and transitions', level: 2 },
            {
                id: 'what-can-refuse-a-transition',
                text: 'What can refuse a transition',
                level: 3,
            },
            { id: 'who-can-move-a-task', text: 'Who can move a Task', level: 3 },
            {
                id: 'running-a-task-with-an-agent',
                text: 'Running a Task with an Agent',
                level: 2,
            },
            { id: 'run', text: 'Run', level: 3 },
            { id: 'moving-to-in-progress', text: 'Moving to In progress', level: 3 },
            {
                id: 'acceptance-checks-quality-gates',
                text: 'Acceptance checks (quality gates)',
                level: 2,
            },
            {
                id: 'settled-decisions-this-task-may-re-open',
                text: 'Settled decisions this Task may re-open',
                level: 2,
            },
            {
                id: 'editing-a-task-afterwards',
                text: 'Editing a Task afterwards',
                level: 2,
            },
            {
                id: 'scheduling-a-task-run-once-scheduled-recurring',
                text: 'Scheduling a Task: Run once, Scheduled, Recurring',
                level: 2,
            },
            { id: 'scheduled-one-shot', text: 'Scheduled (one-shot)', level: 3 },
            { id: 'recurring-tasks', text: 'Recurring Tasks', level: 2 },
            {
                id: 'starting-unblocked-tasks-automatically',
                text: 'Starting unblocked Tasks automatically',
                level: 2,
            },
            { id: 'deleting-a-task', text: 'Deleting a Task', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'inbox',
        section: 'running-the-loop',
        order: 50,
        title: 'Inbox (Questions, Approvals, Escalations & Notices)',
        label: 'Inbox',
        summary: 'Questions, approvals, escalations and notices addressed to you, and how to answer them.',
        keywords: [
            'inbox',
            'decisions',
            'questions',
            'approvals',
            'escalations',
            'answer',
        ],
        documents: ['DASHBOARD_INBOX'],
        related: ['approvals-and-escalations', 'notifications', 'tasks'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/inbox.md',
        docsUrl: 'https://docs.ever.works/features/inbox',
        headings: [
            { id: 'what-the-inbox-is-not', text: 'What the Inbox is not', level: 2 },
            {
                id: 'the-four-kinds-of-message',
                text: 'The four kinds of message',
                level: 2,
            },
            { id: 'finding-it', text: 'Finding it', level: 2 },
            { id: 'reading-a-message', text: 'Reading a message', level: 2 },
            { id: 'answering-a-question', text: 'Answering a question', level: 2 },
            {
                id: 'what-happens-when-you-press-send',
                text: 'What happens when you press Send',
                level: 3,
            },
            {
                id: 'approvals-are-option-only',
                text: 'Approvals are option-only',
                level: 3,
            },
            { id: 'housekeeping', text: 'Housekeeping', level: 2 },
            { id: 'my-decisions', text: 'My Decisions', level: 2 },
            { id: 'how-the-queue-is-ordered', text: 'How the queue is ordered', level: 3 },
            { id: 'filtering-and-linking', text: 'Filtering and linking', level: 3 },
            { id: 'answering-with-a-reason', text: 'Answering, with a reason', level: 3 },
            { id: 'what-happens-to-the-work', text: 'What happens to the work', level: 3 },
            {
                id: 'how-to-answer-a-blocking-question',
                text: 'How to answer a blocking question',
                level: 2,
            },
            { id: 'how-an-agent-asks-you', text: 'How an agent asks you', level: 2 },
            { id: 'producers', text: 'Producers', level: 2 },
            { id: 'api', text: 'API', level: 2 },
            { id: 'delivery', text: 'Delivery', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'activity',
        section: 'running-the-loop',
        order: 60,
        title: 'Activity',
        label: 'Activity',
        summary: 'The record of everything the platform did for you, the Schedules view, filters and CSV export.',
        keywords: ['activity', 'log', 'schedules', 'history', 'export', 'generation'],
        documents: ['DASHBOARD_ACTIVITY'],
        related: ['tasks', 'notifications', 'sessions-and-steering'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/activity.md',
        docsUrl: 'https://docs.ever.works/features/activity',
        headings: [
            { id: 'which-view-you-want', text: 'Which view you want', level: 2 },
            { id: 'the-log-view', text: 'The Log view', level: 2 },
            { id: 'columns', text: 'Columns', level: 3 },
            { id: 'table-and-board', text: 'Table and Board', level: 3 },
            {
                id: 'stopping-a-running-generation',
                text: 'Stopping a running generation',
                level: 3,
            },
            { id: 'summary-cards', text: 'Summary cards', level: 2 },
            { id: 'filters', text: 'Filters', level: 2 },
            { id: 'exporting-to-csv', text: 'Exporting to CSV', level: 2 },
            { id: 'the-schedules-view', text: 'The Schedules view', level: 2 },
            { id: 'inbound-triggers', text: 'Inbound triggers', level: 3 },
            { id: 'the-live-feed-view', text: 'The Live Feed view', level: 2 },
            {
                id: 'per-work-feed-vs-the-global-log',
                text: 'Per-Work feed vs the global Log',
                level: 2,
            },
            {
                id: 'where-the-deployed-sites-events-land',
                text: 'Where the deployed site\'s events land',
                level: 3,
            },
            {
                id: 'external-activity-from-your-connectors',
                text: 'External activity from your connectors',
                level: 3,
            },
            {
                id: 'getting-the-same-activity-pushed-to-you',
                text: 'Getting the same activity pushed to you',
                level: 2,
            },
            { id: 'known-layout-trap', text: 'Known layout trap', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'goals',
        section: 'running-the-loop',
        order: 70,
        title: 'Goals',
        label: 'Goals',
        summary: 'A measurable target an Agent iterates towards, with a metric source and a lifecycle.',
        keywords: ['goal', 'metric', 'target', 'iteration', 'delivery'],
        documents: ['DASHBOARD_GOALS', 'DASHBOARD_GOALS_NEW'],
        related: ['missions', 'agents', 'tasks'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/goals.md',
        docsUrl: 'https://docs.ever.works/features/goals',
        headings: [
            { id: 'when-to-use-a-goal', text: 'When to use a Goal', level: 2 },
            { id: 'creating-a-goal', text: 'Creating a Goal', level: 2 },
            { id: 'delivery-goals', text: 'Delivery goals', level: 2 },
            {
                id: 'who-runs-a-brand-new-goal',
                text: 'Who runs a brand-new Goal',
                level: 3,
            },
            { id: 'concurrent-iterations', text: 'Concurrent iterations', level: 2 },
            { id: 'the-metric-source', text: 'The metric source', level: 2 },
            { id: 'lifecycle', text: 'Lifecycle', level: 2 },
            { id: 'evaluate-now', text: 'Evaluate now', level: 3 },
            { id: 'what-a-goal-does-not-do', text: 'What a Goal does not do', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'agents',
        section: 'your-agents',
        order: 10,
        title: 'Agents (Your AI Employees)',
        label: 'Agents',
        summary: 'Who your Agents are, what each one has, what they do on an idle tick and how to create one.',
        keywords: [
            'agent',
            'employee',
            'heartbeat',
            'workbench',
            'guardrails',
            'create agent',
        ],
        documents: ['DASHBOARD_AGENTS', 'DASHBOARD_AGENT_NEW', 'DASHBOARD_AGENT'],
        related: ['skills-catalog', 'teams', 'approvals-and-escalations'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/agents.md',
        docsUrl: 'https://docs.ever.works/features/agents',
        headings: [
            {
                id: 'the-work-agent-vs-your-own-agents',
                text: 'The Work Agent vs. your own Agents',
                level: 2,
            },
            { id: 'what-an-agent-has', text: 'What an Agent has', level: 2 },
            { id: 'agent-scope', text: 'Agent scope', level: 3 },
            {
                id: 'agents-as-an-organization',
                text: 'Agents as an organization',
                level: 2,
            },
            { id: 'agent-definition-files', text: 'Agent definition files', level: 2 },
            {
                id: 'heartbeats--what-an-agent-does-on-an-idle-tick',
                text: 'Heartbeats — what an Agent does on an idle tick',
                level: 2,
            },
            { id: 'memory', text: 'Memory', level: 2 },
            { id: 'tasks-skills-and-email', text: 'Tasks, skills, and email', level: 2 },
            { id: 'budgets--guardrails', text: 'Budgets & guardrails', level: 2 },
            { id: 'the-agents-workbench', text: 'The Agents workbench', level: 2 },
            { id: 'the-ten-tabs', text: 'The ten tabs', level: 3 },
            { id: 'creating-an-agent', text: 'Creating an Agent', level: 2 },
            { id: 'see-also', text: 'See also', level: 2 },
        ],
    },
    {
        id: 'skills-catalog',
        section: 'your-agents',
        order: 20,
        title: 'Skills Catalog',
        label: 'Skills Catalog',
        summary: 'Reusable capabilities an Agent can use, the SKILL.md format and how to attach Skills to Agents.',
        keywords: ['skill', 'skills', 'catalog', 'attach', 'capability'],
        documents: ['DASHBOARD_SKILLS', 'DASHBOARD_SKILL_NEW', 'DASHBOARD_SKILL'],
        related: ['agents', 'knowledge-base', 'plugins'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/skills-catalog.md',
        docsUrl: 'https://docs.ever.works/features/skills-catalog',
        headings: [
            { id: 'the-skillmd-format', text: 'The SKILL.md format', level: 2 },
            {
                id: 'the-public-ever-worksskills-catalog',
                text: 'The public ever-works/skills catalog',
                level: 2,
            },
            {
                id: 'the-everworks-skills-provider-plugin',
                text: 'The everworks-skills provider plugin',
                level: 2,
            },
            { id: 'autoenable', text: 'autoEnable', level: 3 },
            { id: 'go-to-market-skills', text: 'Go-to-market Skills', level: 2 },
            {
                id: 'attaching-skills-to-agents',
                text: 'Attaching Skills to Agents',
                level: 2,
            },
            { id: 'related-pages', text: 'Related pages', level: 2 },
        ],
    },
    {
        id: 'memory',
        section: 'your-agents',
        order: 30,
        title: 'Memory (Org-Wide)',
        label: 'Memory',
        summary: 'Everything your organization knows, gathered across every Work: search, review, consolidation and recall.',
        keywords: ['memory', 'review queue', 'consolidation', 'recall', 'meetings'],
        documents: ['DASHBOARD_MEMORY'],
        related: ['knowledge-base', 'agents', 'organizations'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/memory.md',
        docsUrl: 'https://docs.ever.works/features/memory',
        headings: [
            { id: 'knowledge-base-vs-memory', text: 'Knowledge Base vs Memory', level: 2 },
            { id: 'finding-it', text: 'Finding it', level: 2 },
            { id: 'searching-and-filtering', text: 'Searching and filtering', level: 2 },
            {
                id: 'how-to-find-something-across-every-work',
                text: 'How to find something across every Work',
                level: 3,
            },
            { id: 'adding-to-memory', text: 'Adding to Memory', level: 2 },
            { id: 'uploading-originals', text: 'Uploading originals', level: 3 },
            {
                id: 'organization-level-documents',
                text: 'Organization-level documents',
                level: 3,
            },
            { id: 'the-review-queue', text: 'The review queue', level: 2 },
            { id: 'how-to-clear-the-queue', text: 'How to clear the queue', level: 3 },
            { id: 'consolidation', text: 'Consolidation', level: 2 },
            {
                id: 'how-to-run-consolidation-on-demand',
                text: 'How to run consolidation on demand',
                level: 3,
            },
            { id: 'scheduled-consolidation', text: 'Scheduled consolidation', level: 3 },
            { id: 'memory-health', text: 'Memory health', level: 2 },
            { id: 'files', text: 'Files', level: 2 },
            {
                id: 'how-to-keep-a-memory-folder-in-git',
                text: 'How to keep a Memory folder in Git',
                level: 3,
            },
            { id: 'knowledge-library', text: 'Knowledge library', level: 2 },
            { id: 'agent-memory', text: 'Agent Memory', level: 2 },
            { id: 'meetings', text: 'Meetings', level: 2 },
            {
                id: 'recall-injection-into-runs',
                text: 'Recall injection into runs',
                level: 2,
            },
            {
                id: 'reaching-memory-from-a-machine',
                text: 'Reaching Memory from a machine',
                level: 2,
            },
            { id: 'coming-soon', text: 'Coming soon', level: 2 },
            { id: 'api-reference', text: 'API reference', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'knowledge-base',
        section: 'your-agents',
        order: 40,
        title: 'Knowledge Base & Memory',
        label: 'Knowledge Base & Memory',
        summary: 'A Work\'s own store of context: what lives in it, how files are ingested and how Agents search it.',
        keywords: ['knowledge base', 'kb', 'documents', 'ingest', 'search', 'upload'],
        documents: ['DASHBOARD_WORK_KB'],
        related: ['memory', 'creating-a-work', 'agents'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/knowledge-base.md',
        docsUrl: 'https://docs.ever.works/features/knowledge-base',
        headings: [
            { id: 'what-lives-in-the-kb', text: 'What lives in the KB', level: 2 },
            {
                id: 'git-backed-two-layer-storage',
                text: 'Git-backed, two-layer storage',
                level: 2,
            },
            { id: 'the-workbench', text: 'The workbench', level: 2 },
            {
                id: 'ingest-drop-a-file-get-usable-knowledge',
                text: 'Ingest: drop a file, get usable knowledge',
                level: 2,
            },
            {
                id: 'what-gets-extracted-from-what',
                text: 'What gets extracted from what',
                level: 3,
            },
            {
                id: 'how-to-upload-a-source-and-confirm-agents-can-read-it',
                text: 'How to upload a source and confirm agents can read it',
                level: 3,
            },
            {
                id: 'extractor-plugins--for-urls-not-uploads',
                text: 'Extractor plugins — for URLs, not uploads',
                level: 3,
            },
            {
                id: 'search-lexical-semantic-and-both',
                text: 'Search: lexical, semantic, and both',
                level: 2,
            },
            {
                id: 'vector-stores--where-the-embeddings-live',
                text: 'Vector stores — where the embeddings live',
                level: 2,
            },
            {
                id: 'how-to-move-a-works-embeddings-to-qdrant',
                text: 'How to move a Work\'s embeddings to Qdrant',
                level: 3,
            },
            { id: 'how-agents-use-it', text: 'How Agents use it', level: 2 },
            {
                id: 'locks-inheritance-and-audit',
                text: 'Locks, inheritance, and audit',
                level: 2,
            },
            {
                id: 'beyond-one-work-org-wide-memory',
                text: 'Beyond one Work: org-wide Memory',
                level: 3,
            },
            {
                id: 'reaching-the-kb-from-anywhere',
                text: 'Reaching the KB from anywhere',
                level: 2,
            },
            {
                id: 'how-to-drive-the-kb-from-an-mcp-client',
                text: 'How to drive the KB from an MCP client',
                level: 3,
            },
            {
                id: 'how-to-script-the-kb-from-the-cli',
                text: 'How to script the KB from the CLI',
                level: 3,
            },
            { id: 'see-also', text: 'See also', level: 2 },
        ],
    },
    {
        id: 'teams',
        section: 'your-agents',
        order: 50,
        title: 'Teams',
        label: 'Teams',
        summary: 'Group Agents into teams with roles and resources, nest them and read the Org Chart.',
        keywords: ['team', 'roster', 'roles', 'org chart', 'nesting'],
        documents: [
            'DASHBOARD_TEAMS',
            'DASHBOARD_TEAM_NEW',
            'DASHBOARD_TEAM',
            'DASHBOARD_ORG_CHART',
        ],
        related: ['agents', 'organizations'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/teams.md',
        docsUrl: 'https://docs.ever.works/features/teams',
        headings: [
            {
                id: 'teams-vs-the-other-groupings',
                text: 'Teams vs. the other groupings',
                level: 2,
            },
            { id: 'creating-a-team', text: 'Creating a team', level: 2 },
            {
                id: 'the-slug-is-derived-and-permanent',
                text: 'The slug is derived and permanent',
                level: 3,
            },
            { id: 'the-team-page', text: 'The team page', level: 2 },
            { id: 'roster--adding-agents', text: 'Roster — adding Agents', level: 3 },
            { id: 'roles', text: 'Roles', level: 3 },
            {
                id: 'resources--what-a-team-owns',
                text: 'Resources — what a team owns',
                level: 2,
            },
            { id: 'nesting-teams', text: 'Nesting teams', level: 2 },
            { id: 'the-org-chart', text: 'The Org Chart', level: 2 },
            { id: 'settings-and-deleting', text: 'Settings and deleting', level: 2 },
            { id: 'getting-teams-pre-built', text: 'Getting teams pre-built', level: 2 },
            { id: 'a-trap-worth-knowing', text: 'A trap worth knowing', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'organizations',
        section: 'setup-and-connections',
        order: 10,
        title: 'Organizations, Invitations & Company Registration',
        label: 'Organizations',
        summary: 'Switch workspaces, create an Organization, invite members and register a company.',
        keywords: ['organization', 'workspace', 'invite', 'members', 'company'],
        documents: [],
        related: ['teams', 'settings-map', 'credits-and-billing'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/organizations.md',
        docsUrl: 'https://docs.ever.works/features/organizations',
        headings: [
            { id: 'the-workspace-switcher', text: 'The workspace switcher', level: 2 },
            {
                id: 'how-to-create-an-organization',
                text: 'How to create an Organization',
                level: 2,
            },
            {
                id: 'the-first-organization-asks-about-your-existing-work',
                text: 'The first Organization asks about your existing work',
                level: 3,
            },
            { id: 'settings--organization', text: 'Settings → Organization', level: 2 },
            { id: 'the-vision-field', text: 'The Vision field', level: 3 },
            { id: 'members-and-invitations', text: 'Members and invitations', level: 2 },
            { id: 'how-to-invite-someone', text: 'How to invite someone', level: 3 },
            {
                id: 'what-the-invited-person-sees',
                text: 'What the invited person sees',
                level: 3,
            },
            {
                id: 'invitation-rules-worth-knowing',
                text: 'Invitation rules worth knowing',
                level: 3,
            },
            { id: 'roles-exactly-one-today', text: 'Roles: exactly one, today', level: 3 },
            { id: 'tenant-vs-organization', text: 'Tenant vs. Organization', level: 2 },
            { id: 'register-a-company', text: 'Register a Company', level: 2 },
            { id: 'how-to-register-one', text: 'How to register one', level: 3 },
            {
                id: 'prebuilt-companies-import-a-whole-company',
                text: 'Prebuilt companies: import a whole company',
                level: 2,
            },
            { id: 'how-to-import-one', text: 'How to import one', level: 3 },
            { id: 'what-you-get', text: 'What you get', level: 3 },
            {
                id: 'when-the-template-step-is-missing',
                text: 'When the template step is missing',
                level: 3,
            },
            {
                id: 'what-else-is-scoped-to-an-organization',
                text: 'What else is scoped to an Organization',
                level: 2,
            },
            {
                id: 'platform-admin-is-a-different-thing-entirely',
                text: 'Platform admin is a different thing entirely',
                level: 3,
            },
            { id: 'api-reference', text: 'API reference', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'plugins',
        section: 'setup-and-connections',
        order: 20,
        title: 'Plugins',
        label: 'Plugins',
        summary: 'Enable, configure and disable plugins, at account level or for one Work.',
        keywords: ['plugin', 'provider', 'enable', 'credentials', 'integration'],
        documents: ['DASHBOARD_PLUGINS', 'DASHBOARD_PLUGIN_DETAIL'],
        related: ['settings-map', 'job-runtimes', 'getting-started'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/plugins.md',
        docsUrl: 'https://docs.ever.works/features/plugins',
        headings: [
            {
                id: 'plugins-vs-the-pages-that-look-like-plugins',
                text: 'Plugins vs. the pages that look like plugins',
                level: 2,
            },
            { id: 'what-the-page-shows', text: 'What the page shows', level: 2 },
            { id: 'categories', text: 'Categories', level: 2 },
            {
                id: 'where-each-category-is-documented-in-full',
                text: 'Where each category is documented in full',
                level: 3,
            },
            { id: 'enabling-a-plugin', text: 'Enabling a plugin', level: 2 },
            {
                id: 'also-enable-for-all-works',
                text: '"Also enable for all works"',
                level: 3,
            },
            { id: 'there-is-no-install-step', text: 'There is no install step', level: 3 },
            {
                id: 'account-level-vs-work-level',
                text: 'Account level vs. Work level',
                level: 2,
            },
            { id: 'disabling-a-plugin', text: 'Disabling a plugin', level: 2 },
            { id: 'settings-and-credentials', text: 'Settings and credentials', level: 2 },
            {
                id: 'which-plugin-serves-a-capability',
                text: 'Which plugin serves a capability',
                level: 2,
            },
            {
                id: 'what-breaks-without-a-provider',
                text: 'What breaks without a provider',
                level: 2,
            },
            {
                id: 'when-a-plugins-code-loads',
                text: 'When a plugin\'s code loads',
                level: 2,
            },
            {
                id: 'what-an-operator-can-change',
                text: 'What an operator can change',
                level: 3,
            },
            {
                id: 'dynamic-plugin-distribution',
                text: 'Dynamic plugin distribution',
                level: 2,
            },
            { id: 'what-an-operator-sets', text: 'What an operator sets', level: 3 },
            { id: 'install-on-use', text: 'Install-on-use', level: 3 },
            { id: 'sandbox-sessions', text: 'Sandbox sessions', level: 3 },
            {
                id: 'background-jobs-the-worker',
                text: 'Background jobs (the worker)',
                level: 3,
            },
            { id: 'the-admin-allowlist', text: 'The admin allowlist', level: 3 },
            {
                id: 'installing-and-what-refuses',
                text: 'Installing, and what refuses',
                level: 3,
            },
            {
                id: 'how-to-install-a-distributable-plugin',
                text: 'How to install a distributable plugin',
                level: 3,
            },
            { id: 'on-small-screens', text: 'On small screens', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'notifications',
        section: 'setup-and-connections',
        order: 30,
        title: 'Notifications, Channels & Preferences',
        label: 'Notifications',
        summary: 'The bell, delivery channels beyond the dashboard, and which events reach you where.',
        keywords: ['notification', 'bell', 'channel', 'preferences', 'alerts'],
        documents: ['DASHBOARD_SETTINGS_NOTIFICATIONS'],
        related: ['inbox', 'activity', 'settings-map'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/notifications.md',
        docsUrl: 'https://docs.ever.works/features/notifications',
        headings: [
            {
                id: 'how-a-notification-travels',
                text: 'How a notification travels',
                level: 2,
            },
            { id: 'in-app-the-bell', text: 'In-app: the bell', level: 2 },
            { id: 'types-and-categories', text: 'Types and categories', level: 3 },
            { id: 'the-in-app-api', text: 'The in-app API', level: 3 },
            { id: 'the-novu-inbox-embed', text: 'The Novu inbox embed', level: 3 },
            {
                id: 'channels-delivery-beyond-the-dashboard',
                text: 'Channels: delivery beyond the dashboard',
                level: 2,
            },
            { id: 'the-five-providers', text: 'The five providers', level: 3 },
            {
                id: 'adding-testing-and-removing',
                text: 'Adding, testing and removing',
                level: 3,
            },
            {
                id: 'limits-and-delivery-mechanics',
                text: 'Limits and delivery mechanics',
                level: 3,
            },
            { id: 'the-channels-api', text: 'The channels API', level: 3 },
            {
                id: 'agents-can-post-to-a-channel',
                text: 'Agents can post to a channel',
                level: 2,
            },
            {
                id: 'event-subscriptions-which-event-goes-where',
                text: 'Event subscriptions: which event goes where',
                level: 2,
            },
            {
                id: 'how-the-platform-resolves-channels-for-an-event',
                text: 'How the platform resolves channels for an event',
                level: 3,
            },
            { id: 'the-preferences-api', text: 'The preferences API', level: 3 },
            {
                id: 'validation-rules-that-will-bite-you',
                text: 'Validation rules that will bite you',
                level: 3,
            },
            {
                id: 'what-triggers-a-notification',
                text: 'What triggers a notification',
                level: 2,
            },
            {
                id: 'other-ways-things-reach-you',
                text: 'Other ways things reach you',
                level: 2,
            },
            {
                id: 'how-to-from-zero-to-a-slack-ping',
                text: 'How to: from zero to a Slack ping',
                level: 2,
            },
            { id: 'troubleshooting', text: 'Troubleshooting', level: 2 },
            { id: 'see-also', text: 'See also', level: 2 },
        ],
    },
    {
        id: 'settings-map',
        section: 'setup-and-connections',
        order: 40,
        title: 'The Settings Map',
        label: 'Settings Map',
        summary: 'Where every settings page lives, including the ones the settings sidebar does not list.',
        keywords: ['settings', 'account', 'preferences', 'configuration'],
        documents: ['DASHBOARD_SETTINGS'],
        related: ['plugins', 'notifications', 'credits-and-billing'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/settings-map.md',
        docsUrl: 'https://docs.ever.works/features/settings-map',
        headings: [
            { id: 'account-and-platform', text: 'Account and platform', level: 2 },
            {
                id: 'email-addresses-is-a-v0-shell',
                text: 'Email Addresses is a v0 shell',
                level: 3,
            },
            { id: 'the-plugins-section', text: 'The PLUGINS section', level: 2 },
            { id: 'usage--credits', text: 'Usage & Credits', level: 2 },
            { id: 'the-costs-tab', text: 'The Costs tab', level: 3 },
            {
                id: 'pages-the-sidebar-does-not-list',
                text: 'Pages the sidebar does not list',
                level: 2,
            },
            { id: 'billing--payment-method', text: 'Billing → Payment method', level: 3 },
            { id: 'related-pages', text: 'Related pages', level: 2 },
        ],
    },
    {
        id: 'budgets-and-usage',
        section: 'money-and-limits',
        order: 10,
        title: 'Budgets & Usage',
        label: 'Budgets & Usage',
        summary: 'Cap AI spend per Work, Mission, Idea or account, and what happens when a cap is hit.',
        keywords: ['budget', 'cap', 'limit', 'spend', 'usage', 'cost'],
        documents: [
            'DASHBOARD_USAGE',
            'DASHBOARD_WORK_SETTINGS_BUDGETS',
            'DASHBOARD_AGENT_BUDGETS',
        ],
        related: ['credits-and-billing', 'missions', 'approvals-and-escalations'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/budgets-and-usage.md',
        docsUrl: 'https://docs.ever.works/features/budgets-and-usage',
        headings: [
            { id: 'what-gets-counted', text: 'What gets counted', level: 2 },
            { id: 'account-wide-caps', text: 'Account-wide caps', level: 2 },
            { id: 'per-mission-caps', text: 'Per-Mission caps', level: 2 },
            {
                id: 'per-idea--per-work-budgets',
                text: 'Per-Idea + per-Work budgets',
                level: 2,
            },
            { id: 'billing-modes', text: 'Billing modes', level: 2 },
            {
                id: 'what-happens-when-a-cap-is-hit',
                text: 'What happens when a cap is hit',
                level: 2,
            },
            {
                id: 'where-the-numbers-come-from',
                text: 'Where the numbers come from',
                level: 2,
            },
            { id: 'api', text: 'API', level: 2 },
            { id: 'where-to-go-next', text: 'Where to go next', level: 2 },
        ],
    },
    {
        id: 'credits-and-billing',
        section: 'money-and-limits',
        order: 20,
        title: 'Credits & Billing',
        label: 'Credits & Billing',
        summary: 'Credits, the ledger, the Billing and Usage & Credits pages, plans and seats.',
        keywords: ['credits', 'billing', 'invoice', 'plan', 'seats', 'payment'],
        documents: ['DASHBOARD_SETTINGS_BILLING', 'DASHBOARD_SETTINGS_PAYMENT_METHOD'],
        related: ['budgets-and-usage', 'settings-map'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/credits-and-billing.md',
        docsUrl: 'https://docs.ever.works/features/credits-and-billing',
        headings: [
            {
                id: 'the-ledger-is-the-source-of-truth',
                text: 'The ledger is the source of truth',
                level: 2,
            },
            {
                id: 'buckets-and-what-gets-spent-first',
                text: 'Buckets and what gets spent first',
                level: 3,
            },
            { id: 'allowances', text: 'Allowances', level: 3 },
            { id: 'the-billing-page', text: 'The Billing page', level: 2 },
            { id: 'pay-as-you-go', text: 'Pay-as-you-go', level: 2 },
            { id: 'the-usage--credits-page', text: 'The Usage & Credits page', level: 2 },
            { id: 'choosing-the-period', text: 'Choosing the period', level: 3 },
            { id: 'period-totals', text: 'Period totals', level: 3 },
            { id: 'the-four-breakdowns', text: 'The four breakdowns', level: 3 },
            { id: 'export-csv', text: 'Export CSV', level: 3 },
            { id: 'plan-entitlements', text: 'Plan entitlements', level: 2 },
            { id: 'seats', text: 'Seats', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'sessions-and-steering',
        section: 'when-something-goes-wrong',
        order: 10,
        title: 'Sessions & Run Steering',
        label: 'Sessions & Steering',
        summary: 'Why a run sits queued, how to steer or interrupt a live run, and how to resume a parked one.',
        keywords: ['stuck', 'queued', 'session', 'run', 'interrupt', 'resume'],
        documents: ['DASHBOARD_AGENT_SESSIONS', 'DASHBOARD_AGENT_SESSION'],
        related: ['agents', 'tasks', 'job-runtimes'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/sessions-and-steering.md',
        docsUrl: 'https://docs.ever.works/features/sessions-and-steering',
        headings: [
            { id: 'the-sessions-list', text: 'The Sessions list', level: 2 },
            { id: 'where-to-find-it', text: 'Where to find it', level: 3 },
            { id: 'what-a-row-tells-you', text: 'What a row tells you', level: 3 },
            {
                id: 'attach-a-terminal-to-a-live-run',
                text: 'Attach a terminal to a live run',
                level: 3,
            },
            {
                id: 'why-a-run-sits-queued--the-dispatch-gate',
                text: 'Why a run sits queued — the dispatch gate',
                level: 2,
            },
            { id: 'the-queued-reasons', text: 'The queued reasons', level: 3 },
            { id: 'the-valves', text: 'The valves', level: 3 },
            {
                id: 'how-a-parked-run-gets-promoted',
                text: 'How a parked run gets promoted',
                level: 3,
            },
            {
                id: 'when-a-queue-is-not-moving',
                text: 'When a queue is not moving',
                level: 3,
            },
            { id: 'steering-a-live-run', text: 'Steering a live run', level: 2 },
            { id: 'interrupting', text: 'Interrupting', level: 2 },
            {
                id: 'awaiting-input--the-amber-badge-and-where-you-answer-it',
                text: 'Awaiting input — the amber badge, and where you answer it',
                level: 2,
            },
            { id: 'resuming-a-parked-run', text: 'Resuming a parked run', level: 2 },
            { id: 'ownership', text: 'Ownership', level: 2 },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'approvals-and-escalations',
        section: 'when-something-goes-wrong',
        order: 20,
        title: 'Approvals, Escalations & Guardrail Modes',
        label: 'Approvals & Escalations',
        summary: 'What an Agent may do on its own, why a proposal waits for you, and what happens when a run gives up.',
        keywords: ['approval', 'escalation', 'guardrails', 'auto-pause', 'failure'],
        documents: [],
        related: ['inbox', 'agents', 'sessions-and-steering'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/approvals-and-escalations.md',
        docsUrl: 'https://docs.ever.works/features/approvals-and-escalations',
        headings: [
            {
                id: 'guardrails-what-an-agent-may-do-on-its-own',
                text: 'Guardrails: what an Agent may do on its own',
                level: 2,
            },
            { id: 'the-decision-table', text: 'The decision table', level: 3 },
            { id: 'setting-guardrails', text: 'Setting guardrails', level: 3 },
            {
                id: 'risk-flags-why-a-proposal-queues-anyway',
                text: 'Risk flags: why a proposal queues anyway',
                level: 2,
            },
            { id: 'the-approval-queue', text: 'The approval queue', level: 2 },
            { id: 'api', text: 'API', level: 3 },
            {
                id: 'escalations-when-a-run-gives-up',
                text: 'Escalations: when a run gives up',
                level: 2,
            },
            {
                id: 'confidence--so-the-queue-ranks-instead-of-merely-listing',
                text: 'Confidence — so the queue ranks instead of merely listing',
                level: 3,
            },
            { id: 'api-1', text: 'API', level: 3 },
            { id: 'delivery', text: 'Delivery', level: 3 },
            {
                id: 'hitl-questions-a-run-that-parks-until-you-answer',
                text: 'HITL questions: a run that parks until you answer',
                level: 2,
            },
            {
                id: 'the-safety-nets-around-it',
                text: 'The safety nets around it',
                level: 2,
            },
            {
                id: 'auto-pause-after-n-failures',
                text: 'Auto-pause after N failures',
                level: 3,
            },
            { id: 'the-doom-loop-detector', text: 'The doom-loop detector', level: 3 },
            {
                id: 'how-to-start-strict-then-relax',
                text: 'How to: start strict, then relax',
                level: 2,
            },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
    {
        id: 'job-runtimes',
        section: 'when-something-goes-wrong',
        order: 30,
        title: 'Job Runtimes',
        label: 'Job Runtimes',
        summary: 'The engine that runs background work, how to choose one and what to check when nothing runs.',
        keywords: ['background work', 'job runtime', 'worker', 'queue', 'not running'],
        documents: ['DASHBOARD_SETTINGS_JOB_RUNTIME'],
        related: ['sessions-and-steering', 'plugins', 'getting-started'],
        reviewedAt: '2026-09-14',
        source: 'docs/features/job-runtimes.md',
        docsUrl: 'https://docs.ever.works/features/job-runtimes',
        headings: [
            {
                id: 'workers-versus-job-runtimes',
                text: 'Workers versus job runtimes',
                level: 2,
            },
            { id: 'the-six-bundled-runtimes', text: 'The six bundled runtimes', level: 2 },
            {
                id: 'how-the-runtimes-differ-in-practice',
                text: 'How the runtimes differ in practice',
                level: 3,
            },
            {
                id: 'choosing-the-runtime-for-a-self-hosted-instance',
                text: 'Choosing the runtime for a self-hosted instance',
                level: 2,
            },
            {
                id: 'how-to-run-a-self-hosted-triggerdev-webapp-with-docker-compose',
                text: 'How to: run a self-hosted Trigger.dev webapp with Docker Compose',
                level: 3,
            },
            { id: 'settings--job-runtime', text: 'Settings → Job Runtime', level: 2 },
            { id: 'the-three-modes', text: 'The three modes', level: 3 },
            {
                id: 'credentials-a-pointer-not-a-paste-box',
                text: 'Credentials: a pointer, not a paste-box',
                level: 3,
            },
            { id: 'the-four-actions', text: 'The four actions', level: 3 },
            {
                id: 'how-to-point-your-organization-at-your-own-triggerdev-project',
                text: 'How to: point your organization at your own Trigger.dev project',
                level: 3,
            },
            {
                id: 'how-to-manage-the-overlay-over-the-api',
                text: 'How to: manage the overlay over the API',
                level: 3,
            },
            { id: 'operator-controls', text: 'Operator controls', level: 2 },
            {
                id: 'the-instance-wide-allow-list',
                text: 'The instance-wide allow-list',
                level: 3,
            },
            {
                id: 'the-per-tenant-allow-list-screen',
                text: 'The per-tenant allow-list screen',
                level: 3,
            },
            { id: 'fleet-nodes-as-a-runtime', text: 'Fleet nodes as a runtime', level: 2 },
            {
                id: 'the-desktop-apps-runtime-picker',
                text: 'The Desktop app\'s runtime picker',
                level: 2,
            },
            {
                id: 'what-is-wired-and-what-is-not',
                text: 'What is wired, and what is not',
                level: 2,
            },
            { id: 'related', text: 'Related', level: 2 },
        ],
    },
] as const satisfies readonly HelpArticleMeta[];
