export const README = [
	'## What is the Zapier Automation plugin?',
	'',
	'This plugin triggers a [Zapier](https://zapier.com) action during a directory generation stage.',
	'Instead of running the built-in AI pipeline, you pick any Zapier action — either a custom Zap you have built',
	'or one of the thousands of native actions published by Zapier apps — and this plugin invokes it when the pipeline runs.',
	'',
	'## Why use it?',
	'',
	'- **Reuse existing automation** — trigger Zaps you already maintain as part of directory generation',
	'- **9,000+ apps** — invoke any Zapier-supported service without writing integration code here',
	'- **Two result modes** — accept structured `{ items: [...] }` output *or* map raw records via field aliases',
	'- **Deduplication** — existing directory items are summarized and forwarded to the action to avoid duplicates',
	'',
	'## Getting started',
	'',
	'1. Install the Zapier SDK CLI locally: `npm i -g @zapier/zapier-sdk-cli` (or use `npx zapier-sdk …`).',
	'2. Create client credentials — these are how you prove identity to the Zapier SDK in production:',
	'   ```bash',
	'   npx zapier-sdk create-client-credentials',
	'   # → prints ZAPIER_CLIENT_ID and ZAPIER_CLIENT_SECRET',
	'   ```',
	'3. Exchange credentials for an access token (or run `npx zapier-sdk login` in interactive environments).',
	'4. Paste the token into the plugin settings as **Access Token**.',
	'5. Identify the action you want to run. Every Zapier action is addressed by a triple:',
	'   - `app_key` — the app slug (e.g. `slack`, `google_sheets`)',
	'   - `action_type` — one of `search | filter | read | read_bulk | run | search_and_write | search_or_write | write`',
	'   - `action_key` — the action slug (e.g. `send_message`)',
	'6. Look up the **authentication ID** (the numeric id of the Zapier connection that should run the action) and set it in settings or per-generation.',
	'',
	'> **Note.** The plugin always requires an explicit authentication ID — it will not auto-pick a connection on your behalf.',
	'',
	'## How it works',
	'',
	'1. **Validate Zapier Connection** — verifies the token and fetches the action metadata via `getAction`',
	'2. **Prepare Action Payload** — builds input with directory metadata, existing items summary, and any custom parameters',
	'3. **Execute Zapier Action** — calls `runAction({ appKey, actionType, actionKey, authenticationId, inputs })`',
	'4. **Collect & Validate Results** — parses the response according to the selected result shape and deduplicates',
	'5. **Capture Screenshots** — optionally captures screenshots for generated items using the configured screenshot provider',
	'6. **Cleanup** — releases resources',
	'',
	'## Result shapes',
	'',
	'### Structured (default — recommended for custom Zaps)',
	'',
	'Return a JSON object with an `items` array from your Zap (for example from a "Code by Zapier" or "Webhooks by Zapier" final step):',
	'',
	'```json',
	'{',
	'  "items": [',
	'    {',
	'      "name": "Tool Name",',
	'      "description": "A concise description (1-3 sentences)",',
	'      "url": "https://example.com",',
	'      "category": "Category Name",',
	'      "tags": ["tag1", "tag2"],',
	'      "content": "Optional longer markdown content",',
	'      "brand": "Optional brand name",',
	'      "images": ["https://example.com/screenshot.png"]',
	'    }',
	'  ]',
	'}',
	'```',
	'',
	'**Required fields per item:** `name`. **Strongly recommended:** `description`, `url`, `category`, `tags`.',
	'',
	'### Native (map raw Zapier records)',
	'',
	'If the action returns raw domain records (e.g. a `search` action that returns Airtable rows, Notion pages, or Hubspot contacts), switch the *Result Shape* to **Native** and provide a field mapping.',
	'Field paths are dot-separated and also support numeric indices for arrays, e.g. `fields.0.value`.',
	'',
	'| Mapping field | Example | What it maps to |',
	'| --- | --- | --- |',
	'| `name_field` (required) | `title` | `item.name` |',
	'| `url_field` | `link` | `item.source_url` |',
	'| `description_field` | `summary` | `item.description` |',
	'| `category_field` | `category` | `item.category` |',
	'| `tags_field` | `tags` | `item.tags` (array or comma-separated string) |',
	'| `image_field` | `image_url` | `item.images` |',
	'| `brand_field` | `brand` | `item.brand` |',
	'| `content_field` | `body` | `item.markdown` |',
	'',
	'## Workflow input contract',
	'',
	'Regardless of the result shape, the plugin passes the same object as `inputs` to the action:',
	'',
	'```json',
	'{',
	'  "metadata": {',
	'    "directoryId": "dir-123",',
	'    "directoryName": "Best AI Tools",',
	'    "directorySlug": "best-ai-tools",',
	'    "directoryDescription": "A curated list of the best AI tools",',
	'    "prompt": "Find the best AI writing tools",',
	'    "generationMethod": "create-update",',
	'    "targetItems": 50',
	'  },',
	'  "existingSummary": {',
	'    "totalItems": 10,',
	'    "categories": ["Writing", "Image Generation"],',
	'    "tags": ["free", "open-source"],',
	'    "sampleItems": [{ "name": "ChatGPT", "url": "https://chat.openai.com" }]',
	'  },',
	'  "actionParams": { "...": "custom fields set in the Advanced form section" }',
	'}',
	'```',
	'',
	'- `existingSummary` is omitted if the directory is empty or the user disables it',
	'- `actionParams` contains any custom key-value pairs pasted into the Advanced form section',
	'- `metadata.targetItems` is the number of new items the user wants'
].join('\n');
