export const README = [
	'## What is the Zapier Automation plugin?',
	'',
	'This plugin lets Ever Works directory generation invoke any **Zapier catalog action** — the thousands of pre-built actions published by Zapier apps (Gmail, Slack, Google Sheets, Airtable, Notion, …) plus the built-in "Webhooks by Zapier" and "Code by Zapier" apps. When you pick this plugin as a directory\'s pipeline, the plugin calls the Zapier SDK\'s `runAction({ appKey, actionType, actionKey, authenticationId, inputs })` during the execute step and converts the response into directory items according to the selected result shape.',
	'',
	'> **Catalog actions ≠ Zaps.** This plugin invokes Zapier app actions directly, not user-built Zaps. If you want a Zap you built to run during generation, give it a **Webhooks by Zapier → Catch Hook** trigger and have this plugin invoke the hook via `webhook.write.custom` (requires a Webhooks-by-Zapier connection in your account).',
	'',
	'## Why use it?',
	'',
	'- **Reuse existing automation** — invoke any of the 9,000+ apps on Zapier without writing integration code here',
	'- **Three result shapes** — return structured `{ items: [...] }`, map raw records via field aliases, or fire a side-effect action with no expected items',
	'- **Production-ready auth** — supports both long-lived OAuth client credentials and short-lived browser-login JWTs',
	'- **Deduplication** — existing directory items are summarized and forwarded to the action so your Zap can avoid producing duplicates',
	'',
	'## Getting started',
	'',
	'### 1. Install the Zapier SDK CLI (one-time)',
	'',
	'```bash',
	'npm i -g @zapier/zapier-sdk-cli',
	'# …or use npx without installing:',
	'npx zapier-sdk --help',
	'```',
	'',
	'### 2. Pick an authentication method',
	'',
	'All credentials are entered directly in the plugin settings UI — **the plugin does not read any environment variables**. You configure them once in **Settings → Plugins → Zapier Automation** and they\'re stored per user.',
	'',
	'The plugin supports two paths. **Production uses client credentials; local dev can use either.**',
	'',
	'#### Path A — Client credentials (recommended for production)',
	'',
	'Long-lived `clientId` + `clientSecret` pair.',
	'',
	'```bash',
	'npx zapier-sdk create-client-credentials "everworks-prod"',
	'# → prints:',
	'#   client_id: ckc_xxx…',
	'#   client_secret: cks_xxx…   (shown once — copy it now)',
	'```',
	'',
	'Paste both into **Settings → Plugins → Zapier Automation** as **Zapier Client ID** and **Zapier Client Secret**, then click **Save**.',
	'',
	'#### Path B — Access token (local dev only)',
	'',
	'Short-lived bearer JWT (~15 min lifetime) obtained from browser login:',
	'',
	'```bash',
	'npx zapier-sdk login',
	'# macOS — pull the JWT out of the keychain:',
	'security find-generic-password -s "zapier-sdk-cli" -w | jq -r .login_jwt',
	'```',
	'',
	'Copy the printed JWT (starts with `eyJ…`) and paste it into the **Zapier Access Token** setting. When it expires, re-run `npx zapier-sdk login`, re-extract, and update the field.',
	'',
	'> **Precedence.** If both are configured, the plugin prefers `clientId + clientSecret` over `accessToken`.',
	'',
	'### 3. Identify the action you want to invoke',
	'',
	'Every Zapier catalog action is addressed by a triple plus a connection (authentication) ID:',
	'',
	'| Field | What it is | How to find it |',
	'| --- | --- | --- |',
	'| `app_key` | The Zapier app slug (`gmail`, `slack`, `google_sheets`, `webhook`, `code`) | `npx zapier-sdk list-apps` |',
	'| `action_type` | One of `search` `filter` `read` `read_bulk` `run` `search_and_write` `search_or_write` `write` | Listed alongside each action in `list-actions` |',
	'| `action_key` | The action slug within the app (first token in parentheses, e.g. `message` for Gmail send) | `npx zapier-sdk list-actions <app_key>` |',
	'| `authentication_id` | UUID of the Zapier connection that will run the action (e.g. `020432e5-b0c7-…`) | `npx zapier-sdk list-connections <app_key>` |',
	'',
	'Inspect an action\'s required inputs before wiring it in:',
	'',
	'```bash',
	'npx zapier-sdk get-action gmail write message',
	'```',
	'',
	'And dry-run it end-to-end from the CLI before pointing the plugin at it:',
	'',
	'```bash',
	'npx zapier-sdk run-action gmail write message \\',
	'  --authentication-id <connection-uuid> \\',
	'  --inputs \'{"to":"you@example.com","subject":"Test","body":"Hello"}\'',
	'```',
	'',
	'If the CLI dry-run works, the plugin will succeed with the same values.',
	'',
	'> **Connection must match the action\'s app.** A Gmail connection cannot run a Slack action. Always use `list-connections <app>` to get an ID compatible with the action you\'re calling. Mismatches produce `invalid_authentication: "The app linked to this authentication is not compatible with the provided app"`.',
	'',
	'### 4. Configure the plugin per directory',
	'',
	'Open a directory → generation modal → select **Zapier Automation** as the pipeline → fill the form:',
	'',
	'- **App Key**, **Action Type**, **Action Key** — the triple from step 3',
	'- **Authentication ID** — the connection UUID from step 3',
	'- **Result Shape** — see next section',
	'- **Custom Action Parameters** (Advanced) — JSON with the fields the action expects (e.g. `{ "to": "…", "subject": "…", "body": "…" }` for Gmail send)',
	'',
	'## Result shapes',
	'',
	'Choose the mode that matches what your action returns:',
	'',
	'### Structured — `{ items: [...] }` *(best for custom Zaps that produce items)*',
	'',
	'Use when the action\'s response body is a JSON object containing an `items` array (or a bare array). Each item becomes a directory record.',
	'',
	'```json',
	'{',
	'  "items": [',
	'    {',
	'      "name": "Tool Name",',
	'      "description": "A concise description (1-3 sentences)",',
	'      "url": "https://example.com",',
	'      "category": "Category Name",',
	'      "tags": ["tag1", "tag2"],',
	'      "content": "Optional longer markdown content",',
	'      "brand": "Optional brand name",',
	'      "images": ["https://example.com/screenshot.png"]',
	'    }',
	'  ]',
	'}',
	'```',
	'',
	'**Required per item:** `name`. **Strongly recommended:** `description`, `url`, `category`, `tags`.',
	'',
	'**How to produce this shape:**',
	'',
	'- A custom Zap ending in a **Code by Zapier** step that outputs `{ items: [...] }`, exposed via a webhook',
	'- Your own Zapier Platform app whose action\'s `perform` returns `{ items: [...] }`',
	'- An external HTTP endpoint (reached via `webhook.read.get` or `webhook.write.custom`) that serves this JSON',
	'',
	'> Gmail `write.message`, Slack `write.send_message`, and similar **send/post/create** actions return a confirmation (e.g. `{ id, threadId, labelIds }`) — not items. For those, use **side-effect** mode instead.',
	'',
	'### Native — raw records with field mapping *(best for search / read actions)*',
	'',
	'Use when the action returns a list of domain records (Airtable rows, Notion pages, Hubspot contacts, Gmail search results, Google Sheets rows, …). Each record is projected onto a directory item via the field mapping you provide.',
	'',
	'Field paths are dot-separated and support numeric array indices (e.g. `fields.0.value`).',
	'',
	'| Mapping field | Example path | Becomes |',
	'| --- | --- | --- |',
	'| `name_field` **(required)** | `title` | `item.name` |',
	'| `url_field` | `link` | `item.source_url` |',
	'| `description_field` | `summary` | `item.description` |',
	'| `category_field` | `category` | `item.category` |',
	'| `tags_field` | `tags` | `item.tags` (array or comma-separated string) |',
	'| `image_field` | `image_url` | `item.images` |',
	'| `brand_field` | `brand` | `item.brand` |',
	'| `content_field` | `body` | `item.markdown` |',
	'',
	'### Side-effect — fire-and-forget *(best for send/post/create actions)*',
	'',
	'Use when the action is invoked purely for its effect (send email, post Slack message, create Trello card). The plugin:',
	'',
	'- Executes the action',
	'- Logs the response for visibility',
	'- Completes successfully with **zero directory items**',
	'',
	'Typical use cases: generation-complete notifications, audit trails, triggering downstream workflows.',
	'',
	'**Example — send an email on generation:**',
	'',
	'| Field | Value |',
	'| --- | --- |',
	'| App Key | `gmail` |',
	'| Action Type | `write` |',
	'| Action Key | `message` |',
	'| Authentication ID | your Gmail connection UUID |',
	'| Result Shape | **Side-effect only** |',
	'| Custom Action Parameters | `{ "to": "you@example.com", "subject": "Generation done", "body": "…" }` |',
	'',
	'## Workflow input contract',
	'',
	'Regardless of the result shape, the plugin forwards the same payload to the action as `inputs`. User-supplied `action_params` are **spread at the top level** so catalog actions receive their expected field names directly, while also being preserved under `actionParams` for custom Zaps that want the envelope context.',
	'',
	'```json',
	'{',
	'  "metadata": {',
	'    "directoryId": "dir-123",',
	'    "directoryName": "Best AI Tools",',
	'    "directorySlug": "best-ai-tools",',
	'    "directoryDescription": "A curated list of the best AI tools",',
	'    "prompt": "Find the best AI writing tools",',
	'    "generationMethod": "create-update",',
	'    "targetItems": 50',
	'  },',
	'  "existingSummary": {',
	'    "totalItems": 10,',
	'    "categories": ["Writing", "Image Generation"],',
	'    "tags": ["free", "open-source"],',
	'    "sampleItems": [{ "name": "ChatGPT", "url": "https://chat.openai.com" }]',
	'  },',
	'  "actionParams": { "to": "…", "subject": "…", "body": "…" },',
	'  "to": "…",',
	'  "subject": "…",',
	'  "body": "…"',
	'}',
	'```',
	'',
	'- `existingSummary` is omitted when the directory is empty or the user disables it via **Pass Existing Items Summary**',
	'- Each key from `actionParams` is **also flattened at the root** — this is why Gmail sees `to`/`subject`/`body` where it expects them',
	'- On collision, user-supplied `action_params` keys win over envelope keys (useful if an action happens to have a field named `metadata`)',
	'- `metadata.targetItems` is the number of new items the user asked for',
	'',
	'## Pipeline steps',
	'',
	'1. **Validate Zapier Connection** — resolves the action metadata via `getAction`; fails fast on bad triples or expired auth',
	'2. **Prepare Action Payload** — builds the `inputs` object (envelope + flattened `action_params`)',
	'3. **Execute Zapier Action** — calls `runAction(...)`; honours abort signal for mid-run cancellation',
	'4. **Collect & Validate Results** — parses the response per the selected result shape; deduplicates items against existing names',
	'5. **Capture Screenshots** — optional; skipped unless enabled and a screenshot provider is configured',
	'6. **Cleanup** — releases resources',
	'',
	'## Troubleshooting',
	'',
	'| Symptom | Likely cause | Fix |',
	'| --- | --- | --- |',
	'| `Zapier authentication is not configured` | No credentials in settings | Set either Client ID + Secret or Access Token |',
	'| `Zapier app "X" was not found` | Typo in app_key, or your credentials lack access | Confirm via `npx zapier-sdk list-apps \\| grep -i X` |',
	'| `Zapier action or authentication not found` | Wrong `action_key` slug (remember: CLI does fuzzy matching, the SDK doesn\'t) | Run `npx zapier-sdk list-actions <app>` — action key is the first token in parentheses |',
	'| `invalid_authentication: … not compatible with the provided app` | Your connection is for a different app than the action | Use `npx zapier-sdk list-connections <app>` to get an `app`-specific UUID |',
	'| `Required field "X" is missing` | The action expects a field you didn\'t supply | Run `npx zapier-sdk get-action <app> <type> <key>` to see the input schema; add the field to Custom Action Parameters |',
	'| `Zapier access token is invalid or expired` | JWT expired (~15 min lifetime) | Re-run `npx zapier-sdk login` and re-export, or switch to client credentials |',
	'| `Zapier rejected the action inputs` | Required inputs missing or malformed | Check the action\'s input schema; required fields must appear at top-level of Custom Action Parameters |',
	'| `Zapier action returned a structured response but with no usable items` | Selected Structured mode but the action returned a confirmation (not items) | Switch Result Shape to **Side-effect only** for send/post/create actions, or **Native** for search/read actions |',
	'| `none could be mapped to directory items` | Native mode: `name_field` resolved to empty strings | Fix the Name Field path — check an actual record shape with `get-action` |',
	'| `rate limit exceeded` | Too many calls to Zapier | Wait and retry; consider increasing **Action Timeout** |',
	'',
	'## Limitations',
	'',
	'- **Cannot invoke user-built Zaps directly.** The plugin addresses the Zapier action catalog, not the Zap registry. Bridge via a Catch Hook URL if needed.',
	'- **Built-in app connections must already exist.** Webhooks-by-Zapier and Code-by-Zapier connections are typically created via the Zap editor UI, not the SDK CLI.',
	'- **Access tokens are short-lived.** Use client credentials in any environment where the plugin runs longer than 15 minutes without user intervention.',
	'- **`authentication_id` is always required.** The plugin never auto-picks a connection — mismatched connections produce clear errors rather than silent wrong-account writes.'
].join('\n');
