export const README = [
	'## What is the Zapier Automation plugin?',
	'',
	'This plugin delegates directory generation work to [Zapier](https://zapier.com), so Ever Works can connect with the apps and services your team already uses.',
	'Use it to pull records from tools like Airtable, Notion, Google Sheets, or HubSpot, or to trigger follow-up actions such as sending notifications after generation finishes.',
	'',
	'## Why use it?',
	'',
	'- **Thousands of app integrations** — connect Ever Works generation to apps available through Zapier',
	'- **Flexible outputs** — create directory items from structured results or mapped records',
	'- **Side-effect actions** — send messages, create tasks, or trigger downstream workflows without producing items',
	'- **Deduplication** — existing directory items can be summarized and passed along to reduce duplicates',
	'',
	'## How it works',
	'',
	'1. **Validate** — checks that Zapier credentials and the selected app action are reachable',
	'2. **Prepare Payload** — builds the input with directory metadata, existing items summary, and custom parameters',
	'3. **Run Action** — sends the request to Zapier',
	'4. **Collect Results** — converts the response into directory items or completes a side-effect action',
	'5. **Capture Screenshots** — optionally captures screenshots for generated items using the configured screenshot provider',
	'6. **Cleanup** — releases resources',
	'',
	'## Result modes',
	'',
	'- **Structured items** — use when the action returns an `items` array that already matches the directory item shape',
	'- **Native records** — use when the action returns records and you want to map fields such as name, URL, description, category, tags, image, brand, or content',
	'- **Side-effect only** — use when the action should send a message, create a task, update another system, or trigger another workflow without adding directory items',
	'',
	'## Data passing strategies',
	'',
	'- **Inline summary** (default) — directory metadata and a sample of existing items are sent in the action input',
	'- **GitHub repository** — pass a repo URL and access token so the action can read the full dataset directly',
	'',
	'## Required configuration',
	'',
	'- **Zapier credentials** — connect with Client ID + Client Secret, or use an Access Token for local development',
	'- **App Key** — the Zapier app to run, such as `slack`, `google_sheets`, `airtable`, or `notion`',
	'- **Action Type** — the kind of Zapier action, such as `search`, `read`, `write`, or `run`',
	'- **Action Key** — the specific action inside the selected app',
	'- **Authentication ID** — the Zapier connection that should run the action',
	'',
	'## Action input & output',
	'',
	'Your Zapier action receives structured input fields and can return structured directory items.',
	'',
	'<details>',
	'<summary><strong>Input your action receives</strong></summary>',
	'',
	'```json',
	'{',
	'  "metadata": {',
	'    "directoryId": "dir-123",',
	'    "directoryName": "Best AI Tools",',
	'    "directorySlug": "best-ai-tools",',
	'    "directoryDescription": "A curated list of the best AI tools",',
	'    "prompt": "Find the best AI writing tools",',
	'    "generationMethod": "create-update",',
	'    "targetItems": 50',
	'  },',
	'  "existingSummary": {',
	'    "totalItems": 10,',
	'    "categories": ["Writing", "Image Generation"],',
	'    "tags": ["free", "open-source"],',
	'    "sampleItems": [{ "name": "ChatGPT", "url": "https://chat.openai.com" }]',
	'  },',
	'  "actionParams": {}',
	'}',
	'```',
	'',
	'- `existingSummary` is omitted when the directory is empty or the user disables it via **Pass Existing Items Summary**',
	'- `actionParams` contains any custom key-value pairs passed from the Advanced form section and is also used to fill the selected Zapier action inputs',
	'- `metadata.targetItems` is the number of new items the user asked for',
	'',
	'</details>',
	'',
	'<details>',
	'<summary><strong>Output your action can return</strong></summary>',
	'',
	'For Structured items mode, return a JSON object with an `items` array:',
	'',
	'```json',
	'{',
	'  "items": [',
	'    {',
	'      "name": "Tool Name",',
	'      "description": "A concise description (1-3 sentences)",',
	'      "url": "https://example.com",',
	'      "category": "Category Name",',
	'      "tags": ["tag1", "tag2"],',
	'      "content": "Optional longer markdown content",',
	'      "brand": "Optional brand name",',
	'      "images": ["https://example.com/screenshot.png"]',
	'    }',
	'  ]',
	'}',
	'```',
	'',
	'**Required field:** `name`',
	'',
	'**Recommended fields:** `description`, `url`, `category`, `tags`',
	'',
	'**Optional fields:** `content` (stored as markdown), `brand`, `images`',
	'',
	'</details>',
	'',
	'## Getting started',
	'',
	'1. Create or choose the Zapier app action you want Ever Works to run',
	'2. Connect Zapier credentials in the plugin settings',
	'3. Enable this plugin for a directory',
	'4. When generating a directory, select Zapier Automation as the pipeline',
	'5. Configure the app action, connection, result mode, and any custom action parameters'
].join('\n');
