---
kind: Service
apiVersion: v1
metadata:
  name: ever-works-web
spec:
  selector:
    app: ever-works-web
  ports:
    - name: web
      protocol: TCP
      port: 3100
      targetPort: 3100

---
kind: Service
apiVersion: v1
metadata:
  name: ever-works-api
spec:
  selector:
    app: ever-works-api
  ports:
    - name: web
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ever-works-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ever-works-api
  template:
    metadata:
      labels:
        app: ever-works-api
    spec:
      containers:
        - name: ever-works-api
          image: ghcr.io/ever-co/ever-works-api:latest
          env:
            - name: API_HOST
              value: 0.0.0.0
            - name: FIREBASE_API_KEY
              value: "$FIREBASE_API_KEY"
            - name: FIREBASE_AUTH_DOMAIN
              value: "$FIREBASE_AUTH_DOMAIN"
            - name: FIREBASE_DATABASE_URL
              value: "$FIREBASE_DATABASE_URL"
            - name: FIREBASE_PROJECT_ID
              value: "$FIREBASE_PROJECT_ID"
            - name: FIREBASE_STORAGE_BUCKET
              value: "$FIREBASE_STORAGE_BUCKET"
            - name: FIREBASE_MESSAGING_SENDER_ID
              value: "$FIREBASE_MESSAGING_SENDER_ID"
            - name: FIREBASE_APP_ID
              value: "$FIREBASE_APP_ID"
            - name: FIREBASE_MEASUREMENT_ID
              value: "$FIREBASE_MEASUREMENT_ID"
            - name: FIREBASE_ADMIN_PRIVATE_KEY
              value: "$FIREBASE_ADMIN_PRIVATE_KEY"
            - name: FIREBASE_ADMIN_CLIENT_EMAIL
              value: "$FIREBASE_ADMIN_CLIENT_EMAIL"

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"

          ports:
            - containerPort: 3100
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ever-works-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ever-works-web
  template:
    metadata:
      labels:
        app: ever-works-web
    spec:
      containers:
        - name: ever-works-web
          image: ghcr.io/ever-co/ever-works-web:latest
          env:
            - name: AUTH_SECRET
              value: "$AUTH_SECRET"
            - name: API_URL
              value: "http://ever-works-api:3100"
            - name: NEXT_PUBLIC_WEB_URL
              value: "https://app.ever.works"
          ports:
            - containerPort: 3100
              protocol: TCP

          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ever-works-web-ing
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: app.ever.works
      http:
        paths:
          - backend:
              service:
                name: ever-works-web
                port:
                  number: 3100
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - app.ever.works
      secretName: app.ever.works-tls

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ever-works-api-ing
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: api.ever.works
      http:
        paths:
          - backend:
              service:
                name: ever-works-api
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - api.ever.works
      secretName: api.ever.works-tls
