name: Deploy to Trigger.dev Dev

on:
  workflow_run:
    workflows: ["CI"]
    branches: [develop]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubicloud-standard-2

    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.13.1

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build workspace packages
        run: pnpm --filter @packages/agent build

      - name: 🚀 Verify Trigger.dev is available
        working-directory: packages/tasks
        env:
          TRIGGER_ACCESS_TOKEN: ${{ secrets.TRIGGER_ACCESS_TOKEN }}
        # Note: we don't use the `preview` env in Trigger.dev for now for deployments from the develop branch, 
        # because it requires a paid account and also because we want to use built-in scheduling in NestJs in the dev!
        # That's why we just run the login operation below.
        run: |
          npx trigger.dev@4.3.0 login
