export const README = [
	'# Claude Managed Agent Plugin',
	'',
	'Generate directory items with a hosted Claude-powered agent that can research, organize, and refine results over longer runs.',
	'',
	'## What is it?',
	'',
	'This plugin connects Ever Works to Claude Managed Agents so directory generation can run in Anthropic-managed infrastructure instead of a local CLI session. It is a good fit when you want a more hosted, long-running agent workflow for researching and updating directory content.',
	'',
	'## Why use it?',
	'',
	'- **Hosted agent runs** — generation happens in a managed environment without relying on a local Claude Code setup',
	'- **Long-running work** — useful for larger research and content-generation tasks that may take longer to complete',
	'- **Existing item awareness** — the agent can review current items and taxonomy before creating or updating results',
	'- **Directory-friendly output** — returns structured items, categories, tags, collections, and brands back into Ever Works',
	'',
	'## Comparison with Claude Code',
	'',
	'- **Claude Managed Agent Plugin** — best when you want a hosted Claude workflow for longer autonomous runs',
	'- **Claude Code Plugin** — best when you want generation driven by the local Claude Code toolchain',
	'- Both plugins aim to create or improve directory content, but they differ in where the agent run happens and how you authenticate it',
	'',
	'## Getting started',
	'',
	'1. Add an Anthropic API key with Managed Agents access',
	'2. Enable the Claude Managed Agent plugin for your workspace or directory',
	'3. Choose the Claude model you want to use',
	'4. Start generation as usual and let the agent return structured results to Ever Works',
	'',
	'## Notes',
	'',
	'- Managed Agents is currently in beta',
	'- This plugin is designed for autonomous runs and does not yet rely on manual tool confirmations during generation'
].join('\n');
